### ISSUE TITLE
Any chance of a "CS Education" Area?

### ISSUE THREAD

**Issue by acbart** [emeryberger/CSrankings#11]
This could represent SIGCSE, TOCE, CSE, ITiCSE, ICER, etc. I know it's not the most popular subfield, but we're growing in importance and popularity.

**Comment by emeryberger** [comment]
It's possible though it might not meet the inclusion criteria (at least 50 R1 institutions have published at least one paper in the last 10 years). What are the top three conferences for this area?

**Comment by acbart** [comment]
I can't imagine that it'd be hard to meet the criteria; I suspect SIGCSE alone would manage that.

I would suggest that the top three conferences are:
- SIGCSE: [Special Interest Group on Computer Science Education](http://dl.acm.org/event.cfm?id=RE175&CFID=606255620&CFTOKEN=45235379)
- ITiCSE: [Innovation and Technology in Computer Science Education](http://dl.acm.org/event.cfm?id=RE279&CFID=606255620&CFTOKEN=45235379)
- ICER: [International Computing Education Conference (ICER)](http://dl.acm.org/event.cfm?id=RE286&CFID=606255620&CFTOKEN=45235379)

I could see an argument for the CCCS conferences or the Koli conference, but I think those three are the big ones based on the [SIGCSE community](http://sigcse.org/sigcse/events) and the [ACM Special Interest Group Page](http://dl.acm.org/sig.cfm?id=SP927&CFID=606255620&CFTOKEN=45235379).

**Comment by emeryberger** [comment]
At this point, I do not see how SIGCSE can be included until it follows a more rigorous process of peer review that matches those of all the other represented communities - that is, until volunteer-based reviewing is replaced by traditional program committees composed of established experts.

http://sigcse2016.sigcse.org/reviewers/index.html

**Comment by acbart** [comment]
Well, issues with SIGCSE's review process aside, what about the other venues? TOCE, CSE, ITiCSE, etc. have more traditional review mechanisms and I'd be surprised to find out that none of them meet the established criteria.

**Comment by emeryberger** [comment]
CSRankings currently only includes journals that are the publication outlets for conferences.

What is the CSE to which you are referring? (DBLP link please.)

**Comment by acbart** [comment]
http://dblp2.uni-trier.de/db/journals/csedu/

**Comment by emeryberger** [comment]
Looks like it's an instance of a journal that is not a publication outlet for a conference.

**Comment by acbart** [comment]
> At this point, I do not see how SIGCSE can be included until it follows a more rigorous process of peer review that matches those of all the other represented communities - that is, until volunteer-based reviewing is replaced by traditional program committees composed of established experts.
> 
> http://sigcse2016.sigcse.org/reviewers/index.html

You know, coming back to this 4 years later now that I have a job, I just wanna say that it was a bad bit of logic. Your stated criteria on your website does not say anything about applying peer review criteria. I think you should either update your FAQ or include the metrics.

**Comment by emeryberger** [comment]
SIGCSE is and remains a unique case. It remains the case that SIGCSE - unlike all other areas I am aware of - not only relies entirely on community-based reviewing, but also does not appear distinguish between research articles and practitioner's experience reports in the proceedings. These are both unlike every other area of CS represented in CSrankings (this is not a metrics concern, and it's also not a frequently-asked question). It would certainly help make the case for including SIGCSE were it to move its research output to be in line with the standards of the broader CS community. It remains to be seen whether it would meet the stated criteria in the FAQ of representation among R1 institutions.

**Comment by acbart** [comment]
Well, you can make arguments based on merits about whether you agree with SIGCSE's reviewing policy, but at the end of the day there are budding researchers who are trying to apply to graduate school, and they're apparently using your ranking site. They're recommended by folks like Phil Guo and Google. Sure, maybe you think that they shouldn't be presented with CS Ed as an option because the field isn't up to your standards for rigor. But the fact is that some folks, thankfully, will still persist and want to know this kind of information because they have no starting point about what the partial order of schools is. Locking out CS Ed may keep these numbers slightly closer to your desired reality, but they aren't really helping future graduate students make decisions. And I don't think this field is going to get better by staying stagnate.

**Comment by a-cavalcanti** [comment]
Is there any possibility to include the education area now in 2022?

For example: LAK - https://dblp2.uni-trier.de/db/conf/lak/index.html , ICALT - https://dblp2.uni-trier.de/db/conf/icalt/index.html

**Comment by acbart** [comment]
@emeryberger Here's an opportunity to reconsider again, another couple years later! Perhaps its time to finally introduce CS Education into your rankings?

**Comment by SethPoulsen** [comment]
An alternative proposal--if we were to make the area title slightly more general, and call it "Computers and Education" instead of "CS Education", it could include applications of computer science to solving education problems that aren't necessarily computer science education. 

Then we could include the Artificial Intelligence in Education (AIED) and Educational Data Mining (EDM) conferences, giving us 3 conferences that meet @emeryberger's requirements: 

ICER, AIED, and EDM. 

What would people's thoughts be on that?

**Comment by SethPoulsen** [comment]
Another candidate for inclusion could be ACM's new Learning at Scale conference (L@S), which also meets the requirements.

**Comment by tmbarnes** [comment]
I agree, we need to add AI in Education, Educational Data Mining, Learning at Scale, ICER, ITiCSE, and SIGCSE. 

If SIGCSE is excluded, I could see that, if there is an explicit written policy about what kind of peer review structure is required, and if SIGCSE does not meet it, then it would be reasonable to exclude it.
