### ISSUE TITLE
make clean-dblp

### ISSUE THREAD

**Issue by joanna350** [emeryberger/CSrankings#1114]
I cannot get past this to download data. Other folks have gone past it alright it and I got the data through them, bu Drafty is empty and this command is blocking me from getting data on both of my laptops (Ubuntu & mac OS) each returning error137, error130.

**Comment by emeryberger** [comment]
I assume you have downloaded the data already (which you can do with `make download-dblp`). Perhaps you can post a screenshot of the issues you encounter.

**Comment by joanna350** [comment]
No because the command is part of `make download-dblp`.
Tried the following directly, as this is what is supposedly run.
`gunzip -dc dblp.xml.gz | awk 'NF' | xmllint --loaddtd --dtdattr --noent --path '.' -  > dblp-fixed.xml`
Ubuntu just kills the process (memory intensive I guess) and on MacOS everything slows down.
Looks like the links may help
https://stackoverflow.com/questions/726690/what-killed-my-process-and-why
https://backdrift.org/oom-killer-how-to-create-oom-exclusions-in-linux

**Comment by emeryberger** [comment]
Yes, it's memory intensive. There's really nothing to be done about that. You may just need to run this on a larger machine.
