### ISSUE TITLE
DBLP adding session chairs as papers

### ISSUE THREAD

**Issue by emidec** [emeryberger/CSrankings#1148]
Hi,

I just noticed DBLP added entries for session chairs of ACM CCS 2018 (https://dblp.org/db/conf/ccs/ccs2018.html), which means that the latest csrankings update got that one too. 

Clearly it's a DBLP/ACM bug but I thought it'd be worth it to raise as a possible issue.

Thanks

**Comment by emeryberger** [comment]
Yep, that's a pain. Thanks for pointing it out. I have sent a note to DBLP and will add some custom logic to workaround it for now.
