### ISSUE TITLE
Neural Information Processing Systems now uses the acronym NeurIPS

### ISSUE THREAD

**Issue by jeisner** [emeryberger/CSrankings#1183]
As you are probably aware, the acronym has been changed from NIPS to NeurIPS for D&I reasons.
Can you change the way it is displayed on the site?

![screenshot139](https://user-images.githubusercontent.com/2395181/49406722-6169b100-f724-11e8-8993-79864cb3dca3.png)

Perhaps it's also necessary to change the way you scrape the data.  I think both acronyms will be used for a while.  In particular, many past papers will continue to be listed as NIPS since that was the acronym at the time they were published.  However, the paper that just won the 10-year "test of time" award at NeurIPS 2018 was announced on a slide at the award presentation (a few minutes ago) as having appeared at NeurIPS 2007, not NIPS 2007.  So I went ahead and changed the NIPS entries to NeurIPS on my own CV.

Thanks!  I can provide more background if needed, or put you in touch with the relevant NeurIPS folks.

**Comment by emeryberger** [comment]
Hi @jeisner - thanks for bringing this up. I have been following this issue and considered changing it but I am now unsure about whether it would be confusing to do so. I am considering moving to a transitional "NeurIPS/NIPS" as DBLP is doing (see https://dblp1.uni-trier.de/db/conf/nips/). Thoughts?

**Comment by jeisner** [comment]
I think that would be reasonable.  It reassures people that their work is being counted either way.  In DBLP's case, it probably also ensures that either search query will match all the papers from the conference.

**Comment by emeryberger** [comment]
Great. Updated with https://github.com/emeryberger/CSrankings/commit/94a1266706b1b14bca71abb6310a5215135f3ee9.

**Comment by jeisner** [comment]
Thanks.  As a matter of form, you may also want to change the URL in that link from nips.cc to neurips.cc (both work at present).  

So, no other changes are necessary because you get your info from DBLP, and they are going to standardize everything as NeurIPS/NIPS?

**Comment by emeryberger** [comment]
DBLP: looks that way (internally, it is still "nips"), so nothing will change on my end for processing. But I will go ahead and change the link!

**Comment by aaroth** [comment]
It looks to me like NeuRIPS 2018 papers are not currently being counted (even though they are listed on DBLP).

**Comment by emeryberger** [comment]
Yeah, they changed it to "NeurIPS" in the newest DBLP (which I recently downloaded). Will fix momentarily. Thanks for the report!

**Comment by emeryberger** [comment]
Now fixed.
