### ISSUE TITLE
ECCV 2018 papers are missing

### ISSUE THREAD

**Issue by BernardGhanem** [emeryberger/CSrankings#1225]
Hi,

First off, I'd like to thank you for your efforts on csrankings. It really does come in handy. 

I came across an issue recently with the ECCV 2018 papers. They are all on DBLP but the retrieved results in csrankings seem to be only a fraction of what they should be. For example, they put me (Bernard Ghanem from KAUST) down for 2 papers, while the count should be 6. Same thing goes for the few other authors I checked (e.g. Wolfgang Heidrich at KAUST). We'd appreciate that you look into this weird behavior, so we maintain a complete ranking throughout the year.

Thanks 

----------------------------
Bernard Ghanem

Associate Professor of Electrical Engineering
Visual Computing Center
King Abdullah University of Science and Technology (KAUST)
Building 1, Room 2125
Thuwal 23955-6900, Saudi Arabia

Email: bernard.ghanem@kaust.edu.sa
Homepage: ivul.kaust.edu.sa; www.bernardghanem.com
Phone: +966 (0) 12 808-0261

**Comment by emeryberger** [comment]
Thanks for the report. This has been fixed. The issue is that there was a huge increase in the number of ECCV volumes, each of which needs separate handling.
