### ISSUE TITLE
csrankings.csv cleaning

### ISSUE THREAD

**Issue by SIG-SP** [emeryberger/CSrankings#1242]
Different People with Similar Names:

Line 4046: "rDfyQnIAAAAJ" -> "ql6BXwcAAAAJ"
Line 4052: "rDfyQnIAAAAJ" -> "qPDhlWkAAAAJ"

**Comment by emeryberger** [comment]
Thanks. Did you find this programatically?

**Comment by emeryberger** [comment]
(Fixed with https://github.com/emeryberger/CSrankings/commit/a0a9dfa094e2905c423c2195cacaa22ea623de5d)

**Comment by SIG-SP** [comment]
> Thanks. Did you find this programatically?

I found it by accident.

Maybe you can try parse each author name according to syllables, generate a bag of words for each author, and perform similarity join algorithm over the set of word bags using Jaccard similarity to find similar author names. Then, you can check manually whether different authors have the same Google Scholar ID or not in your CSV file.

**Comment by emeryberger** [comment]
well, for this particular issue, it's enough to verify that two authors who do not have the same DBLP name do not also have the same google scholar ID...

**Comment by emeryberger** [comment]
anyway, thanks! i wrote some code to check this and turned up lots of similar issues (but mostly missing aliases).
