### ISSUE TITLE
bug in associating research to a school?

### ISSUE THREAD

**Issue by billtang** [emeryberger/CSrankings#1245]
michael-franklin left Berkeley and joined Chicago in 2016. At present, all the publication of Michael Franklin is listed under Chicago even if you narrow the range prior to 2016.  I think this is a bug; he should have been listed under Berkeley instead.
http://csrankings.org/#/fromyear/2009/toyear/2014/index?all

Same issue with Ben Zhao listed under Chicago. I think he was in UC Santa Barbara up till 2017.

**Comment by emeryberger** [comment]
This is a feature, not a bug. When a faculty member moves, their portfolio accompanies them. They are not starting from scratch just by moving from one institution to another, and their ghostly halo does not survive to advise students in their absence at their old institution.
