### ISSUE TITLE
Consider adding AAMAS under Artificial Intelligence?

### ISSUE THREAD

**Issue by nandofioretto** [emeryberger/CSrankings#1256]
There are currently only two venues under AI (AAAI and IJCAI). 
AAMAS is a leading multi-agent conference and its popularity has been growing substantially in recent years. For instance, AAMAS 2018 had over 700 reviewed submissions [1] and the current edition seem to have exceeded this number by far. 

[1] http://ifaamas.org/Proceedings/aamas2018/pdfs/fm-welcome.pdf

**Comment by fycus-tree** [comment]
Emery previously responded on this topic at #37 . Not sure if his answer now will be any different.

**Comment by nandofioretto** [comment]
Thanks. IMHO the conference size should not matter as much as mentioned in #37. At least not for a tier-1 conference. It is natural that, in general, the more specialized is the venue, the less number of papers it will attract, simply because fewer researchers work in a specialized area. This, however, does not necessarily correlate with the publications' impact. AAMAS as an H5-index of 40, while IJCAI's is 45, according to [1]. 

[1] http://www.guide2research.com/topconf/machine-learning
