### ISSUE TITLE
UT Austin Faculty Update

### ISSUE THREAD

**Issue by shreydesai** [emeryberger/CSrankings#1332]
Proposing to add the following tenure-track faculty from the UT Austin Department of Linguistics. They do research with the computer science department, and can be categorized under "Natural Language Processing":

- Katrin Erk (http://www.katrinerk.com/)
- Jessy Li (https://jjessyli.github.io/)

Recent publications from both:

- https://arxiv.org/abs/1811.03554
- https://aclanthology.info/papers/D18-1175/d18-1175
- https://arxiv.org/abs/1811.05085
- https://www.aaai.org/Papers/AAAI/2019/AAAI-GaoYifan.7009.pdf

**Comment by shreydesai** [comment]
Also, Qiang Liu joined recently as well (https://www.cs.utexas.edu/~lqiang/). He can probably be categorized under "Machine learning & data mining".

**Comment by emeryberger** [comment]
Unless these faculty can _solely_ advise PhD students _in the Computer Science department_, they are not eligible for inclusion. (Erk is listed as affiliated faculty, which I assume grants this privilege; the CS faculty member clearly is; please submit a PR to add them. Jessy Li is not on that list.)

**Comment by shreydesai** [comment]
Thanks for the response! To clarify your first statement, are you saying that if they do not have the privilege of advising PhD students in the CS department, they are not eligible for inclusion? Jessy Li has two PhD students––one from the linguistics department and another co-advised with a professor (Greg Durrett) from the CS department, so I'm slightly confused on the requirement.

**Comment by emeryberger** [comment]
Your understanding is correct. This is in the FAQ.
