### ISSUE TITLE
Frequent collaboration leads to double count?

### ISSUE THREAD

**Issue by tongzhou80** [emeryberger/CSrankings#1338]
It's common that two or three professors collaborate on almost every single paper. In that case, they essentially get twice the count. Such can be shown that two professors in the same school and same area get very similar adjusted counts because they always appear on a paper together. So if one school has much more collaboration among faculties than another school, it tends to get more counts. By this standard, an easy way to manipulate the counts is to build a long term relationship with another professor within the institute, and always publish together.

**Comment by fycus-tree** [comment]
[FAQ](http://csrankings.org/faq.html) says _A single faculty member gets 1/N credit for a paper, where N is the number of authors_

But in some ways, you're right. If it's a 2 author (student + professor) paper, the university gets 0.5 points of credit. If you add 2 more professors to the paper, the university gets 0.75 points of credit.

**Comment by tongzhou80** [comment]
Oh oh yes you are right. Thanks for the explanation! Going from 0.5 to 0.75 is nontrivial, a 50% increase already.

**Comment by marcniethammer** [comment]
This seems to be a general issue as long as there are authors that are counted in the distribution for credit (i.e., in the N), but are not included in csrankings (i.e., students, postdocs, industry researchers, ...). It's also a good argument to not count students when coming up with the credit distribution (as proposed by many people before, though likely for other reasons). In this way, there would be no incentive to add more faculty and at the same time there would be no penalty for adding students to a paper. I imagine that Emery likely disagrees with this viewpoint, but isn't the PhD all about providing educational opportunities for students? It seems like we should encourage and not discourage student authorships.

**Comment by fycus-tree** [comment]
@vesuppi but it required having only 1-non-university-professor author, and the 50% increase in score required a 100% increase in authors (from 2 to 4) or 300% increase in university-professor authors (from 1 to 3). This clearly has diminishing returns. First "extra" prof is 25% increase, second is 12.5%, third is 6%, fourth is 4%, etc. This is basically the "worst case" and it's not really that bad.

**Comment by marcniethammer** [comment]
@fycus-tree , well, there is definitely a diminishing return. But there are probably a lot of papers out there with quite a few student authors. In this case this seems to be an actual issue. Just for arguments sake, let's start with a paper with 3 student authors (which is probably not too uncommon in some fields). Here is how this breaks down when adding more faculty:

one faculty: 0.25 credit overall
two faculty: 2 * 0.2 = 0.4 credit overall
three faculty: 3 * 0.1666 = 0.5 credit overall

Yes, of course it has to diminish, but it is a bit of a weird incentive structure.

**Comment by kno10** [comment]
Its a completely weird incentive anyway.
Because at the same time, all the universities and funding agencies ask for more collaboration, yet this ranking "punishes" this. In particular, if the co-authors are not CS faculty.

So it would _also_ make sense to ignore authors not in the ranking database when distributing scores; or apply the 1/N rule only for authors with the same affiliation (so a paper with three authors from the same university is not counted three times, but a collaboration of three universities counts for each of them).

**Comment by fycus-tree** [comment]
@kno10 see #265 and #562

**Comment by kno10** [comment]
The frequency with which this topic comes up here shows that the current approach is pretty problematic.
