### ISSUE TITLE
Data copy

### ISSUE THREAD

**Issue by zkt12** [emeryberger/CSrankings#1368]
I want to build a website to show the csrankings of Chinese Universities. Can I use generated-author-info.csv & country-info.csv in my site? What do I need to add in my site for this?

**Comment by emeryberger** [comment]
You may not do this. This would violate the terms of the license under which CSrankings code and data are released.

https://creativecommons.org/licenses/by-nc-nd/4.0/

**Comment by emeryberger** [comment]
However, you are of course welcome to submit updates for CSrankings.
