### ISSUE TITLE
Add Compilers as one of the Systems Areas

### ISSUE THREAD

**Issue by rcorcs** [emeryberger/CSrankings#1376]
It would be nice if there was a "Compilers" area under Systems.
This would include conferences such as:
CGO: International Symposium on Code Generation and Optimization
PACT: International Conference on Parallel Architectures and Compilation Techniques
CC: International Conference on Compiler Construction
LCTES: Conference on Languages, Compilers and Tools for Embedded Systems
LCPC: International Workshop on Languages and Compilers for Parallel Computing

It could be called Compilers, Compiler Construction, Compilation Techniques, etc.

Thanks,
Rodrigo Rocha

**Comment by emeryberger** [comment]
This is from the FAQ.


> How were research areas determined?
> --
> Nearly all categories are based on research-focused ACM SIGs. Areas not represented by ACM SIGs are intended to span most established research-centric areas of computer science.
> 

Compilers are covered by SIGPLAN. Finer granularity than ACM SIGs is not going to happen.
