### ISSUE TITLE
University of Toronto (robotics) faculty list update

### ISSUE THREAD

**Issue by animesh-garg** [emeryberger/CSrankings#1409]
Tim Barfoot, University of Toronto, http://asrl.utias.utoronto.ca/~tdb/, N_vPIhoAAAAJ
Florian Shkurti, University of Toronto,http://www.cs.toronto.edu/~florian/, BDmtLHsAAAAJ
Animesh Garg, University of Toronto, http://www.cs.toronto.edu/~garg/, zp8V7ZMAAAAJ
Jessica Burgner-Kahrs, University of Toronto, https://www.cs.toronto.edu/~jbk/, JtHZL24AAAAJ

check: http://web.cs.toronto.edu/people/faculty.htm (for details)

**Comment by fycus-tree** [comment]
Consider making a pull request

**Comment by animesh-garg** [comment]
I have made one here. 
https://github.com/emeryberger/CSrankings/pull/1523

Let me know if additional info is needed

**Comment by emeryberger** [comment]
Added via PR
