### ISSUE TITLE
Missing papers

### ISSUE THREAD

**Issue by nguyenthanhvuh** [emeryberger/CSrankings#141]
Recent commits (not sure which one specifically, but within the last couple of days) seem to cause some inconsistencies 

E.g.,  http://dblp.uni-trier.de/pers/hd/s/Srisa=an:Witawas  has 1 (full) ICSE, but his name no longer appears in the UNL Software Engineer ranking.  
Also,  http://dblp.uni-trier.de/pers/hd/n/Nguyen:ThanhVu has 3 (full) ICSE papers, but only 2 were counted.  

These data were all correct previously.

**Comment by emeryberger** [comment]
Appears to be fixed with https://github.com/emeryberger/CSrankings/commit/3e547599ffab006c57fbeafcba1f7d77c22cc510. Problem was possibly a corrupt DBLP download; this one had same md5sum as posted.
