### ISSUE TITLE
lifting of moratorium

### ISSUE THREAD

**Issue by marcniethammer** [emeryberger/CSrankings#1422]
Hi Emery,

what are the current thoughts on lifting the 2018 moratorium (see your response in #856) on adding new areas / conferences?

There seem to be many open requests and, of course, there is also the quantitative analysis by @fycus-tree  (#859).

Thanks for any updates on this issue.

For convenience, here is a reasonably complete list of open issues in this regard to allow for a quick overview: #1312, #1256, #839, #856, #762, #367, #238, #427, #423, #366, #361, #263, #259, #240, #162, #147, #99, #38

**Comment by jefhai** [comment]
I also agree- we should at least establish a poll to add a few in...

@emeryberger is it a lot of work to maintain this site for you?

**Comment by marcniethammer** [comment]
@emeryberger : Any comments on this?
