### ISSUE TITLE
Include CSCW

### ISSUE THREAD

**Issue by mdekstrand** [emeryberger/CSrankings#147]
I note that CSCW is not included in the HCI rankings.

If the premier conference on collaborative and social computing is excluded, then HCI researchers focusing on that area can only help their university's rankings with that work that they decide to send to CHI instead of the more focused CSCW conference. This seems like a perverse incentive.

I would recommend either re-evaluating the 3-conference rule or splitting HCI into subfields. It is a sufficiently broad topic that capturing it in 3 conferences does not seem realistic.

**Comment by pgbovine** [comment]
fwiw, CSCW is starting to get more "systemsy". Obviously everyone has their own picks in the 3-conference rule, but for myself and many folks on the CS-ey side of HCI, our 3-conference pick is usually {CHI, CSCW, UIST}

**Comment by aaroniidx** [comment]
I agree. CSCW is definitely a premier venue for HCI researchers to publish. I think ICWSM should also be added, but that's just my opinion.

**Comment by ChristinaLee515** [comment]
I 100% agreed! CHI is definitely the top conference. But it's debatable wether CSCW, UIST, or UbiComp is more reputable. This doesn't seem fair.

**Comment by emeryberger** [comment]
I would like to understand what part is "unfair". Unfair would be if some area were treated differently than others. Right now, all areas are subject to the three conference limit. This may not be ideal (and it may change), but it's officially fair because all areas are treated identically.

**Comment by emeryberger** [comment]
In any event, this is the kind of thing that I think would be best addressed by a community-wide survey.

**Comment by aaroniidx** [comment]
"Unfair" is a bit of an overstatement. But according to [Google Scholars](https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_humancomputerinteraction), CHI, CSCW, and Ubicomp are the top three conferences right now.

**Comment by emeryberger** [comment]
So to be clear, the candidates for top 3 are CHI, CSCW, Ubicomp, UIST, and possibly ICWSM. Correct?

**Comment by aaroniidx** [comment]
Correct. (And I don't have a super strong opinion about ICWSM because it can be in IR as well.)

**Comment by mdekstrand** [comment]
Unfair is not an overstatement.

Facially-equal treatment does not imply fairness. The (entirely subjective) definition of different research areas significantly impacts the fairness of the results.

Right now, the scholars who publish primarily on the collaborative and social side of HCI (e.g. CSCW & ICWSM) do not contribute to their departments' standing in CSRankings. That is grounds for claiming that the system is not fair.

Systems is broken down into many sub-areas. So is artificial intelligence. Why is HCI not broken down into sub-areas? It is entirely reasonable to consider UI technology (UIST, UbiComp, some of CHI) to be distinct from collaborative and social computing (CSCW and some in CHI); these two areas are just as distinct as as "Software engineering" and "Measurement and performance analysis".

I see 2 solutions: break HCI into sub-areas, or relax the 3-conference rule. There is not a set of 3 conferences that will be regarded across HCI as capturing the top quality of the breadth of the field. The CHI, CSCW, UIST trio is the closest I can think of, and it is probably still missing important subfields.

**Comment by emeryberger** [comment]
This is in the FAQ. (Note that "Systems", etc. are _not_ areas.)

**How were research areas determined?**
--
The areas are intended to span most established research-centric areas of computer science. Nearly all categories are based on research-focused ACM SIGs.

**Comment by ChristinaLee515** [comment]
Alright, apologies for my statement if in anyway appear rude. I just wanted to point out that CSCW is very well respected. And according to Google Scholars, CHI, CSCW, and Ubicomp are the top three conferences on there. But if you had already consulted with the research community and decided CSCW shouldn't be up there, I will respect it.

**Comment by mdekstrand** [comment]
I do not believe that punting the CS categorization to the ACM SIG structure is a workable strategy. This also comes into play in #562 as mentioned by @fycus-tree, although I don't think the multi-metric approach in #562 is the right solution:

> The problem is this normalization makes it's own value judgement-- that all ACM SIGs are equal. Which assumes that ACM has done a good job of managing, balancing and selecting SIGs.

SIGCHI is by far one of the largest SIGs in the ACM by conference count (more than 20 conferences). It encompasses a wide array of methods, applications, and problems, and includes conferences that have a lot of other work going on as well (e.g. RecSys has more data mining & machine learning than HCI many years, but is entirely sponsored by SIGCHI). Restructuring ACM SIGs is a lot more work (for questionable benefit) than restructuring CSRankings' view of the field. ACM SIG structures don't really shift individual researcher or institutional incentives.

**There is no neutral decision.** Every inclusion and ranking decision in CSRankings is a value judgement, and as @fycus-tree observes, assuming that ACM SIGs are well-balanced and reflect a reasonable division of CS for the purposes of generating rankings is one such judgement. My central contention here is that that judgement is incorrect, and _any_ attempt to summarize HCI as a single area with 3 conferences will limit the ability for productive researchers to contribute to their institutions' rankings.

**Comment by brendano** [comment]
@mdekstrand: "I do not believe that punting the CS categorization to the ACM SIG structure is a workable strategy."

I wanted to note that while some parts of the csrankings area system correspond to ACM SIGs (especially the systems ones, I think), plenty of areas don't.  For example, csrankings has areas for NLP, ML, and Vision (correctly, in my opinion) but there's no ACM SIG for any of them, as far as I know, and very few ACM-related conferences in those areas.

**Comment by printfoo** [comment]
Out of 3 [inclusion criteria](http://csrankings.org/faq.html), CSCW has higher [h5-index](https://scholar.google.com/citations?view_op=top_venues&vq=eng_humancomputerinteraction) and [number of submissions](https://sigchi.org/conferences/conference-history/CSCW) than Ubicomp and UIST, so it's reasonable to assume that excluding CSCW in the first place is due to its acceptance rate. 

However, It's noteworthy that before 2012, CSCW had similar acceptance rate compared to CHI/Ubicomp/UIST. Since 2012, CSCW adopted a journal-ish "revise and resubmit" process which suddenly increased its acceptance rate. According to this [survey](https://cscw.acm.org/2014/cscw-survey.pdf), >40% of people think "that (at least some of) their accepted papers would have been rejected under the earlier (one-round) system (Q5)", and a majority of people "believe CSCW's higher acceptance rates are justified by the increased quality of papers that make it through the new, two-round reviewing process (Q17)".

I think it's debatable whether the acceptance rate of such "revise and resubmit" process is directly comparable to traditional one-round conference paper selection process.

**Comment by mdekstrand** [comment]
Thanks for the additional CSCW details, @printfoo.

To further complicate matters, this year CSCW has moved to the PACM model, so its papers are journal papers in _Proceedings of the ACM_.

**Comment by printfoo** [comment]
@mdekstrand Thank you, that's true. But I guess the PACM publication model doesn't affect the inclusion decision for csrankings. As far as I know, there are several conferences included already moved to the PACM model, including Ubicomp, SIGMETRICS, POPL, OOPSLA, ICFP. (I could be wrong about this)

**Comment by dakuo** [comment]
CSCW should be included but not included... this has caused series problems as some funding agencies are using CSRanking to evaluate institution and distribute funding to the strong ones. It does not makes sense that we include the Rank 1, 3, 4 conferences in HCI field but left the Rank 2 conference. Thanks! @emeryberger 
![WechatIMG71](https://user-images.githubusercontent.com/3362714/61555980-a54cc480-aa2e-11e9-98db-d8b544f2bfde.jpeg)

**Comment by leonidk** [comment]
I wrote [a paper generating conference value by grant funding & faculty hiring](https://arxiv.org/abs/1904.12573), and in HCI-- it saw CHI as 1st, CSCW & UIST tied at 2nd. It's even in the header image of the paper.

**Comment by mdekstrand** [comment]
@dakuo can you point to any public docs about CSRankings being used in funding decisions? I would very much like to learn more about where and how frequently that is happening.

**Comment by printfoo** [comment]
FWIW, Google just released 2019 scholar metrics yesterday, current h-index under HCI is CHI 87, CSCW 60, Ubicomp 57, UIST 46.

**Comment by leonidk** [comment]
@printfoo The issue with h-index is that it's highly correlated with size. Larger conferences have an easier time getting a large h-index (it's number of papers, not percentage of papers). CSCW accepted 142 in 2016, UIST accepted 79. Ubicomp accepted 101. 

Plus citations are a pretty sloppy metric, useful only to an order of magnitude (different communities have different citation rates), see Kurtz, Michael J., and Edwin A. Henneken. "Measuring metrics‐a 40‐year longitudinal cross‐validation of citations, downloads, and peer review in astrophysics." Journal of the Association for Information Science and Technology 68, no. 3 (2017): 695-708..

**Comment by printfoo** [comment]
@leonidk Yes I agree. Obviously any measure measures what it measures and it's implausible to find a single measure that makes everyone happy... I only mention H-index because it's one of 3 measures that currently being considered by CSRankings (along with submission # and acceptance %).

**Comment by eglassman** [comment]
> fwiw, CSCW is starting to get more "systemsy". Obviously everyone has their own picks in the 3-conference rule, but for myself and many folks on the CS-ey side of HCI, our 3-conference pick is usually {CHI, CSCW, UIST}

Ours too. And it was the same when I was working for Bjoern @ UC Berkeley and Rob Miller @ MIT.

**Comment by williamstome** [comment]
Posting here to agree -- it's crazy that CSCW is not included.

**Comment by sliminality** [comment]
Agree with this. As a systems HCI researcher (now closer to PL), CSCW is definitely a top-3 venue along with CHI and UIST. More importantly, its omission excludes a large component of the HCI research community doing important work on social collaboration, which is already maligned as "not real CS" despite copious evidence to the contrary and often-significant technical investment.

**Comment by JimWallace** [comment]
If you're going to pick 3, CHI, CSCW, UbiComp would make the most sense:  

https://scholar.google.ca/citations?view_op=top_venues&hl=en&vq=eng_humancomputerinteraction

But picking 3 seems like a horrible idea anyway, why not index them all?

**Comment by wooogler** [comment]
I am curious why this issue was closed.
