### ISSUE TITLE
Addition of Asia

### ISSUE THREAD

**Issue by mkramanathan** [emeryberger/CSrankings#153]
Hi, 

There are quite a few universities in Asia (even in the current CS rankings list). List below:
1) Technion - Israel Institute of Technology 
2) Tel Aviv University 
3) Hebrew University of Jerusalem
4) IISc Bangalore

Can you please create a separate entry for asia and list these universities under it? 

Thanks,
Murali Krishna

**Comment by emeryberger** [comment]
https://www.quora.com/Why-is-Israel-considered-to-be-a-European-country-while-it-is-geographically-situated-in-Africa-Asia

**Comment by emeryberger** [comment]
It's a tricky question. I don't want to engage in politics here. My impression is that Israelis do not consider themselves to be in Asia, but I am verifying this.

In any event, the real value add would be to have the IITs included in CSrankings. I'd be more than happy to get PRs for their faculty.

**Comment by mkramanathan** [comment]
Oh, I didn't realize that there was uncertainty on this issue regarding Israel.  

In any case, can asia still be added given that IISc Bangalore is in asia. I have already notified a few folks at IITs. 

Also, when will the changes made in the repo be reflected on the website?

**Comment by emeryberger** [comment]
Changes should be there now.
