### ISSUE TITLE
Not listed in csrankings.org but affil's are correct in CSV

### ISSUE THREAD

**Issue by bates151** [emeryberger/CSrankings#1553]
Hi there,

I don't appear to be showing up as faculty at my institution in spite of the fact that my affiliation is correct on DBLP and inside of csrankings.csv.  Please advise!

There are two entries for me in csrankings.csv:
`Adam Bates,Univ. of Illinois at Urbana-Champaign,http://adambates.org,1dVglBkAAAAJ`
`Adam M. Bates 0001,Univ. of Illinois at Urbana-Champaign,http://adambates.org,1dVglBkAAAAJ`

I'm not sure if this is related. As you can see, the affiliation perfectly matches other UIUC faculty that are currently appearing on the rankings:

`Kirill Levchenko,Univ. of Illinois at Urbana-Champaign,http://klevchen.ece.illinois.edu,bVGlTd4AAAAJ`
`Nikita Borisov,Univ. of Illinois at Urbana-Champaign,https://www.ece.illinois.edu/directory
/profile/nikita,MnsxqAcAAAAJ`

Please advise!

Best,
Adam

**Comment by emeryberger** [comment]
Hi Adam - The issue was a missing '0001' suffix after your name (not the one with the initial). Fixed with https://github.com/emeryberger/CSrankings/commit/303dc33b67aa6df42b5c3d34647de400fd0f08e3.

**Comment by bates151** [comment]
Thanks Emery!!
