### ISSUE TITLE
Update Hung-Wei Tseng

### ISSUE THREAD

**Issue by msridhar** [emeryberger/CSrankings#1561]
**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition
- [ ] Deletion
- [X] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name as listed in DBLP**

Hung-Wei Tseng

**Update/add an affiliation**

Moved to University of California, Riverside from North Carolina State University.

**Update/add a home page**

https://intra.engr.ucr.edu/~htseng/

**Update/add a Google Scholar page.**

https://scholar.google.com/citations?user=j-Lk39cAAAAJ&hl=en

**Comment by emeryberger** [comment]
Updated.
