### ISSUE TITLE
google search links not working

### ISSUE THREAD

**Issue by kudhru** [emeryberger/CSrankings#158]
Hi

the google search links of professors, (for example, **_

> https://www.google.co.in/search?q=Eileen%2520Kraemer%2520Clemson%2520University&btnI=&gws_rd=cr&ei=xrkxWLbDHcHWvASFr73gCw

_** )

do not work. there is an extra "%25" being embedded between spaces.

**Comment by emeryberger** [comment]
They are generated automatically. I welcome pull requests but I will fix that one manually.

**Comment by emeryberger** [comment]
Notice that this is due to Google redirects. The automatically generated link is fine.
