### ISSUE TITLE
Limin Wang (ADD)

### ISSUE THREAD

**Issue by marshtompsxd** [emeryberger/CSrankings#1584]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Limin Wang

**Enter any aliases (multiple entries) given in DBLP.**
None

**Update/add an affiliation**
Department of Computer Science and Technology, Nanjing University
http://wanglimin.github.io/

**Update/add a home page**
http://wanglimin.github.io/

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?hl=zh-CN&user=HEuN8PcAAAAJ

**Comment by emeryberger** [comment]
Added.
