### ISSUE TITLE
Viktor Leis (ADD)

### ISSUE THREAD

**Issue by viktorleis** [emeryberger/CSrankings#1590]
**Please indicate whether this is an addition, deletion, or modification**
- [X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Viktor Leis

**Enter any aliases (multiple entries) given in DBLP.**

**Update/add an affiliation**
Friedrich Schiller University Jena

**Update/add a home page**
https://dbis1.github.io/

**Update/add a Google Scholar page.**
https://scholar.google.de/citations?user=qFOwPNQAAAAJ&hl=en

**Comment by emeryberger** [comment]
Added.
