### ISSUE TITLE
Amin Sakzad (ADD)

### ISSUE THREAD

**Issue by luckyluck63** [emeryberger/CSrankings#1601]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
https://dblp.org/pers/hd/s/Sakzad:Amin

**Update/add an affiliation**
Monash University
https://research.monash.edu/en/persons/amin-sakzad

**Update/add a home page**
https://research.monash.edu/en/persons/amin-sakzad

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=b8k6e8IAAAAJ&hl=en

**Comment by emeryberger** [comment]
Added.
