### ISSUE TITLE
Tam V. Nguyen (ADD)

### ISSUE THREAD

**Issue by vantam** [emeryberger/CSrankings#1610]
**Please indicate whether this is an addition, deletion, or modification**
- [ X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [ X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Tam V. Nguyen
https://dblp.uni-trier.de/pers/hd/n/Nguyen:Tam_V=

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
University of Dayton

**Update/add a home page**
https://sites.google.com/site/vantam/

**Update/add a Google Scholar page.**
https://scholar.google.com.sg/citations?user=qIaGn7YAAAAJ

**Comment by emeryberger** [comment]
AFAICT this institution does not grant PhDs in computer science and so it is not eligible for inclusion in CSrankings.

**Comment by vantam** [comment]
University of Dayton offers PhD in Computer Science
https://udayton.edu/artssciences/academics/computerscience/academic/computer-science-phd.php
I am supervising one PhD student. Please kindly check my request. Thanks.
