### ISSUE TITLE
Ajmal Mian (ADD)

### ISSUE THREAD

**Issue by iSarmad** [emeryberger/CSrankings#1615]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._

**Ajmal Mian**

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

NA

**Add an affiliation**
https://research-repository.uwa.edu.au/en/persons/ajmal-mian
**University of Western Australia, Crawley, WA, Australia**

**Add a home page**
http://staffhome.ecm.uwa.edu.au/~00053650/

**Add a Google Scholar page.**
https://scholar.google.com/citations?user=X589yaIAAAAJ&hl=en

**Comment by emeryberger** [comment]
Added.
