### ISSUE TITLE
Adding Top 3 journals as well

### ISSUE THREAD

**Issue by kudhru** [emeryberger/CSrankings#163]
Hi

I was just wondering why we have only included the Top 3 conferences and not included the top journals in respective fields. Could you please explain your thinking?

Thanks and regards
Dhruv

**Comment by emeryberger** [comment]
Conferences are the primary publication venue for most areas of computer science. Journals don't generally publish acceptance rates, and many top journals primarily comprise polished versions of articles that have previously appeared at conferences.
