### ISSUE TITLE
Lale Özkahya, plus (ADD)

### ISSUE THREAD

**Issue by ozkahya** [emeryberger/CSrankings#1634]
**Please indicate whether this is an addition, deletion, or modification**
- [x ] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Lale Özkahya

**Enter any aliases (multiple entries) given in DBLP.**
Lale Özkahya

**Update/add an affiliation**
Hacettepe University
Department of Computer Engineering
https://www.cs.hacettepe.edu.tr/

**Update/add a home page**
Enter the full home page below. Please test it to make sure it is correct.
https://web.cs.hacettepe.edu.tr/~ozkahya/

**Update/add a Google Scholar page.**
https://scholar.google.com.tr/citations?hl=en&user=1GKiDzwAAAAJ

**Comment by emeryberger** [comment]
Added.

**Comment by ozkahya** [comment]
Thank you very much. Right now, my name does not appear in the faculty list of the CS department of Hacettepe University in the csrankings webpage. When do you think it will appear? Thanks again.
