### ISSUE TITLE
Mohammad Abdullah Al Faruque, plus (ADD)

### ISSUE THREAD

**Issue by alfaruqu** [emeryberger/CSrankings#1638]
**Please indicate whether this is an addition, deletion, or modification**
- [X] Addition

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Mohammad Abdullah Al Faruque
https://dblp.uni-trier.de/pers/hd/f/Faruque:Mohammad_Abdullah_Al

**Enter any aliases (multiple entries) given in DBLP.**
Mohammad Al Faruque
https://dblp.uni-trier.de/pers/hd/f/Faruque:Mohammad_Al

**Update/add an affiliation**
University of California, Irvine (UCI)
Department of Electrical Engineering & Computer Science (EECS)
Department of Computer Science (CS) 
Web: http://aicps.eng.uci.edu/ 

**Update/add a home page**
http://aicps.eng.uci.edu/ 

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=ejWHC-cAAAAJ&hl=en

**Comment by emeryberger** [comment]
Added.
