### ISSUE TITLE
missing papers of Lijun Zhang 0005 and Yang Yu 0001(UPDATE)

### ISSUE THREAD

**Issue by marshtompsxd** [emeryberger/CSrankings#1665]
**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition
- [ ] Deletion
- [x] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

There are several missing ML and AI papers of Lijun Zhang 0005 and Yang Yu 0001 since the dblp faculty entries of Lijun Zhang and Yang Yu were ambiguous previously. I have fixed part of this by merging several papers to Yang Yu 0001 and Lijun Zhang 0005 (They are the true authors of the lost papers). Could you please use the latest released dblp data to add these papers? Thank you very much!

**Comment by emeryberger** [comment]
I update DBLP at least monthly, but not more frequently. The updates will eventually show up if they are not there already. Thanks for helping disambiguate the DB!
