### ISSUE TITLE
Option to include *all* listed conferences

### ISSUE THREAD

**Issue by nguyenthanhvuh** [emeryberger/CSrankings#1667]
Currently there's an option to turn on all areas, but that does not include all listed conferences (e.g., in PL, this includes PLDI and POPL but excludes OOPSLA and ICFP).  Is it possible to have an option to check all of them?

**Comment by emeryberger** [comment]
You can of course manually check all of them. They are deliberately left blank because they are "second tier" conferences (in a separate equivalence class from the others).
