### ISSUE TITLE
double escaping on google search for person name

### ISSUE THREAD

**Issue by brendano** [emeryberger/CSrankings#168]
after clicking on a person's name (for people where it tries to launch a google search)

i think this is a double escaping issue -- the `%20` things appear in the query box ui

<img width="1117" alt="screen shot 2016-12-07 at 11 29 53 am" src="https://cloud.githubusercontent.com/assets/1677/20976430/87ead408-bc70-11e6-8669-ba2dcdbe46ca.png">

**Comment by emeryberger** [comment]
​Sigh. Thanks, Google. Will look into it.

**Comment by emeryberger** [comment]
OK, I fixed this by making the homepage-builder far more robust, and cleaned out all Google search entries in the process.
