### ISSUE TITLE
Auroop Ganguly, plus (ADD)

### ISSUE THREAD

**Issue by auroop-ganguly** [emeryberger/CSrankings#1684]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Auroop R. Ganguly

**Enter any aliases (multiple entries) given in DBLP.**
Auroop R. Ganguly
Auroop Ganguly
Auroop Ratan Ganguly

**Update/add an affiliation**
Northeastern University
https://en.wikipedia.org/wiki/Auroop_Ratan_Ganguly
https://www.civ.neu.edu/people/ganguly-auroop
risQ Inc
https://www.risq.io/

**Update/add a home page**
https://www.civ.neu.edu/people/ganguly-auroop

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=eNrAUJMAAAAJ

**Comment by emeryberger** [comment]
Added.
