### ISSUE TITLE
Nathan Sturtevant (UPDATE)

### ISSUE THREAD

**Issue by nathansttt** [emeryberger/CSrankings#1697]
**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition
- [ ] Deletion
- [x] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion criteria.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_Nathan R. Sturtevant_
https://dblp.org/pers/hd/s/Sturtevant:Nathan_R=

**Enter any aliases (multiple entries) given in DBLP.**
Nathan Sturtevant

**Update/add an affiliation**
Affiliation (University of Alberta) is currently correct - DBLP has outdated information.

[Although my name is in the database, I am not appearing under searches for the University of Alberta. I assume this is because my DBLP entry is not being properly pulled.]

**Comment by emeryberger** [comment]
Yep, the issue was a mismatch with DBLP. Updated with https://github.com/emeryberger/CSrankings/commit/b388ac1fa3d3082f52046f4f9ea75b5d4cd04197.
