### ISSUE TITLE
Alexis Hiniker ADD

### ISSUE THREAD

**Issue by alexishiniker** [emeryberger/CSrankings#1713]
**Please indicate whether this is an addition, deletion, or modification**
- [X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Alexis Hiniker

**Enter any aliases (multiple entries) given in DBLP.**

**Update/add an affiliation**
University of Washington

**Update/add a home page**
http://alexishiniker.com

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=tY-tZTkAAAAJ&hl=en&oi=ao

**Comment by emeryberger** [comment]
Not listed here: https://www.cs.washington.edu/people/faculty, no indication of cross-appointment.

**Comment by emeryberger** [comment]
If you have a cross-appointment with CSE, please point me to it and feel free to reopen.

**Comment by alexishiniker** [comment]
Hi, I have a courtesy appointment in CSE and am listed here: https://www.cs.washington.edu/people/faculty/adjunct. Thanks!

**Comment by emeryberger** [comment]
Perfect, thanks! Added.
