### ISSUE TITLE
Andrea Tagliasacchi DELETE

### ISSUE THREAD

**Issue by bmkapron** [emeryberger/CSrankings#1717]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Deletion

**Please check the box below to indicate that you have read the inclusion criteria.**

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._

Andrea Tagliasacchi

**Update/add an affiliation**
List the new affiliation, and the old affiliation (if already in CSRankings). Please point to a web page (preferably institutional/departmental, but personal is OK), a LinkedIn site, or similar. If a faculty member has moved to industry, retired, or for other reasons departed academia, please indicate this here.

New affiliation -- Google AI
Old affiliation -- University of Victoria

**Update/add a home page**
Enter the full home page below. Please test it to make sure it is correct.

https://ai.google/research/people/106392/

**Update/add a Google Scholar page.**
Please include a link to the faculty member's [Google Scholar](https://scholar.google.com) page. If none exists, please put "NOSCHOLARPAGE".

https://scholar.google.com/citations?user=1RmD-YsAAAAJ&hl=en

**Comment by emeryberger** [comment]
Deleted.
