### ISSUE TITLE
Antonis Argyros (ADD)

### ISSUE THREAD

**Issue by antonisargyros** [emeryberger/CSrankings#1719]
**Please indicate whether this is an addition, deletion, or modification**
- [X] Addition

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Antonis A. Argyros 
https://dblp.uni-trier.de/pers/hd/a/Argyros:Antonis_A=

**Enter any aliases (multiple entries) given in DBLP.**
-

**Update/add an affiliation**
Computer Science Department, University of Crete
https://www.csd.uoc.gr/CSD/index.jsp?lang=en

**Update/add a home page**
http://users.ics.forth.gr/~argyros

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?hl=en&user=9OieklkAAAAJ

**Comment by emeryberger** [comment]
Already added.
