### ISSUE TITLE
add more conferences + checkboxes for each

### ISSUE THREAD

**Issue by emeryberger** [emeryberger/CSrankings#172]
This would keep the current system of top conferences for each area, but would let people drill down further into subareas. I see this as being revealed by another clickable triangle below each area, though handling this elegantly in the UI is not obvious.

**Comment by emeryberger** [comment]
This has finally been implemented!

**Comment by fycus-tree** [comment]
@emeryberger 

1. Visualization doesn't have checkboxes
2.  Computer graphics doesn't have checkboxes
3. The checkboxes aren't aligned across subblocks. Would be good to right-align them. (e.g. look at AI and CV)

**Comment by emeryberger** [comment]
1. and 2. Checkboxes require a bit more work for visualization and computer graphics because the different conference proceedings appear in the same journals.
3. Fixed. Thanks!

**Comment by emeryberger** [comment]
Computer graphics checkboxes now implemented.
