### ISSUE TITLE
Alexandros Iosifidis ADD

### ISSUE THREAD

**Issue by pkarras** [emeryberger/CSrankings#1722]
**Please indicate whether this is an addition, deletion, or modification**
- [ X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [ X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
List the new affiliation, and the old affiliation (if already in CSRankings). Please point to a web page (preferably institutional/departmental, but personal is OK), a LinkedIn site, or similar. If a faculty member has moved to industry, retired, or for other reasons departed academia, please indicate this here.
Aarhus University

**Update/add a home page**
Enter the full home page below. Please test it to make sure it is correct.
https://sites.google.com/view/iosifidis

**Update/add a Google Scholar page.**
Please include a link to the faculty member's [Google Scholar](https://scholar.google.com) page. If none exists, please put "NOSCHOLARPAGE".
https://scholar.google.com/citations?user=KjsL0KEAAAAJ

**Comment by emeryberger** [comment]
Not in CS. Please read over inclusion criteria.

**Comment by pkarras** [comment]
I did read the inclusion criteria. Alexandros can solely advise PhD students in CS through the DIGIT center: http://digit.au.dk/

**Comment by emeryberger** [comment]
Can you provide a more precise link? I see one PhD project where this faculty member is co-advising, which does not provide much evidence that he can solely advise a PhD student for a CS PhD.

**Comment by pkarras** [comment]
He can solely advise a PhD student for a CS PhD in principle, since the PhD program is managed at the school level rather than the department level. See here:

https://international.au.dk/about/organisation/index/6/64/64-01/

8.-(1) For each PhD student, the institution designates a principal supervisor who is responsible for the overall PhD degree programme. The principal supervisor must be a recognised researcher within the relevant field, be employed by the institution and affiliated with the graduate school.
