### ISSUE TITLE
Robert Patro, UPDATE

### ISSUE THREAD

**Issue by rob-p** [emeryberger/CSrankings#1727]
**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition
- [ ] Deletion
- [X] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, 
[Robert Patro](https://dblp.uni-trier.de/pers/hd/p/Patro:Robert)

**Update/add an affiliation**
New affiliation: University of Maryland - College Park 
Old affiliation: Stony Brook University
[webpage](www.robpatro.net)

**Comment by emeryberger** [comment]
Already updated.
