### ISSUE TITLE
Vojtěch Řehák ADD

### ISSUE THREAD

**Issue by VojtechRehak** [emeryberger/CSrankings#1744]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**

Vojtech Rehák
https://dblp.org/pers/hd/r/Reh=aacute=k:Vojtech

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
https://www.muni.cz/en/people/3721-vojtech-rehak
https://is.muni.cz/osoba/3721?lang=en

**Update/add a home page**
https://www.fi.muni.cz/~xrehak/

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=ecYKcckAAAAJ&hl=cs

**Comment by emeryberger** [comment]
This institution is not yet in the database; please add it (with all CS faculty) via a github pull request.

**Comment by VojtechRehak** [comment]
The institution is already there. It is Masaryk University. My colleague is, e.g., https://dblp.org/pers/hd/k/Kucera_0001:Anton=iacute=n

Many thanks.

**Comment by VojtechRehak** [comment]
As this is closed, I reopened it as a new issue, see #1983.

**Comment by emeryberger** [comment]
Added.
