### ISSUE TITLE
Chao Chen (ADD)

### ISSUE THREAD

**Issue by chaochen** [emeryberger/CSrankings#1748]
**Please indicate whether this is an addition, deletion, or modification**
- [X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**

Chao Chen 0012

**Update/add an affiliation**

Stony Brook University
https://www.cs.stonybrook.edu/people/faculty/ChaoChen

**Update/add a home page**

http://eniac.cs.qc.cuny.edu/cchen/

**Update/add a Google Scholar page.**

https://scholar.google.com/citations?user=J-iIIFAAAAAJ

**Comment by emeryberger** [comment]
Updated Google Scholar link.
