### ISSUE TITLE
Jaesik Park (ADD)

### ISSUE THREAD

**Issue by syncle** [emeryberger/CSrankings#1751]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Jaesik Park

**Update/add an affiliation**
Dept. of Computer Science and Engineering, POSTECH
https://cse.postech.ac.kr

**Update/add a home page**
Enter the full home page below. Please test it to make sure it is correct.
http://jaesik.info

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=_3q6KBIAAAAJ&hl=en&oi=ao

**Comment by emeryberger** [comment]
added.
