### ISSUE TITLE
Add collaboration graphs

### ISSUE THREAD

**Issue by emeryberger** [emeryberger/CSrankings#176]
With the existing data, it should now be straightforward to generate collaboration graphs for each institution. Cross-institution would also be doable - in fact, a whole map of collaboration networks across CS would in theory be easy to do. (H/T @dbarowy).

(Here's one from a long time ago as an example - https://people.cs.umass.edu/~emery/misc/collaboration/).

**Comment by brunyuriy** [comment]
Collaboration graphs should probably not be limited to papers in top three conferences in each area and should also include journals, other conferences, workshops, etc.

**Comment by emeryberger** [comment]
Thanks for the suggestion; I think there is value in both approaches.

**Comment by emeryberger** [comment]
Closed (now up at http://csrankings.org/collab).
