### ISSUE TITLE
Marcos Zampieri (ADD)

### ISSUE THREAD

**Issue by marcoszampieri** [emeryberger/CSrankings#1767]
**Please indicate whether this is an addition, deletion, or modification**
- [X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Marcos Zampieri
Link: https://dblp.org/pers/hd/z/Zampieri:Marcos

**Enter any aliases (multiple entries) given in DBLP.**
Marcos Zampieri

**Update/add an affiliation**
Rochester Institute of Technology

**Update/add a home page**
http://www.marcoszampieri.com

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=vAx7VsoAAAAJ&hl=en

**Comment by emeryberger** [comment]
Added.
