### ISSUE TITLE
Abhinav Bhatele (ADD)

### ISSUE THREAD

**Issue by bhatele** [emeryberger/CSrankings#1769]
**Please indicate whether this is an addition, deletion, or modification**
- [X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_Abhinav Bhatele_

**Enter any aliases (multiple entries) given in DBLP.**

**Update/add an affiliation**
University of Maryland
https://www.cs.umd.edu/people/bhatele

**Update/add a home page**
http://www.cs.umd.edu/~bhatele

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=3x65qtwAAAAJ

**Comment by emeryberger** [comment]
Added.
