### ISSUE TITLE
Yang Hu (ADD)

### ISSUE THREAD

**Issue by hy6356** [emeryberger/CSrankings#1778]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._
Yang Hu 0001

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
List the new affiliation, and the old affiliation (if already in CSRankings). Please point to a web page (preferably institutional/departmental, but personal is OK), a LinkedIn site, or similar. If a faculty member has moved to industry, retired, or for other reasons departed academia, please indicate this here.
University of Texas at Dallas, Computer Engineering
https://ece.utdallas.edu/ece/staff/yang-hu/

**Update/add a home page**
Enter the full home page below. Please test it to make sure it is correct.
https://www.huyang-ece.info/

**Update/add a Google Scholar page.**
Please include a link to the faculty member's [Google Scholar](https://scholar.google.com) page. If none exists, please put "NOSCHOLARPAGE".
https://scholar.google.com/citations?user=2W3uYmQAAAAJ&hl=en

**Comment by emeryberger** [comment]
Hi - not clear you meet the inclusion criteria as you do not appear here and your web page does not indicate a cross-appointment with CS (https://cs.utdallas.edu/people/faculty/).

> 
> **What are the criteria for including faculty?**
> --
> The criteria for inclusion are that anyone who is a full-time, tenure-track faculty member on a given campus who can solely advise PhD students in Computer Science can be included in the database. This approach thus extends the reach of the database to a number of faculty from other departments who have adjunct appointments with a CS department or similar that let them advise CS PhD students. Note that full-time means an at least 75% appointment for the entire academic year.
> 
> 
>

**Comment by hy6356** [comment]
> Hi - not clear you meet the inclusion criteria as you do not appear here and your web page does not indicate a cross-appointment with CS (https://cs.utdallas.edu/people/faculty/).
> 
> > ## **What are the criteria for including faculty?**
> > The criteria for inclusion are that anyone who is a full-time, tenure-track faculty member on a given campus who can solely advise PhD students in Computer Science can be included in the database. This approach thus extends the reach of the database to a number of faculty from other departments who have adjunct appointments with a CS department or similar that let them advise CS PhD students. Note that full-time means an at least 75% appointment for the entire academic year.

Hi Dr. Berger,
The CS department of UTD has granted me a CS affiliation in their department, which indicates that I can solely supervise PhD of CS department right now. They should update their website soon. Would you please kindly add me to the faculty list? Thanks!
Best,
Yang
https://www.huyang-ece.info
