### ISSUE TITLE
James R. Wallace (ADD), hci.uwaterloo.ca

### ISSUE THREAD

**Issue by JimWallace** [emeryberger/CSrankings#1829]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
List the new affiliation, and the old affiliation (if already in CSRankings). Please point to a web page (preferably institutional/departmental, but personal is OK), a LinkedIn site, or similar. If a faculty member has moved to industry, retired, or for other reasons departed academia, please indicate this here.

**Update/add a home page**
Enter the full home page below. Please test it to make sure it is correct.

**Update/add a Google Scholar page.**
Please include a link to the faculty member's [Google Scholar](https://scholar.google.com) page. If none exists, please put "NOSCHOLARPAGE".

**Comment by JimWallace** [comment]
Thank you

**Comment by emeryberger** [comment]
Not listed here: https://cs.uwaterloo.ca/about/people/group/49

**Comment by JimWallace** [comment]
Doesn’t need to be...

- Jim Wallace, PhD
School of Public Health and Health Systems
University of Waterloo

**Comment by emeryberger** [comment]
Can you confirm via some other means that you can solely advise a PhD student in Computer Science at Waterloo?

**Comment by JimWallace** [comment]
I can mail you a business card? 

- Jim Wallace, PhD
School of Public Health and Health Systems
University of Waterloo

**Comment by JimWallace** [comment]
Are you clear on requirements for PhD supervision at Waterloo? Being listed on that website isn’t necessary or sufficient. Have you been asking faculty for proof of ADDS status?

- Jim Wallace, PhD
School of Public Health and Health Systems
University of Waterloo

**Comment by emeryberger** [comment]
I don't know what "ADDS" means; I routinely ask for verification of adjunct status / courtesy appointments when people are not in CS departments or the local equivalent so I can verify they meet the inclusion criteria. From the FAQ:

> 
> **What are the criteria for including faculty?**
> --
> The criteria for inclusion are that anyone who is a full-time, tenure-track faculty member on a given campus who can solely advise PhD students in Computer Science can be included in the database. This approach thus extends the reach of the database to a number of faculty from other departments who have adjunct appointments with a CS department or similar that let them advise CS PhD students. Note that full-time means an at least 75% appointment for the entire academic year.
> 
>

**Comment by JimWallace** [comment]
At Waterloo all faculty are required to have ADDS status to sole supervise PhD students, you haven’t been asking for that from others?

- Jim Wallace, PhD
School of Public Health and Health Systems
University of Waterloo

**Comment by emeryberger** [comment]
"ADDS" appears to be Waterloo-specific jargon (or at least, it's what comes up when I google for it).

The question is not whether you can advise PhD students. That's necessary, but not sufficient. The question is whether you can advise PhD students who are going to receive a PhD *in Computer Science*. You are in an entirely different school, AFAICT. Your clarification is welcome.

**Comment by JimWallace** [comment]
Yes, exactly, and the website that you linked to provides no evidence of ability to advise PhD students, so I’m very confused what you’ve been accepting from others. Since ADDS status is the requirement at Waterloo, is that what you’ve been asking for?

It sounds like you’re trying to say that Waterloo works the way that your institution does, which I guess might work sometimes, but seems like a silly assumption in the general case. 

- Jim

**Comment by emeryberger** [comment]
Let's keep this simple. To my knowledge, you have yet to indicate that you are allowed to advise PhD students in Computer Science, something which I take for granted for tenure-track faculty within a CS department but not for faculty outside said departments, especially if there is no visible courtesy appointment. I'd be more than happy to add you if you can provide such an indication.

**Comment by JimWallace** [comment]
Thank you.

Yes, I can (and do) advise PhD students in Computer Science.

- Jim

**Comment by JimWallace** [comment]
Hi Emery,

Is this sufficient?

https://cs.uwaterloo.ca/about/people/group/53

- Jim Wallace, PhD
School of Public Health and Health Systems
University of Waterloo

**Comment by JimWallace** [comment]
Hi Emery,

I’ve provided a link to a website that lists me as cross-appointed faculty, is this sufficient?

- Jim Wallace, PhD
School of Public Health and Health Systems
University of Waterloo

**Comment by JimWallace** [comment]
Hi Emery,

Can you please confirm whether I’ve provided enough information at this point? 

- Jim

**Comment by emeryberger** [comment]
Confirmed.
