### ISSUE TITLE
Jonathan Katz UPDATE

### ISSUE THREAD

**Issue by yig** [emeryberger/CSrankings#1838]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._

Jonathan Katz

**Update/add an affiliation**
List the new affiliation, and the old affiliation (if already in CSRankings). Please point to a web page (preferably institutional/departmental, but personal is OK), a LinkedIn site, or similar. If a faculty member has moved to industry, retired, or for other reasons departed academia, please indicate this here.

New affiliation: George Mason University
Old affiliation: University of Maryland, College Park

Google Scholar page: https://scholar.google.com/citations?user=H4rKFc8AAAAJ&hl=en
GMU CS faculty directory: https://cs.gmu.edu/directory/by-category/faculty/
News announcement of the move: https://cs.gmu.edu/blog/jon-katz-joins-the-department-as-eminent-scholar-in-cybersecurity/

**Comment by emeryberger** [comment]
(Already) updated.
