### ISSUE TITLE
Add SIGGRAPH Asia conference

### ISSUE THREAD

**Issue by jnjortn** [emeryberger/CSrankings#184]
Please add the SIGGRAPH Asia (SA) conference to the Computer Graphics category. The SA conference utilizes the exact same reviewing process as SIGGRAPH and has the same quality level. Both conferences have their complete proceedings published as issues of ACM Transaction on Graphics.

**Comment by MingCLin** [comment]
I second.   Both are SIGGRAPH conferences, with SIGGRAPH Asia being equally selective and often with lower acceptance rates.

**Comment by emeryberger** [comment]
Updated after consulting with a few other people to verify. Thanks for the feedback.
