### ISSUE TITLE
Many VIS publications not in database

### ISSUE THREAD

**Issue by alexsb** [emeryberger/CSrankings#185]
This might be just an update issue, but a lot of VIS papers are not (yet) in the csrankings database: 

![image](https://cloud.githubusercontent.com/assets/2039375/21482140/70403a1e-cb70-11e6-9555-792f5cb00d88.png)

None of the Utah VIS faculty appear in this screenshot as the papers seem to be missing.

**Comment by emeryberger** [comment]
Thanks for the report. This should be mostly fixed with https://github.com/emeryberger/CSrankings/commit/9424e43282d7c35a96f121a601ae3308a2074175.
