### ISSUE TITLE
Michael S. Ryoo (UPDATE)

### ISSUE THREAD

**Issue by mryoo** [emeryberger/CSrankings#1864]
**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition
- [ ] Deletion
- [X] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_Michael S. Ryoo_

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
New: Stony Brook University
Old: Indiana University
https://www.cs.stonybrook.edu/people/faculty/MichaelRyoo

**Update/add a home page**
No updates or additions to be made here.

**Update/add a Google Scholar page.**
No updates or additions to be made here.

**Comment by emeryberger** [comment]
Hi - you appear to have a dual affiliation with Google. Please confirm here that your appointment with Stony Brook is full-time (> 75%) or that you are on sabbatical leave. For now, moving to `old/industry.csv`.

**Comment by mryoo** [comment]
I have more than 75% with Stony Brook. It will be great if you can move me back.

Thanks,

Michael

**Comment by emeryberger** [comment]
Will do.

**Comment by mryoo** [comment]
Thanks!

One question: in future, if I decide to be “on leave” from the department, how does this count?

Michael

**Comment by emeryberger** [comment]
Non-sabbatical leaves > 25% => removal from the database.

**Comment by mryoo** [comment]
Thanks for clarifying!
