### ISSUE TITLE
Amit P. Sheth ADD

### ISSUE THREAD

**Issue by quz105** [emeryberger/CSrankings#1881]
**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition

**Please check the box below to indicate that you have read the inclusion criteria.**
- [ x]

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Amit P. Sheth 

**Enter any aliases (multiple entries) given in DBLP.**

**Update/add an affiliation**
University of South Carolina
https://sc.edu/study/colleges_schools/engineering_and_computing/faculty-staff/amitsheth.php

**Update/add a home page**
https://www.linkedin.com/in/amitsheth/

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=2T3H4ekAAAAJ&hl=en

**Comment by emeryberger** [comment]
Added.
