### ISSUE TITLE
Paja, Elda (ADD)

### ISSUE THREAD

**Issue by bplank** [emeryberger/CSrankings#1888]
**Please indicate whether this is an addition, deletion, or modification**
- [X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._

**Enter any aliases (multiple entries) given in DBLP.**

https://dblp.org/pers/hd/p/Paja:Elda

**Update/add an affiliation**

IT University of Copenhagen

**Update/add a home page**

https://pure.itu.dk/portal/en/persons/elda-paja(ce1a5350-f645-4a53-a745-fca8d4f1f030).html

**Update/add a Google Scholar page.**

https://scholar.google.com/citations?user=5TAtu2cAAAAJ

**Comment by emeryberger** [comment]
Added.
