### ISSUE TITLE
Pat Pannuto, ADD

### ISSUE THREAD

**Issue by ppannuto** [emeryberger/CSrankings#1897]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._

https://dblp.org/pers/hd/p/Pannuto:Pat

**Enter any aliases (multiple entries) given in DBLP.**
_No aliases_

**Update/add an affiliation**
Joining as new Assistant Professor at UCSD
https://cse.ucsd.edu/people/faculty-profiles/pat-pannuto

**Update/add a home page**
https://patpannuto.com

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=4uuuczIAAAAJ

**Comment by emeryberger** [comment]
Added.
