### ISSUE TITLE
Lale Ozkahya plus (ADD)

### ISSUE THREAD

**Issue by ozkahya** [emeryberger/CSrankings#1903]
Please indicate whether this is an addition, deletion, or modification

[x ] Addition
 Deletion
 Modification
Please check the box below to indicate that you have read the inclusion criteria.

[x ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can solely advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.
Enter the faculty member's name AS LISTED IN DBLP, including disambiguation suffixes like 0001 as needed, as in Joe Shmoe 0001.
Lale Özkahya

Enter any aliases (multiple entries) given in DBLP.
Lale Özkahya

Update/add an affiliation
Hacettepe University
Department of Computer Engineering
https://www.cs.hacettepe.edu.tr/

Update/add a home page
Enter the full home page below. Please test it to make sure it is correct.
https://web.cs.hacettepe.edu.tr/~ozkahya/

Update/add a Google Scholar page.
https://scholar.google.com.tr/citations?hl=en&user=1GKiDzwAAAAJ

**Comment by ozkahya** [comment]
Hello. Above, I made a new submission to be added, although I already had a submission that was closed with issue #1634 and ended with me being added. The reason for my resubmission is that I could not see my name under Hacettepe University after being added with issue #1634. Thank you and sorry to bother you again. Lale

**Comment by emeryberger** [comment]
Hi - you don't show up because none of your publications are indexed by CSrankings.
