### ISSUE TITLE
Zhenman Fang, ADD

### ISSUE THREAD

**Issue by zhenman** [emeryberger/CSrankings#1944]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._
Zhenman Fang

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
List the new affiliation, and the old affiliation (if already in CSRankings). Please point to a web page (preferably institutional/departmental, but personal is OK), a LinkedIn site, or similar. If a faculty member has moved to industry, retired, or for other reasons departed academia, please indicate this here.
Assistant Professor, School of Engineering Science, Simon Fraser University, Canada
Associate Member, School of Computing Science, Simon Fraser University, Canada
http://www.sfu.ca/engineering/faculty-and-staff/faculty/zhenman_fang.html

**Update/add a home page**
Enter the full home page below. Please test it to make sure it is correct.
http://www.sfu.ca/~zhenman/

**Update/add a Google Scholar page.**
Please include a link to the faculty member's [Google Scholar](https://scholar.google.com) page. If none exists, please put "NOSCHOLARPAGE".
https://scholar.google.com/citations?user=v_FAgbgAAAAJ&hl=en

**Comment by emeryberger** [comment]
Can you clarify what the meaning of "associate member" is? I see you are not an adjunct, so it's not clear that you meet the inclusion criteria (solely advise a PhD student in computer science).

**Comment by zhenman** [comment]
Hi Emery,

Associate (Faculty) Member is the same as Adjunct Professor, which enables us to supervise graduate students (Master's and PhD) across departments at SFU. It is a special term at SFU, just like they call it "Computing Science" instead of "Computer Science". For appointments outside SFU, they call it "Adjunct Professor"; for appointments from a different department from SFU, they call it "Associate Member". 

Thanks,
Zhenman

**Comment by emeryberger** [comment]
Got it. Added.

**Comment by zhenman** [comment]
Thanks. It looks it missed one of my publications in the counting: I have 2 DAC papers (2012 and 2016) and 2 ICCAD papers (2015 and 2016). The system only counted 3.

Zhenman
