### ISSUE TITLE
Cesar Torres, ADD

### ISSUE THREAD

**Issue by cearto** [emeryberger/CSrankings#1956]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*
César Torres
https://dblp.uni-trier.de/pers/hd/t/Torres:C=eacute=sar

**Enter any aliases (multiple entries) given in DBLP.**
N/A

**Update/add an affiliation**
The University of Texas at Arlington
https://cse.uta.edu/people/faculty-directory.php

**Update/add a home page**
http://cearto.com/

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?hl=en&user=9CJbh1MAAAAJ

**Comment by emeryberger** [comment]
Added.
