### ISSUE TITLE
Faculty member name goes here, plus (ADD|UPDATE|DELETE)

### ISSUE THREAD

**Issue by sasharubin** [emeryberger/CSrankings#1986]
**Please indicate whether this is an addition, deletion, or modification**
- [ X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [ X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._

Sasha Rubin
https://dblp.uni-trier.de/pers/hd/r/Rubin:Sasha

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
New affiliation: School of Computer Science, University of Sydney

**Update/add a home page**
https://sasharubin.github.io/

**Update/add a Google Scholar page.**
https://scholar.google.it/citations?user=f5HrcOwAAAAJ&hl=en&oi=ao

**Comment by emeryberger** [comment]
Added.
