### ISSUE TITLE
Bob Kummerfeld

### ISSUE THREAD

**Issue by bobkummerfeld** [emeryberger/CSrankings#1988]
**Please indicate whether this is an addition, deletion, or modification**
- [X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Bob Kummerfeld

**Enter any aliases (multiple entries) given in DBLP.**
Robert Kummerfeld

**Update/add an affiliation**
retired, still working full time, affiliate appointment

**Update/add a home page**
https://sydney.edu.au/engineering/about/our-people/academic-staff/bob-kummerfeld.html

**Update/add a Google Scholar page.**
https://scholar.google.com.au/citations?user=STyZ33MAAAAJ&hl=en

**Comment by emeryberger** [comment]
Emeritus faculty are not eligible for inclusion.
