### ISSUE TITLE
More aliases for venues

### ISSUE THREAD

**Issue by bplank** [emeryberger/CSrankings#1991]
I'd like to suggest to add two more alias extracted from DLPL for NLP conferences:

```
"nlp","ACL","ACL (Short Papers)",True
"nlp","NAACL","NAACL-HLT (1)",True
```

**Comment by emeryberger** [comment]
I'm not sure what file this is meant to be from, but (a) short papers are explicitly not allowed (below 6 pages) and (b) NAACL-HLT (1) is already being included.

**Comment by bplank** [comment]
Hi @emeryberger 

thanks for the clarification re short - I have missed it.

Regarding "NAACL-HLT (1)" - I only see "NAACL-HLT" in the `venues.csv` -- as ACL has also several aliases in it (like [this one](https://github.com/emeryberger/CSrankings/blob/gh-pages/venues.csv#L71)), I thought it needs "NAACL-HLT (1)" (with the one behind) to be matched -- but perhaps that is not necessary?

thanks!

**Comment by emeryberger** [comment]
That file was cruft and I have removed it. All the venues are in `util/csrankings.py`.
