### ISSUE TITLE
Paul Ralph (UPDATE)

### ISSUE THREAD

**Issue by drpaulralph** [emeryberger/CSrankings#2009]
**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition
- [ ] Deletion
- [X] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._

Paul Ralph

**Update/add an affiliation**

New Affiliation: Dalhousie University
Old Affiliation: University of Auckland
Proof: https://www.dal.ca/faculty/computerscience/faculty-staff/paul-ralph.html

**Comment by emeryberger** [comment]
Updated!
