### ISSUE TITLE
Sanjay Rawat, UPDATE

### ISSUE THREAD

**Issue by tosanjay** [emeryberger/CSrankings#2048]
**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition
- [ ] Deletion
- [x] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_Sanjay Rawat 0001_

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
University of Bristol, UK (http://www.bristol.ac.uk/)
IIIT Hyderabad, India (https://www.iiit.ac.in/)

**Update/add a home page**
http://www.bristol.ac.uk/engineering/people/sanjay-rawat/index.html

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=9T1aL3wAAAAJ

**Comment by emeryberger** [comment]
Updated!
