### ISSUE TITLE
Luca Mottola UPDATE

### ISSUE THREAD

**Issue by lmottola** [emeryberger/CSrankings#2058]
**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition
- [ ] Deletion
- [X] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Luca Mottola

**Enter any aliases (multiple entries) given in DBLP.**
No aliases

**Update/add an affiliation**
Politecnico di Milano, Italy

**Update/add a home page**
http://home.deib.polimi.it/mottola/index.html

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=VkFc88EAAAAJ&hl=en&oi=ao

**Comment by emeryberger** [comment]
Modified.
