### ISSUE TITLE
Faculty member name goes here, plus (ADD|UPDATE|DELETE)

### ISSUE THREAD

**Issue by rolandotr** [emeryberger/CSrankings#2059]
**Please indicate whether this is an addition, deletion, or modification**
- [ x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [ x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, 

Rolando Trujillo-Rasua

**Update/add an affiliation**
New affiliation: Deakin University: https://www.deakin.edu.au/about-deakin/people/rolando-trujillo-rasua
Old affiliation: University of Luxembourg 

**Update/add a home page**
https://rolandotr.bitbucket.io/

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?user=USxx1TEAAAAJ&hl=en

**Comment by emeryberger** [comment]
Hi - Deakin is not in the database so all faculty need to be added via a github pull request.
