### ISSUE TITLE
Kai Liu, ADD

### ISSUE THREAD

**Issue by liukaizhijia** [emeryberger/CSrankings#2063]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name** 
*Kai Liu 0018*
https://dblp.uni-trier.de/pers/hd/l/Liu_0018:Kai

**Enter any aliases (multiple entries) given in DBLP.**
N/A
**Update/add an affiliation**
Clemson University, Computer Science Division
https://www.clemson.edu/cecas/departments/computing/people/faculty/computer_science.html

**Update/add a home page**
https://sites.google.com/view/kailiu/home

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?view_op=list_works&hl=en&user=4justeYAAAAJ

**Comment by emeryberger** [comment]
Added.
