### ISSUE TITLE
Ji Wu, ADD

### ISSUE THREAD

**Issue by isjakewong** [emeryberger/CSrankings#2064]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
https://dblp.org/pers/hd/w/Wu:Ji

**Enter any aliases (multiple entries) given in DBLP.**
N/A

**Update/add an affiliation**
Tsinghua University

**Update/add a home page**
https://www.tsinghua.edu.cn/publish/eeen/3784/2010/20101219135614305780920/20101219135614305780920_.html

**Update/add a Google Scholar page.**
https://scholar.google.co.in/citations?user=1V8LxbYAAAAJ&hl=en

**Comment by emeryberger** [comment]
Added.
