### ISSUE TITLE
Eitan Grinspun UPDATE

### ISSUE THREAD

**Issue by user123456789012345** [emeryberger/CSrankings#2085]
**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition
- [ ] Deletion
- [x] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._
Eitan Grinspun

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
List the new affiliation, and the old affiliation (if already in CSRankings). Please point to a web page (preferably institutional/departmental, but personal is OK), a LinkedIn site, or similar. If a faculty member has moved to industry, retired, or for other reasons departed academia, please indicate this here.
old: Columbia University
new: University of Toronto
https://web.cs.toronto.edu/contact-us/faculty-directory#tenurestream

**Update/add a home page**
Enter the full home page below. Please test it to make sure it is correct.

**Update/add a Google Scholar page.**
Please include a link to the faculty member's [Google Scholar](https://scholar.google.com) page. If none exists, please put "NOSCHOLARPAGE".

**Comment by emeryberger** [comment]
Can we get Eitan to verify? His Columbia web page does not indicate any changes.

**Comment by user123456789012345** [comment]
@eitangrinspun ?

**Comment by emeryberger** [comment]
Closing for now; please re-open once you have concrete evidence of this change (not reflected anywhere I can see yet).

**Comment by user123456789012345** [comment]
He is listed here:

https://web.cs.toronto.edu/contact-us/faculty-directory#tenurestream

**Comment by user123456789012345** [comment]
He is also listed here:

https://www.dgp.toronto.edu/people-gallery
and
https://www.dgp.toronto.edu/~eitan/

**Comment by emeryberger** [comment]
I sent Eitan mail; we will see what he says.

**Comment by emeryberger** [comment]
No response to my e-mail. His latest arxiv paper lists two affiliations (see https://arxiv.org/pdf/1911.08029.pdf), which is not actually supported by CSrankings, so pending clarification, I am removing him from the database.

**Comment by emeryberger** [comment]
Clarified affiliation; added with https://github.com/emeryberger/CSrankings/commit/f19b0755fc4825a984aefbe6d4dbb6509dbb18d4.
