### ISSUE TITLE
URLs for PL rankings

### ISSUE THREAD

**Issue by jgbm** [emeryberger/CSrankings#2086]
I'm attempting to a permanent URL to the rankings including all programming languages venues.  I can do something like:

http://csrankings.org/#/fromyear/2015/toyear/2019/index?plan

for example, but when I include ICFP and OOPSLA, the URL becomes

http://csrankings.org/#/fromyear/2015/toyear/2019/index?none

which isn't as useful to send around.

**Comment by emeryberger** [comment]
This is a feature, not a bug: only top tier venues are included in permalinks.
