### ISSUE TITLE
Robert J. Teather, ADD

### ISSUE THREAD

**Issue by agirouard** [emeryberger/CSrankings#2094]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Robert J. Teather

**Enter any aliases (multiple entries) given in DBLP.**

**Update/add an affiliation**
Carleton University

**Update/add a home page**
https://www.csit.carleton.ca/~rteather/

**Update/add a Google Scholar page.**
https://scholar.google.ca/citations?user=KjJbkk8AAAAJ&hl=en

**Comment by emeryberger** [comment]
Not clearly in CS:
https://carleton.ca/scs/our-people/school-of-computer-science-faculty/
https://carleton.ca/scs/our-people/school-of-computer-science-faculty/adjunct-faculty/

**Comment by agirouard** [comment]
Dr. Teather is in the School of Information Technology at Carleton and has a PhD in Computer Science. https://www.csit.carleton.ca/index.php?pageID=PeopleFaculty

He should be listed on CS Rankings.

**Comment by emeryberger** [comment]
The inclusion criteria are very specific.

> Eligible faculty include only full-time, tenure-track
> faculty members on a given campus who can solely advise PhD students in
> Computer Science. Faculty not in a CS department or similar who can
> advise PhD students in CS can be included regardless of their home
> department.
> 

They must be able to solely advise PhD students _in the Computer Science_ department.

**Comment by agirouard** [comment]
You have a very narrow view of those who do research in computer science, it’s quite unfortunate, especially since I see a number of people in your list which are not in a department called computer science (decision science, Automated Manufacturing Engineering, Software and IT Engineering, Management science).

CS-Can, the Canadian national, non-profit society dedicated to representing all aspects of computer science and the interests of the discipline across Canada, recognizes the School of Information Technology as a departmental member.
https://cscan-infocan.ca/members/departments/

**Comment by emeryberger** [comment]
The target audience of CSrankings is, and has always been, prospective graduate students looking for a graduate program in computer science. Hence the criteria.
