### ISSUE TITLE
Unjust Geometric Mean Formula

### ISSUE THREAD

**Issue by dishuk13** [emeryberger/CSrankings#210]
The geometric mean formula automatically assigns the adjusted count of an area to 1 if it was zero previously. 

This seems unfair to universities which have non-zero very small count in that area. It would just have been better to not have published at all.

@emeryberger

**Comment by emeryberger** [comment]
Your proposed replacement is what exactly?

**Comment by dishuk13** [comment]
I propose that instead of being of the form GM(geometric mean) = **(&Pi; c<sub>i</sub>)<sup>1/n</sup>**, it should be of the form GM = **(&Pi; (c<sub>i</sub>+a))<sup>1/n</sup>**, where **a** is a constant. It can be taken as 1 for convenience. 

If a is taken as 1, it will be consistent with assigning all zeroes to one and shift all counts up by one.

**Comment by emeryberger** [comment]
This seems reasonable. Thanks! (incorporated in latest commit)
