### ISSUE TITLE
Alexander Egyed (ADD)

### ISSUE THREAD

**Issue by alexander-egyed** [emeryberger/CSrankings#2101]
**Please indicate whether this is an addition, deletion, or modification**
- [ X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [ X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
https://dblp.org/pers/hd/e/Egyed:Alexander

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
Johannes Kepler University of Linz, Austria

**Update/add a home page**
https://www.jku.at/en/institute-for-software-systems-engineering/about-us/team/alexander-egyed/

**Update/add a Google Scholar page.**
https://scholar.google.at/citations?user=tN-tEGIAAAAJ&hl=en&oi=ao

**Comment by emeryberger** [comment]
Hi - this institution is not yet in the database. Please add all CS faculty via a GitHub pull request. Thanks.
