### ISSUE TITLE
Mark Yim, ADD

### ISSUE THREAD

**Issue by markyim** [emeryberger/CSrankings#2111]
**Please indicate whether this is an addition, deletion, or modification**
- [X ] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._
Mark Yim

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
List the new affiliation, and the old affiliation (if already in CSRankings). Please point to a web page (preferably institutional/departmental, but personal is OK), a LinkedIn site, or similar. If a faculty member has moved to industry, retired, or for other reasons departed academia, please indicate this here.
I have recently been appointed as secondary faculty in Computer and Information Sciences department at University of Pennsylvania which enables me to be the sole advisor to  CIS PhD students. The CIS website has not yet been updated.  If needed, I can submit the appointment letter from the Chair of the CIS department, just let me know - (yim@seas.upenn.edu). 

**Update/add a home page**
Enter the full home page below. Please test it to make sure it is correct.

**Update/add a Google Scholar page.**
Please include a link to the faculty member's [Google Scholar](https://scholar.google.com) page. If none exists, please put "NOSCHOLARPAGE".
https://scholar.google.com/citations?user=6zm5XD8AAAAJ&hl=en

**Comment by emeryberger** [comment]
Please attach a letter here. Also, I need a home page. Thanks.

**Comment by emeryberger** [comment]
I am closing this pending a response; just re-open it with updates. Thanks.

**Comment by markyim** [comment]
Hi Emily,

You need a home page, like my lab research page?

that is
https://www.modlabupenn.org/

I'm attaching the appointment letter here.

thanks
mark

**Comment by emeryberger** [comment]
Please provide your personal or professional home page (though if the lab page is your only such page, that's fine). No attachment has appeared.

**Comment by markyim** [comment]
I have no personal page anymore... I should make one.
So lets use the lab one.

That is wierd about the attachment not appearing, my mailer said it
attached it. I'll attach again to this email.

mark

**Comment by markyim** [comment]
Hi Emery,

Did you receive the appointment letter attachment? Also, my profile page at penn
has been updated with my CIS appointment in case you want to use it. 
https://www.seas.upenn.edu/directory/profile.php?ID=107

Maybe this could used as a professional home page as well if you like.

thanks,
mark

**Comment by emeryberger** [comment]
No attachment, but that profile page works. Thanks! (Added, pushing update momentarily.)
