### ISSUE TITLE
More strict ordering in "Average count"

### ISSUE THREAD

**Issue by dishuk13** [emeryberger/CSrankings#212]
As of now, geometric mean is shown and compared upto one decimal place which leads to a lot of universities clustering together. 

I propose that the number of decimal places upto which it is compared can be increased, say 8 decimal places. Although, the number of digits shown can be kept the same for keeping the UI clean.

@emeryberger

**Comment by emeryberger** [comment]
Added precision just to force a ranking makes no sense. The clustering is appropriate - these universities are really close to each other.
