### ISSUE TITLE
Number of faculty is incorrectly displayed on the site

### ISSUE THREAD

**Issue by dishuk13** [emeryberger/CSrankings#215]
![screen shot 2017-02-10 at 5 39 48 pm](https://cloud.githubusercontent.com/assets/15903013/22826361/0f0f0eca-efb8-11e6-8f3a-89f4d133b864.png)

This snapshot shows that IIIT Bangalore has 6 members listed but just 5 is shown as the number.

**Comment by emeryberger** [comment]
Fixed with https://github.com/emeryberger/CSrankings/commit/31c086e7afe22a538231f98cc87ca8e8f55559b5. Thanks for the report.
