### ISSUE TITLE
Not all faculty of a university is shown

### ISSUE THREAD

**Issue by dishuk13** [emeryberger/CSrankings#216]
Ashish Choudhury from IIIT Bangalore has one publication in CRYPTO but is not shown in the UI. 
He also is present in faculty-affiliations.csv. 
![screen shot 2017-02-11 at 2 25 11 pm](https://cloud.githubusercontent.com/assets/15903013/22852638/1a9d1d00-f066-11e6-81e7-205d27466c33.png)

This bug arose after the [ last bug fix](https://github.com/emeryberger/CSrankings/commit/31c086e7afe22a538231f98cc87ca8e8f55559b5).

**Comment by emeryberger** [comment]
I removed the alias Ashish Choudhary because it is mostly not this person. Ashish needs to contact DBLP to fix this entry.

**Comment by dishuk13** [comment]
>I removed the alias Ashish Choudhary **because it is mostly not this person**

I don't think so. Check out the publications at this [DBLP page](http://dblp.uni-trier.de/pers/hd/c/Choudhury:Ashish) and his [homepage](https://sites.google.com/site/ashishcrypto/).

Also note that it is **Choudhury** not **Choudhary**.  Maybe you saw the wrong person.

**Comment by emeryberger** [comment]
Look closely: DBLP has an alias for this spelling. Many of the publications are listed under this name (50). I will restore the alias, which I assumed was incorrect.
