### ISSUE TITLE
The absence of Sun Yat-sen university in CSrankings.

### ISSUE THREAD

**Issue by sh2huang** [emeryberger/CSrankings#2174]
I know there are some great researchers such as Liang Lin in Sun Yat-sen university. And it is also a well-known university in China. But it does not appear in the list of CSrankings. What is the matter?

**Comment by actbee** [comment]
You can add it by yourself.^-^

**Comment by emeryberger** [comment]
Most of the institutions in the database were contributed. You can do so via a pull request.
