### ISSUE TITLE
Yingzhen Yang (ADD)

### ISSUE THREAD

**Issue by ASU-Active-Perception** [emeryberger/CSrankings#2182]
**Please indicate whether this is an addition, deletion, or modification**
- [*] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [*] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
Yingzhen Yang

**Enter any aliases (multiple entries) given in DBLP.**

**Update/add an affiliation**
Arizona State University

**Update/add a home page**
http://yingzhenyang.com/

**Update/add a Google Scholar page.**
https://scholar.google.com/citations?hl=en&user=36vh2hgAAAAJ&view_op=list_works&sortby=pubdate

**Comment by emeryberger** [comment]
Please point to an administrative page for CS. Not found here: https://cidse.engineering.asu.edu/faculty/

**Comment by ASU-Active-Perception** [comment]
Here you go: https://cidse.engineering.asu.edu/yingzhen-yang/
