### ISSUE TITLE
Przemyslaw Musialski, ADD

### ISSUE THREAD

**Issue by musialski-lab** [emeryberger/CSrankings#2186]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._
Przemyslaw Musialski

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**
List the new affiliation, and the old affiliation (if already in CSRankings). Please point to a web page (preferably institutional/departmental, but personal is OK), a LinkedIn site, or similar. If a faculty member has moved to industry, retired, or for other reasons departed academia, please indicate this here.
New Jersey Institute of Technology
The primary affiliation (NJIT) is > 75% (full time). Please add with primary affiliation.
https://cs.njit.edu/faculty/przem

**Update/add a home page**
Enter the full home page below. Please test it to make sure it is correct.
https://web.njit.edu/~przem/

**Update/add a Google Scholar page.**
Please include a link to the faculty member's [Google Scholar](https://scholar.google.com) page. If none exists, please put "NOSCHOLARPAGE".
https://scholar.google.com/citations?user=GG5256IAAAAJ

**Comment by emeryberger** [comment]
Appears to have joint affiliation with two institutions, but partial affiliations are not supported by CSrankings ("Additionally, he heads the Computational Fabrication group at the Center for Geometry and Computational Design (GCD) at the TU Wien in Vienna in Austria"). Primary institution must be >= 75% to be in the database. Please re-open and confirm if appropriate.

**Comment by musialski-lab** [comment]
The primary affiliation (NJIT) is > 75% (full time). Please add with primary affiliation.
