### ISSUE TITLE
ICS aliasing issue

### ISSUE THREAD

**Issue by bondhugula** [emeryberger/CSrankings#221]
http://dblp.uni-trier.de/db/conf/innovations/index.html is being treated as http://dblp.uni-trier.de/db/conf/ics/index.html 
and is being counted under HPC.

**Comment by emeryberger** [comment]
Can you point to an example? The XML entries for the two conferences are different (ITCS vs. ICS), and HPC only includes ['SC', 'HPDC', 'ICS'].

https://github.com/emeryberger/CSrankings/blob/gh-pages/util/csrankings.py#L63

**Comment by bondhugula** [comment]
IISc Bangalore -> Arnab Bhattacharyya
http://dblp.uni-trier.de/pers/hd/b/Bhattacharyya:Arnab

**Comment by emeryberger** [comment]
Not a CSrankings bug - a DBLP bug. Reported. Closing for now, hopefully fixed in next update of DBLP.
