### ISSUE TITLE
Xiang-Yang Li (UPDATE)

### ISSUE THREAD

**Issue by DwyaneSuarez** [emeryberger/CSrankings#2220]
Prof. Xiang-Yang Li of USTC was announced as a Fellow of the ACM this year. Please add the "ACM Fellow" icon.
https://en.ustc.edu.cn/2019/1215/c15527a408365/pagem.htm
https://awards.acm.org/fellows/award-winners

**Comment by emeryberger** [comment]
Already in the database. Thanks.
