### ISSUE TITLE
Wrong number of raw publications

### ISSUE THREAD

**Issue by dishuk13** [emeryberger/CSrankings#224]
This is for K. Srinathan of IIIT Hyderabad. The pie chart shows a different value from the raw number  of publication.
![screen shot 2017-02-15 at 11 33 49 pm](https://cloud.githubusercontent.com/assets/15903013/22988267/7812f670-f3d7-11e6-9414-29c40c22615a.png)

**Comment by emeryberger** [comment]
Fixed with https://github.com/emeryberger/CSrankings/commit/c9832f2da93b5e3a3e4333c337157af652685bf4.

<img width="502" alt="screen shot 2017-02-15 at 8 20 29 pm" src="https://cloud.githubusercontent.com/assets/1612723/23003055/418f238c-f3bc-11e6-9645-3ba661b0b2c3.png">
