### ISSUE TITLE
Rahul Savani ADD

### ISSUE THREAD

**Issue by VishalWilde** [emeryberger/CSrankings#2244]
**Please indicate whether this is an addition, deletion, or modification**
- [X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**

Rahul Savani

**Update/add an affiliation**

University of Liverpool 
https://cgi.csc.liv.ac.uk/~rahul/

**Update/add a home page**

https://www.liverpool.ac.uk/computer-science/staff/rahul-savani/

**Update/add a Google Scholar page.**

https://scholar.google.co.uk/citations?user=bfqfILEAAAAJ&hl=en

**Comment by emeryberger** [comment]
Added.
