### ISSUE TITLE
James R. Wallace, University of Waterloo (ADD)

### ISSUE THREAD

**Issue by JimWallace** [emeryberger/CSrankings#2279]
**Please indicate whether this is an addition, deletion, or modification**
- [X] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
James R. Wallace

**Enter any aliases (multiple entries) given in DBLP.**
https://dblp.uni-trier.de/pers/hd/w/Wallace:James_R=

**Update/add an affiliation**
University of Waterloo

**Update/add a home page**
uwaterloo.ca/hci-health

**Update/add a Google Scholar page.**
https://scholar.google.ca/citations?user=uCxDo9sAAAAJ

**Comment by JimWallace** [comment]
Please add me to CS Rankings. Thank you.

https://cs.uwaterloo.ca/about/people/group/53

**Comment by emeryberger** [comment]
(added)
