### ISSUE TITLE
tweak/option for collaboration display

### ISSUE THREAD

**Issue by andrewcmyers** [emeryberger/CSrankings#228]
It would be great to have the visualization show what fraction of the total research produced by the department or by individuals is actually collaborative. A simple way to do that would be to add to each individual's bar segments corresponding to that other research. Possibly scaled in some intelligent way so that the total research output of the department matches the circumference of the circle (collaborative research is overcounted in some sense since it appears in multiple bars...)

**Comment by emeryberger** [comment]
Removed collaboration graphs, so closing for now.
