### ISSUE TITLE
add icons (and links) to blind-reviewing policies of the various conferences

### ISSUE THREAD

**Issue by emeryberger** [emeryberger/CSrankings#2331]
The proposed feature is that each conference would have small icons beside them indicating their blind-reviewing status, along with links to the relevant entry on https://double-blind.org.

My current thought is to use the following (where the left "eye" denotes whether authors are known, and the right "eye" is whether reviewers are known) - _lots_ of possible permutations here:

* double-blind: ๏๏ (or ●●, or ◎◎)
* partially double-blind: ◔๏ (or ◐๏, or ◍๏, or ◐●, or ◍●, or ◔◎, or ◍◎) 
* single-blind: ⊙๏ (or ๏●, or ⊙●, or ๏◎)

(Unicode list here: https://www.fileformat.info/info/unicode/block/geometric_shapes/list.htm)

**Comment by emjun** [comment]
What about..
- double-blind: ●
- partially double-blind: ◉
- single-blind: ◐ or ◑ 

Concept: 
- Right half circle is for if authors know their reviewers
- Left half circle is for if reviewers know their papers 

Pros: 
- This eliminates the need for two circles, which would be two different sizes/look odd? (Simpler key to add next to conferences)

Cons: 
- No more eyes metaphor.

Thoughts?
