### ISSUE TITLE
error in formation of the DBLP url

### ISSUE THREAD

**Issue by gqmaguirejr** [emeryberger/CSrankings#2345]
The generated DBLP link points to:
     https://dblp.uni-trier.de/pers/hd/j/Jr=:Gerald_Q=_Maguire
whereas it should point to:
    https://dblp.uni-trier.de/pers/hd/m/Maguire_Jr=:Gerald_Q=

**Comment by emeryberger** [comment]
This was a known issue - addressed it with https://github.com/emeryberger/CSrankings/commit/079ce7ac6a6c0b6af68d6cb8c9dbaebd397c75e1. Thanks!
