### ISSUE TITLE
Machine learning and data mining should be separate categories.

### ISSUE THREAD

**Issue by airalcorn2** [emeryberger/CSrankings#238]
In my opinion, machine learning and data mining are distinct enough fields to warrant their own categories. Data mining research is generally more applied than machine learning research, so I don't think someone who is interested in doing research in machine learning would necessarily be interested in institutions who are primarily conducting research in data mining. As it stands, I think including KDD with NIPS and ICML makes it difficult to determine where an institution lies on the theoretical/applied spectrum, which makes the rankings not particularly useful in that regard.

**Comment by emeryberger** [comment]
Note that PL includes a systems-oriented conference and a theoretically-inclined conference. Separating *areas* into theoretical or applied sub-parts is not likely to happen; a long-term goal is to make it possible to drill down and turn conferences on and off, but this will require a significant overhaul of the UI and databases.

Please separate out the issues (e.g., ICLR inclusion should be a separate issue). Thanks.

**Comment by airalcorn2** [comment]
The relationship between natural language processing and information retrieval, which have their own categories, mirrors the relationship between machine learning and data mining. Further, I suspect if you built a citation graph you'd find many more links between NIPS, ICML, and ICLR than any of them have to KDD (a cursory glance over papers from 2016 proceedings supports my hypothesis).

**Comment by fycus-tree** [comment]
Per #240, #121 . I think this makes total sense. These communities don't really interact that much. And currently mlmining is the size of 2 or 3 categories (#562 has totals).  Then it would make sense to have something like this:

'mining': 'sdm','kdd','icdm'
'ml': 'icml','nips'

This would involve adding SDM (26% 93 papers) , ICDM (20% 155 papers) in addition to the current  KDD (19% 214 papers). The separation into two pairs, ICDM&KDD plus NIPS&ICML also makes sense. 

@emeryberger  if you need to ask someone. Look at your own university. Akshay Krishnamurthy has 1 KDD paper, but 8 NIPS, 7 ICML. While David Jensen has 10 KDD papers & 4 ICDM papers but only 1 NIPS paper.

EDIT: Additionally, [a paper](https://arxiv.org/abs/1710.05225) has come out which looked at CSRankings data but also split ML and Data-mining for analysis. Additionally the numbers in #859 suggest that this split should happen.

**Comment by bhatiasiddharth** [comment]
@emeryberger Sir, can you check if separating DM/ML communities is possible? Thanks.
