### ISSUE TITLE
Add ICLR to machine learning conferences.

### ISSUE THREAD

**Issue by airalcorn2** [emeryberger/CSrankings#240]
ICLR is a young conference, but it is already highly regarded and has featured many papers from some of the top minds in machine learning.

**Comment by yilinyang7** [comment]
I agreed. ICLR is definitely a top conference now.

**Comment by fycus-tree** [comment]
third. 
http://www.ee.cuhk.edu.hk/~yangli/community/trans_conf.html suggests as much, even if ICLR isn't formally counted in any evaluations yet

**Comment by matthew-z** [comment]
Agree. ICLR has only about 15 conference papers each year, so the result should not change much unless the poster track counts.

**Comment by ducha-aiki** [comment]
@matthew-z Poster track is main track everywhere, isn`t it? Poster does not mean "workshop".

**Comment by VVinayak** [comment]
Please add ICLR, RLDM and CoRL if possible

**Comment by animesh-garg** [comment]
I would request to add ICLR (ML) and CoRL (Robotics)
RLDM is a workshop (no proceedings) - hence can be left out of the list archival publications.

**Comment by fycus-tree** [comment]
CoRL has only happened twice. It's totally not clear that it's a top tier conference that should replace RSS/IROS/ICRA (Edit: Emery currently has a limit of 3 per area)

ICLR's biggest issue is that it's not tracked in DBLP, so Emery cannot add it. I've sent a note to the DBLP maintainers to add ICLR.

**Comment by fycus-tree** [comment]
@emeryberger ICLR is now in DBLP.

**Comment by yilinyang7** [comment]
@emeryberger vote for ICLR, which is happening right now, and it's definitely a top conference.

**Comment by DwyaneSuarez** [comment]
ICLR should be considered as "top conference" in the machine learning field. As for the number limit, I think Emery can add a "data mining" field which counts the number of papers in KDD and ICDM.

**Comment by alexlyzhov** [comment]
Guys, ICLR... Please... :) came here to say this.
The absence of ICLR has been detracting from the value of csrankings a lot for as long as I have been using it.

**Comment by alexlyzhov** [comment]
Google Scholar [ranks](https://scholar.google.ru/citations?view_op=top_venues&hl=en&vq=eng) ICLR as the top ML conference by h5 index, above NeurIPS.

**Comment by HongyangGao** [comment]
Add ICLR please.
