### ISSUE TITLE
No publication profile for many professors

### ISSUE THREAD

**Issue by dishuk13** [emeryberger/CSrankings#245]
Many professors from IIT Delhi such as Saroj Kaushik, Prem Kumar Kalra, etc. don't have their publication profile showing up. Please look into this.

@emeryberger

**Comment by emeryberger** [comment]
What exactly is the problem? For example, I see only one pub for Saroj Kaushik (an IJCAI pub, correct). Only the publications indicated are counted.

**Comment by dishuk13** [comment]
I mean that the circular graph is not displayed at all.

**Comment by emeryberger** [comment]
Do you mean the co-author graph?

**Comment by dishuk13** [comment]
Yes. This is what I see.
![image](https://cloud.githubusercontent.com/assets/15903013/23830360/0293afbe-072f-11e7-8be1-e4fb2c1975a7.png)

**Comment by emeryberger** [comment]
Thanks for the bug report. This has been fixed.
