### ISSUE TITLE
TCC

### ISSUE THREAD

**Issue by ivanvisconti** [emeryberger/CSrankings#250]
TCC is a great conference. The recent Gödel Prize has been awarded to a TCC paper. I think it should be added to the Cryptography category.

**Comment by emeryberger** [comment]
It is not in the same equivalence class as the other two.

2015 acceptance rates:
CRYPTO: 27.8%
EuroCrypt: 29.3%
TCC 2015: 38%

Google Scholar metrics:
CRYPTO: h5-index = 51, h5-median = 83
EuroCrypt: h5-index = 50, h5-median = 85
TCC (Theory of Cryptography): h5-index = 36, h5-median = 60

**Comment by ivanvisconti** [comment]
Thanks a lot for explaining the metrics considered to decide membership in equivalence classes. Just for completeness: TCC is a 100% theory conference, while instead CRYPTO and EUROCRYPT include a large  (perhaps nowadays even > 50%) non-theoretical part (and this of course can significantly affect those metrics and might be considered of non-negligible importance for the membership of a conference to the subarea "Cryptography" of the area "Theory").
