### ISSUE TITLE
Request for Change (Add region - UK / United Kingdom)

### ISSUE THREAD

**Issue by VishalWilde** [emeryberger/CSrankings#2500]
Hi Emery, I just wanted to make a 'Request for Change' to the repository (not sure how straightforward it will be). I noticed that institutions in Canada can be ranked within 'Canada' or 'USA and Canada'. Given that UK universities now have 26 entries within 'Europe', could we also have an option solely for 'the UK' and another for 'the UK and Europe'? 

The UK institutions from the Europe list (at least those displayed on the CSRankings webpage) are as follows:

1. University of Edinburgh
2. University of Oxford
3. University College London
4. Imperial College London
5. University of Cambridge
6. University of Warwick
7. University of Bristol
8. University of Liverpool
9. King's College London
10. University of Southampton
11. University of Bath
12. University of Sheffield
13. University of Surrey
14. University of York
15. Queen Mary University of London
16. Royal Holloway University of London
17. University of Nottingham
18. University of St Andrews
19. Durham University
20. Heriot-Watt University
21. University of Manchester
22. University of Sussex
23. Middlesex University
24. University of Kent
25. University of Dundee
26. University of Exeter

**Comment by emeryberger** [comment]
I feel like doing this (BR-CSrankings-exit? 😄) would be opening Pandora's box. There are many universities in other countries, even if they are not all yet in the database, so I'd rather not set such a precedent.

**Comment by VishalWilde** [comment]
Thanks - I understand where you’re coming from so I’ll close this issue. My only suggestion would be that, rather than discount it entirely, it may be something to keep in the pipeline / back-burner (resource and time permitting). I think a lot of countries’ domestic rankings are really lacking and, for what it’s worth, I wish that I had had something like CSRankings for Economics (my undergraduate major). Also, I think with the precedent being set for the USA and Canada, it’s likely to be raised again in future.

Many thanks once again for this really useful database and resource!
