### ISSUE TITLE
University of Wisconsin-Madison duplication 

### ISSUE THREAD

**Issue by VishalWilde** [emeryberger/CSrankings#2507]
Entry for the University of Wisconsin-Madison is duplicated / split (appears twice with different faculty).

**Comment by emeryberger** [comment]
Fixed, thanks.

**Comment by VishalWilde** [comment]
No problem although there are still two separate listings for the university showing up.

**Comment by emeryberger** [comment]
Found it - someone had committed an entry with an em-dash and non-standard spacing. Fixed. Thanks again!
