### ISSUE TITLE
[institution add] Inria is missing

### ISSUE THREAD

**Issue by ejgallego** [emeryberger/CSrankings#2564]
The French Research institute for computer science Inria is missing, thus a large set of French and european-funded papers.

**Comment by emeryberger** [comment]
I'd gladly take a pull request adding Inria.

**Comment by ejgallego** [comment]
I'm looking into it, thanks. The issue is a bit complex due to the way France organizes research groups; for example there are a few Inria researchers that appear in the list however their affiliation is the Inria group they belong to; that's incorrect I think.
