### ISSUE TITLE
[feature request] Track institution changes

### ISSUE THREAD

**Issue by ejgallego** [emeryberger/CSrankings#2565]
After a quick look to the database, it seems that people changing institutions are not properly tracked [really sorry for the noise if I got this wrong]

IMHO researcher info should have date metadata so papers in previous institutions are counted correctly.

**Comment by emeryberger** [comment]
Previous institutions aren't counted in any way in the rankings, so I don't understand the issue.

**Comment by emeryberger** [comment]
That is, when a faculty member moves to a different institution, their papers "move with them."

**Comment by ejgallego** [comment]
> their papers "move with them."

If that's the correct methodology then OK [I'm ignorant myself]

On the other hand it seems unfair that papers move with people, for example if an institution hires a star researcher that may bump it a lot in the rankings; would that be fair / representative?

**Comment by sebastianrjay** [comment]
> > their papers "move with them."
> 
> If that's the correct methodology then OK [I'm ignorant myself]
> 
> On the other hand it seems unfair that papers move with people, for example if an institution hires a star researcher that may bump it a lot in the rankings; would that be fair / representative?

Most students (and professors and anyone else reading the rankings) want to know the current quality of each university's research team. When a researcher leaves a university, that researcher no longer contributes to the quality of that university's research team, so attributing their previous publications to their previous university would mislead anyone reading the rankings. Note that any paper co-authored by researchers at different universities counts for each university in proportion to its share of the paper's authorship.

**Comment by ejgallego** [comment]
Sounds reasonable indeed. I propose then to close this issue, I'll do a pass on the FAQ first to see if we could add some point on this question.

Tracking dates tho could be of general interest for other reasons, so indeed the date range could be optionally added to the schema in case someone would find an utility.

**Comment by sebastianrjay** [comment]
> Tracking dates tho could be of general interest for other reasons, so indeed the date range could be optionally added to the schema in case someone would find an utility.

Agreed. Similarly, displaying the "Last Updated at [date]" snippet above the rankings table would be helpful. It's already shown at the bottom of the homepage.

**Comment by emeryberger** [comment]
Thanks for the discussion.

The latest update info is about publication data from the DBLP database. Other updates are far too frequent for it to make sense to change the home page; also, for mobile devices, using up real estate at the top of the screen is sub-optimal.
