### ISSUE TITLE
All NLP publication data missing for GA Tech and Wisconsin-Madison

### ISSUE THREAD

**Issue by sebastianrjay** [emeryberger/CSrankings#2571]
When I navigate to the homepage of csrankings.org, I notice that the pie charts under Georgia Tech (11) and the University of Wisconsin-Madison (12) contain zero NLP publications.

But when I use the Cntrl+F webpage search feature of my browser to search for "EMNLP" on this webpage, I see clearly that GA Tech has EMNLP publications between 2010 and 2020: https://mlp.cc.gatech.edu/publications.html

(Note: there seem to be intermittent connectivity issues with the above webpage. Perhaps some scraper is overwhelming it and would be best reimplemented with exponential request backoff.)

**Comment by emeryberger** [comment]
The faculty members who are authors of articles on that page are half-time at FAIR and thus do not meet the inclusion criteria (>= 75% time during the academic year).

**Comment by sebastianrjay** [comment]
> The faculty members who are authors of articles on that page are half-time at FAIR and thus do not meet the inclusion criteria (>= 75% time during the academic year).

Why are half-time profs not counted? That still allows them to be significantly impactful at their university. Having insight into the academic world in addition to the private sector is tremendously valuable to students. Moreover, CS research performed at private companies is not inherently any less valuable or cutting-edge than CS research performed at universities.

And why are other half-time profs (like [Fei-Fei Li](https://www.linkedin.com/in/fei-fei-li-4541247)) counted in the rankings, but Dhruv Batra and Devi Parikh aren't?
