### ISSUE TITLE
Including Transactions on Graphics for the graphics community

### ISSUE THREAD

**Issue by thillana** [emeryberger/CSrankings#259]
Thank you for the efforts in putting together this ranking. 

Since 2008, there has been a move in the computer graphics community to unify SIGGRAPH/SIGGRAPH Asia/TOG. SIGGRAPH and SIGGRAPH Asia papers are published as a special issue of Transactions on Graphics, the premier journal in computer graphics. Further, all TOG papers (even those that are not SIGGRAPH/SIGGAsia papers) are presented at either conference by the author’s choosing. The goal of all these changes since 2008 has been to create seamless, high visibility journal publications for the best work in graphics. See http://tog.acm.org/about.cfm for a description articulating this goal. This has been presented by SIGGRAPH/SIGGRAPH Asia chairs to their attendees and at the SIGGRAPH/SIGGRAPH Asia PC meetings.

Given the community efforts to unify our venues, SIGGRAPH/TOG/SIGAsia are together more representative of the best papers of the graphics community. Therefore, we recommend that you 
 add Transaction on Graphics (along with SIGGRAPH and SIGGRAPH Asia) to your list for graphics.

Thank you for your time. Feel free to contact us if you would like more information.

Best,
Kavita Bala (Cornell, TOG Editor-in-Chief)
Jessica Hodgins (CMU, SIGGRAPH Executive Committee member)
Holly Rushmeier (Yale, SIGGRAPH Papers Advisory Group chair)

**Comment by emeryberger** [comment]
Right now, the policy in CSrankings is to only include conferences or journals when those journals comprise conference proceedings. The situation you describe seems to be blurring these lines further. Some questions:

- Are _all_ TOG papers presented at SIGGRAPH / SIGGRAPH Asia?
- What is the acceptance rate for papers submitted to TOG?

**Comment by thillana** [comment]
Yes, all TOG papers are presented at SIGGRAPH/SIGGRAPH Asia. 

I do not have the accurate acceptance rates for TOG right now, but can work on getting that to you.

**Comment by emeryberger** [comment]
Hi @thillana (nice meeting you in person yesterday) - figured I'd ping you about this.

**Comment by yig** [comment]
All TOG papers are invited to appear at SIGGRAPH or SIGGRAPH Asia according to the authors' choice. The papers are not in a separate TOG paper session; they are interleaved in the same sessions. The current TOG Editor-in-Chief is Marc Alexa. He is happy to discuss this issue further. Marc presented acceptance rates at the Associate Editor lunch I attended one month ago. For "Previously Unpublished Research Papers", the acceptance rate was 20% in 2017 and 24% in 2018.

**Comment by jrk** [comment]
This is an old issue, but it really is not representative of the graphics community for TOG to be excluded. It is and long has been tightly integrated into the overall SIGGRAPH process as a co-equal publication and presentation path, just with a rolling deadline and journal reviewing process. It would be especially non-representative of the field to include the new conference track (as suggested, appropriately, in #6858 ) but exclude TOG papers.

**Comment by musialski-lab** [comment]
@jrk The discussion about including TOG-only papers is another one than the discussion of fixing the code to include **SIGGRAPH CONFERENCE-TRACK** papers: https://github.com/emeryberger/CSrankings/issues/6858
