### ISSUE TITLE
Stephen Alstrup missing article

### ISSUE THREAD

**Issue by stephenalstrup** [emeryberger/CSrankings#2612]
I have two SIGIR 2019 articles 
https://dblp.uni-trier.de/pers/hd/a/Alstrup:Stephen
Butt only one is included in csrankings
http://csrankings.org/#/fromyear/2019/toyear/2019/index?none&europe
How I get the bug fixed?

**Comment by emeryberger** [comment]
Feature, not a bug. Papers need to be at least 6 pages long to be included.

**Comment by stephenalstrup** [comment]
Ah. Thanks for clarifying.

**Comment by emeryberger** [comment]
No worries. FWIW, it's in the [FAQ](http://csrankings.org/faq.html).

> Note that publications must be at least 6 pages long to be counted.
