### ISSUE TITLE
publication data is not correct for University of Amsterdam

### ISSUE THREAD

**Issue by ZhengyuZhao** [emeryberger/CSrankings#2627]
I added some researchers from the University of Amsterdam, and I can see them in the ranking now.
But when I checked the results randomly, I found one data discrepancy.
For the researcher Cees Snoek, the ranking shows only 3 papers in CV (cvpr,iccv, and eccv), but the DBLP shows he had 20+ publications (full papers) in these three venues.\

Could you please help me figure out what happened here? Thanks!

**Comment by emeryberger** [comment]
You need to add aliases to `dblp-aliases.csv` and entries for all possible variants of an author's name given in DBLP. I went ahead and did that for this particular author.

**Comment by ZhengyuZhao** [comment]
> You need to add aliases to `dblp-aliases.csv` and entries for all possible variants of an author's name given in DBLP. I went ahead and did that for this particular author.

Got it! Thanks!
