### ISSUE TITLE
Multiple non-US colleges appear in the US college ranking

### ISSUE THREAD

**Issue by quz105** [emeryberger/CSrankings#2658]
Just name a few examples:

61 Beihang University
76 University of Haifa
76 University of Helsinki
110 Heriot-Watt University

![Screen Shot 2020-05-11 at 11 38 55 AM](https://user-images.githubusercontent.com/5768229/81580888-00fc8b80-937c-11ea-93be-5f8365acff5c.png)

**Comment by emeryberger** [comment]
Fixed (somehow line-endings got messed up by someone else's commit; also I fixed a couple of entries). Thanks!
