### ISSUE TITLE
Bioinformatics/Computational Biology Publication Count Inquiry

### ISSUE THREAD

**Issue by amorehead** [emeryberger/CSrankings#2706]
Hello. I have a question about a potential stale data source issue that may be affecting rankings for an entire area.

I noticed that when deselecting all areas and then selecting only the bioinformatics/computational biology track many of the publication counts are (possibly due to user misinterpretation) not correct/up-to-date. I am not sure if this is an issue with the application view not properly updating according to the filters or instead with the DBLP data at large (at least for this specific subfield). What appears to be the issue is that ISMB (ISCB) publications are not being counted consistently. For example, looking at the DBLP entry for Pierre Baldi, I count 2 publications from 2015-2020 at least six pages long in Bioinformatics (the official journal of ISCB/ISMB), whereas CS Rankings reports 1.

Would anyone happen to have any ideas about what might be going on here? Or if I am just misunderstanding the criteria for counting an ISMB publication? For reference, here are the parameters with which I am running CS Rankings followed by Pierre Baldi's DBLP entry. Thank you in advance for your time and clarification.

![image](https://user-images.githubusercontent.com/7051982/83467422-7a4d4280-a43f-11ea-8df3-cc016ff4e21b.png)

![image](https://user-images.githubusercontent.com/7051982/83467505-b680a300-a43f-11ea-8b51-f61aecdd3524.png)

![image](https://user-images.githubusercontent.com/7051982/83467538-cef0bd80-a43f-11ea-8d5a-887a52cecacd.png)

**Comment by amorehead** [comment]
Does anyone have any ideas as to what may be going on? This may have to do with the rules behind how DBLP itself associates certain publications with ISMB (rather than simply the journal "Bioinformatics").

**Comment by emeryberger** [comment]
ISMB papers are distinguished from ordinary Bioinformatics pubs by their volume & number. This logic is in `util/csrankings.py`.

    # ISMB proceedings are published as special issues of Bioinformatics.
    # Here is the list.
    ISMB_Bioinformatics = {2019: (35, 14),
                       2018: (34, 13),
                       2017: (33, 14),
                       2016: (32, 12),
                       2015: (31, 12),
                       2014: (30, 12),
                       2013: (29, 13),
                       2012: (28, 12),
                       2011: (27, 13),
                       2010: (26, 12),
                       2009: (25, 12),
                       2008: (24, 13),
                       2007: (23, 13)
                       }

**Comment by amorehead** [comment]
Thank you for the clarification!
