### ISSUE TITLE
Pravesh Kothari ADD

### ISSUE THREAD

**Issue by praveshkkothari** [emeryberger/CSrankings#2710]
**Please indicate whether this is an addition, deletion, or modification**
- [x] Addition
- [ ] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._
Pravesh Kothari 
https://dblp.org/pid/47/7934

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.
Pravesh K Kothari

**Update/add an affiliation**
List the new affiliation, and the old affiliation (if already in CSRankings). Please point to a web page (preferably institutional/departmental, but personal is OK), a LinkedIn site, or similar. If a faculty member has moved to industry, retired, or for other reasons departed academia, please indicate this here.
Carnegie Mellon University
https://www.cs.cmu.edu/~praveshk/

**Update/add a home page**
Enter the full home page below. Please test it to make sure it is correct.
https://www.cs.cmu.edu/~praveshk/

**Update/add a Google Scholar page.**
Please include a link to the faculty member's [Google Scholar](https://scholar.google.com) page. If none exists, please put "NOSCHOLARPAGE".
https://scholar.google.com/citations?user=07qshUgAAAAJ&hl=en

**Comment by radhikasethi2011** [comment]
@praveshkkothari sir, if you could please edit your message and make it` [x]`, as `[ x] and [x ]` don't work in crossing the checkbox :)

**Comment by praveshkkothari** [comment]
Submitted a pull request for the same change.

**Comment by praveshkkothari** [comment]
thanks for catching this, Radhika. I actually sent in a pull request so
closed this issue.

**Comment by radhikasethi2011** [comment]
No problem sir! That's great.
