### ISSUE TITLE
Manish Gupta (UPDATE)

### ISSUE THREAD

**Issue by shrisharao** [emeryberger/CSrankings#2808]
**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition
- [ ] Deletion
- [*] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [*] Make sure that any faculty you add meet the inclusion

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._

Manish Gupta 0001

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

**Update/add an affiliation**

Microsoft Research
HE IS NOT PART OF IIIT BANGALORE -- see https://www.linkedin.com/in/manishsgupta/

**Update/add a home page**

https://www.microsoft.com/en-us/research/people/gmanish/

**Update/add a Google Scholar page.**

https://scholar.google.co.in/citations?user=eX9PSu0AAAAJ

**Comment by shrisharao** [comment]
This item has evidently not been completed.  The wrong person is still
listed with the affiliation.

**Comment by emeryberger** [comment]
I deleted all old issues; please re-submit as a PR. Thanks!
