### ISSUE TITLE
bug report on ranking

### ISSUE THREAD

**Issue by jelasity** [emeryberger/CSrankings#2821]
At csrankigs.org, when I click on "All areas off", then "AI on" then the resulting values that the ranking is based on suddenly become something other than a geometric mean of the [adjusted count +1]. For example, CMU has value 61.6 at the first position yet the best adjusted count among faculty is 39.7. Obviously, the correct geometric mean is guaranteed to be smaller than 40.7, yet 61.6 is shown.  At the lower end of the list the problem is the opposite, the value is lower than it should be it seems.

The problem is there in other listings too; it is advisable to play with the area and filed settings and see what happens. But fixing the above could fix the other cases too.

**Comment by emeryberger** [comment]
This is not how the geometric mean computation works; it's a geometric mean _across areas_, not _across faculty_ (which would not make sense in terms of adjusting for different area sizes / rates of publication).
