### ISSUE TITLE
ASPLOS/HPCA

### ISSUE THREAD

**Issue by adwaitjog** [emeryberger/CSrankings#288]
Thanks for this great website!

I am curious about the logic behind putting ASPLOS in the computer architecture category. ASPLOS is known to be multidisciplinary spanning computer architecture and hardware, programming languages and compilers, operating systems and networking (as per their CFPs).  Given there is a limit of three conferences per category, in my opinion, HPCA seems to be a better fit for Computer Architecture /only/ category.

**Comment by emeryberger** [comment]
This is the result of a survey conducted of members of the ISCA PC (not shown is PACT, which was quite a bit lower than the others).

![screen shot 2017-04-19 at 5 41 01 pm](https://cloud.githubusercontent.com/assets/1612723/25203503/78a6b4d8-2527-11e7-8768-77f9c502e2bc.png)

See also: https://www.facebook.com/EmeryBerger/posts/10104259343558252
