### ISSUE TITLE
Please include quantum computing as a subcategory

### ISSUE THREAD

**Issue by soumikghosh23** [emeryberger/CSrankings#3002]
There are many schools that have specialized quantum computing programs, like UWaterloo and UChicago, which will get a large boost in rankings if quantum computing is included as a subcategory and top quantum conferences are counted for citations.

**Comment by 1ethanhansen** [comment]
I'll second this request, it would be much appreciated. Quantum Computing and Quantum Information as a sub-category would provide a good deal of benefit I think

**Comment by zxcvbn97** [comment]
Reopening this as I dont see Quantum yet. IEEE QuantumWeek is a top venue: https://qce.quantum.ieee.org/2025/

**Comment by emeryberger** [comment]
Quantum-related papers appear in numerous mainstream venues. As of today, quantum-specific conferences remain largely unindexed by organizations like CORE.

<img width="1240" alt="Image" src="https://github.com/user-attachments/assets/cecee978-4e4e-4474-a4ae-128282170110" />
