### ISSUE TITLE
Dash "-" versus "at" in the name of university 

### ISSUE THREAD

**Issue by Tizpaz** [emeryberger/CSrankings#3035]
Hi,
There is an issue with the name of University. I used University of Texas at El Paso in my csranking update, but later I found out that the existing name is University of Texas - El Paso. I was wondering if you can update the name from "at" to "-"?
Thank you!

_Originally posted by @Tizpaz in https://github.com/emeryberger/CSrankings/pull/2887#issuecomment-711080918_

**Comment by emeryberger** [comment]
Done.
