### ISSUE TITLE
Erroneous data about PL publications for security researchers

### ISSUE THREAD

**Issue by drdreyer** [emeryberger/CSrankings#3116]
I was just using CSrankings today to look at PL authors, and discovered that a bunch of the information about # of PL publications for certain researchers (particularly in security) appears to be bogus.  

In particular, I observed the following information when restricting the search to "the world", "from 2000 to 2020", and "programming languages".  Under these search criteria, CSrankings claims that:

- Ian Goldberg (Waterloo) has 20 PL papers!!!
- N. Asokan (Waterloo) has 4 PL papers
- Florian Kerschbaum (Waterloo) has 4 PL papers
- Lorrie Cranor (CMU) has 4 PL papers
- Urs Hengartner (Waterloo) has 3 PL papers
- Vitaly Shmatikov (Cornell Tech) has 3 PL papers
...and many more...

AFAICT, none of these authors have any PLDI or POPL papers.

**Comment by emeryberger** [comment]
Thanks! This bug was inadvertently introduced in https://github.com/emeryberger/CSrankings/commit/e7f6af1a0f2fd7728badb6ec7a6bb6e636413cda and should now be fixed.

**Comment by emeryberger** [comment]
(on a side note, Vitaly has 1 PLDI paper :).

**Comment by drdreyer** [comment]
Great, thanks!
