### ISSUE TITLE
David Bernhard DELETE

### ISSUE THREAD

**Issue by bristol-d** [emeryberger/CSrankings#3155]
**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition
- [X] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._

David Bernhard

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

This is a request to DELETE the entry for David Bernhard, University of Bristol including the link to the home page as the academic involved not longer meets the requirements (does not do research or supervise PhD students).

**Comment by emeryberger** [comment]
Is this a change in position? (For example, if a faculty member is not _currently_ supervising PhD students in CS but still _can_ solely advise them, they should still be included.)

**Comment by bristol-d** [comment]
Yes, he's been in a non research position for a couple of years now.

**Comment by bristol-d** [comment]
Happy New Year!

Can someone please action this?

**Comment by emeryberger** [comment]
Done.
