### ISSUE TITLE
Constraint on papers being at least 6 pages long

### ISSUE THREAD

**Issue by dishuk13** [emeryberger/CSrankings#316]
@emeryberger Can you explain why this specific constraint is in place ? 

Since we are already considering extremely selective venues, chances of trivial papers being counted are already eliminated. I cannot see how this would help more.

**Comment by emeryberger** [comment]
Conference proceedings often include things like keynotes, posters, and demos, which are all shorter than normal papers. These are generally captured by this page limit.
