### ISSUE TITLE
University of Göttingen is listed in Canadian list

### ISSUE THREAD

**Issue by kurshakuz** [emeryberger/CSrankings#3188]
Hello, guys!

I have been going through universities in Canada, and noticed that for some reason University of Göttingen is listed there as well alongside Canadian flag. Please have a look at the attached screenshot.

![image](https://user-images.githubusercontent.com/28868430/103506733-a9211080-4e87-11eb-8072-11b775300048.png)

**Comment by emeryberger** [comment]
Thanks for the report!
