### ISSUE TITLE
Jingdong Chen (DELETE) 

### ISSUE THREAD

**Issue by reasonW** [emeryberger/CSrankings#3205]
**DEPRECATED: PLEASE OPEN A PULL REQUEST INSTEAD**

**Please indicate whether this is an addition, deletion, or modification**
- [ ] Addition
- [x] Deletion
- [ ] Modification

**Please check the box below to indicate that you have read the inclusion criteria.**
- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Enter the faculty member's name *AS LISTED IN [DBLP](http://dblp.org)*, including disambiguation suffixes like 0001 as needed, as in _Joe Shmoe 0001_.**
_If the faculty entry is currently ambiguous, send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by the faculty member in question._
Jingdong Chen

**Enter any aliases (multiple entries) given in DBLP.**
If DBLP has multiple entries for this person, all of them need to be listed.

This is a request to DELETE the entry for Jingdong Chen, Northwestern Polytechnical University including the link to the home page as the academic involved does not meet the requirements (does supervise CS or similar PhD students).

**Comment by emeryberger** [comment]
Done.
