### ISSUE TITLE
Inconvenient first line of generated-author-info.csv

### ISSUE THREAD

**Issue by swapsha96** [emeryberger/CSrankings#326]
When line [#498](https://github.com/emeryberger/CSrankings/blob/gh-pages/util/regenerate-data.py#L498) of regenerate-data.py is executed, it adds  

> "name","dept","area","count","adjustedcount","year"

 instead of 

> name,dept,area,count,adjustedcount,year

in _generated-author-info.csv_. This creates a problem when I try to load and convert CSV to dictionary in Python using
```python
with open('country-info.csv') as csvfile:
    reader = csv.DictReader(csvfile)
```

**Comment by emeryberger** [comment]
Works for me. Also, github requires these double-quoted headers.
