### ISSUE TITLE
couldn't find the information on http://csrankings.org

### ISSUE THREAD

**Issue by ZevXie** [emeryberger/CSrankings#3303]
**DO NOT USE ISSUES TO UPDATE ENTRIES: EDIT THE APPROPRIATE FILES (`csrankings-[0-9].csv`) AND OPEN A PULL REQUEST INSTEAD**

Hello, professor, I found I couldn't find the information on http://csrankings.org, but the information in csrankings-9.csv had been updated.

The details are as follows：
 Xizhao Wang,Shenzhen University,http://csse.szu.edu.cn/cn/peopled297.html?98400,NyLTM0wAAAAJ
 

best wishes.

**Comment by adityamwagh** [comment]
It takes time to build the website. Your change will reflect in a couple of days.

If the pull request has been merged, your change will reflect in due time.

**Comment by emeryberger** [comment]
Correct - I batch updates, and the site gets updated at least monthly (this is indicated on the web page).
