### ISSUE TITLE
Incorrect average count for the department

### ISSUE THREAD

**Issue by taejunham** [emeryberger/CSrankings#333]
If I understood it correctly, an average count for the department should match to the (sum of Adjusted #s for faculties in department +1) when a single area is selected. 

It seems like there are several cases where this does not hold true.  

Also, one potentailly relevant issue for this is that entries for some faculties have wrong raw publication counts value shown while an associated pie chart displays the correct number of publications. For example, S.Matthew Weinberg in Princeton entry displays 18 raw publications but its pie chart shows 14 publications.

**Comment by emeryberger** [comment]
Thanks for your report. this should be fixed.
