### ISSUE TITLE
Publication length: length filter

### ISSUE THREAD

**Issue by lintool** [emeryberger/CSrankings#3461]
According to the FAQ: http://csrankings.org/faq.html

>Note that publications must be at least 6 pages long to be counted.

This has the effect of, for example, removing _all_ short papers from ACL/EMNLP/NAACL. Short papers have acceptance rates that are comparable or even lower than full papers at these venues.

See (incomplete) data here:
https://aclweb.org/aclwiki/Conference_acceptance_rates

Has this issue been raised/discussed before?

**Comment by tukw** [comment]
#852
