### ISSUE TITLE
New Member Doesn't Show Up Under the Institute After Merge

### ISSUE THREAD

**Issue by xinpl** [emeryberger/CSrankings#3469]
Hi,

I created a pull request a few days ago to add 5 new faculty members at Peking University. It was successfully merged:
https://github.com/emeryberger/CSrankings/pull/3450

However, if I check the website (csrankings.org), one of the new faculty members, Hao Dong 0003, is not displayed under Peking University. I waited for a few days but it remained the same.

According to DBLP, Hao has published at top CS conference like NeurIPS, ICCV, ECCV:
https://dblp.org/pid/14/1525-3.html

Could someone please help me with this?

Thanks,
Xin

**Comment by adityamwagh** [comment]
Hi.

This change should reflect on the next build. Merging the changes doesn't mean that the changes will reflect right away. This is a very big project and takes time to build. Moreover, it's built monthly. So please be patient. Your changes will reflect in due time.

**Comment by xinpl** [comment]
Thanks for the clarification. It was a bit confusing as part of the changes were reflected. I guess I will wait and see :)
