### ISSUE TITLE
Add professors of HITsz and HITwh to HIT(Harbin Institute of Technology)

### ISSUE THREAD

**Issue by 12z34x** [emeryberger/CSrankings#3480]
Dear editor,
  I find that many professors in HITsz and HITwh are not included in HIT(Harbin Institute of Technology). Because, HIT has three schools in China and they make research together. So, I think you need to add these teachers from the two schools into HIT.

**Comment by adityamwagh** [comment]
Hi.

You can open a pull request with the suggested changes, We can then merge it in the main branch.

**Comment by 12z34x** [comment]
Thank you for your reply and your contributions to the CSranking. 👍 I opened a pull request recently. I add many professors in CS of HITsz into HIT. And other professors (in CS of HITwh) will be updated later. Please check my pull request and update the CSranking~ I can't wait to see the updated results~ :)

**Comment by 12z34x** [comment]
@adityamwagh Hi, I have pull a request https://github.com/emeryberger/CSrankings/pull/3711#issue-698361542. Could you check and merge is in your spare time?

**Comment by adityamwagh** [comment]
@12z34x Please contact @emeryberger. I am just a contributor to the project. Emery manages the pull requests.
