### ISSUE TITLE
More statistics and citations

### ISSUE THREAD

**Issue by gannimo** [emeryberger/CSrankings#35]
Show standard deviation, optionally including folks in the department that did not contribute (i.e., a dead meat meter). Maybe add some other funky statistics and data like citations as well. Adding citations would involve downloading papers and parsing citations (this might be hard and involve quite some scripting).

**Comment by emeryberger** [comment]
Standard deviation of what exactly?

**Comment by gannimo** [comment]
Across all professors in the department on the per-department summary screen. I'd like to see the homogeneity of the department/variance between professors. It could also be interesting to pull out cliques/if faculty in the department are working together.

**Comment by emeryberger** [comment]
Statistics across different areas don't make sense because of the different publication rates (and selectivities) of different areas. Cliques, etc. would be interesting to display for sure -- not clear that it makes sense in this context, though.
