### ISSUE TITLE
Professors in ECE Departments

### ISSUE THREAD

**Issue by meghbhalerao** [emeryberger/CSrankings#3508]
**DO NOT USE ISSUES TO UPDATE ENTRIES: EDIT THE APPROPRIATE FILES (`csrankings-[0-9].csv`) AND OPEN A PULL REQUEST INSTEAD**

Dear Author,
Thank you for making the csrankings website. It is very helpful.
Lot of professors from the ECE Department also work in the related areas, especially ML and AI, but their names do not seem to be listed. Is this to be done via a PR? Or is the page very specific to only CS?
Thanks again,
Megh

**Comment by 94rain** [comment]
Faculty not in a CS department or similar who can advise PhD students in CS can be included regardless of their home department. (See [Contributing to CSrankings](https://github.com/emeryberger/CSrankings/blob/gh-pages/CONTRIBUTING.md))

**Comment by canertol** [comment]
My commit is rejected because of that, although we work on Computer Security.

https://github.com/emeryberger/CSrankings/pull/3989#issuecomment-953311231

**Comment by EtoDemerzel0427** [comment]
Share the same thoughts. If this ranking is served to help CS students, as generally CS students would also take a look at the ECE department,  it should definitely be included; if it is to compare the CS research levels of each school, it's even simpler: as long as you are doing CS research, you should be included!

Specifically, at my college, UT-Austin, most faculty in CompArch, AI, software engineering, are under the ECE department, it's not fair to ignore them in CS Rankings.

**Comment by meghbhalerao** [comment]
Yes, for example look at Prof. Atlas Wang from UT ECE. He is not there in csrankings under UT. He publishes large volumes in top ML conferences.
