### ISSUE TITLE
Add ICLR ?

### ISSUE THREAD

**Issue by hijkzzz** [emeryberger/CSrankings#3518]
**DO NOT USE ISSUES TO UPDATE ENTRIES: EDIT THE APPROPRIATE FILES (`csrankings-[0-9].csv`) AND OPEN A PULL REQUEST INSTEAD**

In the AI field, it seems that papers on ICLR will be of higher quality than those on AAAI and IJCAI.

**Comment by shihaoji** [comment]
I can't agree more. ICLR has a similar bar as NeuroIPS and ICML. I highly recommend to add ICLR in the list.

**Comment by diningphil** [comment]
Same here, it would be appropriate to add ICLR to the list. It's even ranked 10th in the latest Google Scholar Top Publication list: https://scholar.google.com/citations?view_op=top_venues

What do you think @emeryberger ?
Thanks for your effort!

**Comment by yhn112** [comment]
I'd like to agree with the others here. ICLR is at least as good as ICML.
Also, as one more argument, it was recently [ranked](http://portal.core.edu.au/conf-ranks/2273/) CORE A*.
