### ISSUE TITLE
How to count faculty

### ISSUE THREAD

**Issue by andrewcmyers** [emeryberger/CSrankings#362]
My understanding is that currently when counting the number of faculty in a particular area or areas, anyone who has published a paper in that area over the designated time period counts as 1 faculty member in that area. This seems misleading: if I publish in 8 areas (as it turns out I have), I am making my institution look like it generates less output per faculty member in each of those areas.

I suggest that a faculty member should count as participating in a particular set of areas proportional to the fraction of their publication output that is in those areas. So if half of my publications are in PL, then I would count as 0.5 faculty for the purpose of figuring out how many PL faculty there are at Cornell. At least, this way of counting faculty seems like a useful statistic that could be presented along with the current faculty count, if not replacing it.

**Comment by emeryberger** [comment]
I think this is too complex for a variety of reasons (both from an implementation standpoint and a comprehensibility standpoint). I have considered simply not reporting the number of faculty, thus requiring people to click on the triangle to see the breakdown.

**Comment by emeryberger** [comment]
Any feedback on the above?

**Comment by andrewcmyers** [comment]
Reporting no number doesn't seem like an improvement to me. I think users need more data, not less.

I can't speak to the implementation challenges, but what about reporting the average percentage participation, e.g. something like 8 (75%) to indicate that there are 8 faculty but they are actually only sending 75% of their work to the areas in question.

**Comment by emeryberger** [comment]
Doable, but doesn't this implicitly hurt faculty who are eclectic or work at the boundaries of two (or more) areas? Also, people can already click on faculty profiles (the little pie charts) to see where they publish. (If you weren't aware of this, let me know!)

**Comment by emeryberger** [comment]
I should note that right now, the pie charts are updated with the number of pubs in the areas selected. That seemed logical but perhaps it would make more sense to have them be invariant and always reflect their overall publication profile.

**Comment by andrewcmyers** [comment]
Yes, I know about the pie charts. My own pie chart has a lot of little segments! I like the idea of having them be invariant -- filtering the pie charts can be misleading and doesn't add much value.

Why does it hurt faculty who work at the boundaries? You are concerned that schools will look less strong in one area if the people in that area do a lot of work that appears in external venues? But is that unfair? The pie chart shows me as something like 40% PL. That seems not far off base. At the same time, it does seem useful to show the total number of faculty who COULD work in the area based on past performance.

**Comment by emeryberger** [comment]
The counting thing is complicated. Percentages are tricky because of differing publication rates. I worry that this may be optimizing for corner cases anyway (since it appears that many, many researchers work almost entirely in one or two areas).

Let's talk about pie charts; I think this is easier to resolve. Making the pie chart invariant for faculty makes sense. What about for institutions? Right now, if you just select areas A and B, you then see the weight of publications by all faculty in just those areas. Change or leave as is?

**Comment by andrewcmyers** [comment]
I think I would just not filter pie charts at all. I don't see the point of it.

**Comment by emeryberger** [comment]
Agreed. Pie charts now invariant (see https://github.com/emeryberger/CSrankings/commit/d649cd4254a2fb37b30eb85f51a1d1243ac1701c).

**Comment by emeryberger** [comment]
Since pie charts now contain all the information about each faculty member regardless of area (so users can easily see how much of a "PL" person someone is, for example), closing.
