### ISSUE TITLE
Add ICWSM to "Web & Information Retrieval"

### ISSUE THREAD

**Issue by emidec** [emeryberger/CSrankings#366]
There are only two venues in the Web & Information retrieval category already: WWW and SIGIR.
Most categories have three conferences and anyway ICWSM (http://dblp.uni-trier.de/db/conf/icwsm/index.html) is arguably at least as strong a venue as SIGIR. In fact, it has higher h5-index (51 vs 50) and h5-median (93 vs 66) than SIGIR according to Google scholar -- see https://scholar.google.co.uk/citations?view_op=top_venues&hl=en&vq=eng_databasesinformationsystems

**Comment by yangzhangalmo** [comment]
I support adding ICWSM as part of the csrankings.org's conference list, it's the best conference on social network mining and it is still growing very fast.

**Comment by gianlucasb** [comment]
I agree that ICWSM is a top conference and should be added to CSrankings, even more so since the Web & IR category only has two conferences listed so far.

**Comment by emeryberger** [comment]
For what it's worth, all listed conferences need to form a single equivalence class. I would appreciate seeing the acceptance rate and conference size (# of submissions) stats.

**Comment by emidec** [comment]
ICWSM'13: 72/349 (21%)
ICWSM'14: 64/279 (23%)
ICWSM'15: 64/337 (19%)
ICWSM'16: 52/306 (17%)
ICWSM'17: 50/372 (13%)  

Sources: 
https://www.aaai.org/ocs/index.php/ICWSM/ICWSM13/paper/view/7309/6409
https://www.aaai.org/Press/Proceedings/icwsm14.php
https://www.aaai.org/Press/Proceedings/icwsm15.php
https://www.aaai.org/Press/Proceedings/icwsm16.php
https://www.aaai.org/Press/Proceedings/icwsm17.php

**Comment by emidec** [comment]
And here are SIGIR acceptance rates:
SIGIR '12	483	98	20%
SIGIR '13	366	73	20%
SIGIR '14	387	82	21%
SIGIR '15	351	70	20%
SIGIR '16	341	62	18%

Source: http://dl.acm.org/citation.cfm?id=2009916 (click on "Publication")

**Comment by ravenben** [comment]
I would agree.
Having served as PC chair for WWW (2016), I think ICWSM's level of selectivity and quality is at least on par with that of WWW tracks. In computational social science and the broader intersection of CS and social science, ICWSM is significantly more selective than the alternatives, and very much the premier venue.  I think adding ICWSM would be very much justified, and in addition, it would help address some of the lack of representation for top interdisciplinary conferences.

It's also worth noting that ICWSM is also highly regarded as a sister-like conference to CHI, with many of the top HCI people submitting there.

**Comment by worst** [comment]
I made the initial pull request to add ICWSM (sorry about that; I thought I had seen previously you wanted those as pull requests).

Obviously I agree with everyone here.

Just as an additional comparison, here is WWW's acceptance rates.

WWW '13 831/125 15%
WWW '14 645/84  13%
WWW '15 929/131 14%
WWW '16 727/115 16%
WWW '17 966/164 17%

From http://dl.acm.org/citation.cfm?id=2566486 (click on "Publication" tab at the bottom)

Perhaps important to note that WWW is >= 2x the size of ICWSM, but it's multi track, while ICWSM is single track.

**Comment by thang-dinh** [comment]
I'd like to bring up another top conference in the same category. IMHO, both ICWSM and WSDM deserve the place, and, it's tough to choose between them.

ACM WSDM 
h-index: WSDM: 54, vs. ICWSM: 51, SIGIR: 50;  
h5-median: WSDM: 89 vs. ICWSM: 93, SIGIR: 66;
[Google Scholar](https://scholar.google.co.uk/citations?view_op=top_venues&hl=en&vq=eng_databasesinformationsystems)

Acceptance rate: 
WSDM '13 | 387 | 73 | 19%
WSDM '14 | 355 | 64 | 18%
WSDM '15 | 238 | 39 | 16%
WSDM '16 | 368 | 67 | 18%
WSDM '17 | 505 | 80 | 16%
[ACM](http://dl.acm.org/citation.cfm?id=2684822&picked=prox) (Click on "Publication" tab)

**Comment by emidec** [comment]
hi there, is there any updates re. this issue? thank you

**Comment by fycus-tree** [comment]
@emeryberger 
In light of the Medical Imaging (#558) & Computer Networking (#586) discussions, it also seems fair to revisit this one, which seems well-founded

**Comment by ravenben** [comment]
hey Emery.
Just wondering if there's a current survey underway regarding ICWSM as well.
Let me know if I can help in any way.
thanks!!
Ben

**Comment by msirivia** [comment]
Dear Emery,

Bringing  Ben's question back: Is there a survey for ICWSM in the works?

Cheers,
Michael

**Comment by gianlucasb** [comment]
As an update on this the 2018 acceptance rate for ICWSM is 16% (48/295)

**Comment by shoumikchow** [comment]
Think this should be revisited.

**Comment by gianlucasb** [comment]
According to the most recent Google Scholar Metrics, both ICWSM and WSDM are ranked higher than SIGIR:

https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_databasesinformationsystems

I think that the ranking in the area of Web and IR should be revisited.

**Comment by ravenben** [comment]
I  personally think the case for ICWSM is stronger, because it represents a significant shift of data mining in recent years towards partial overlap with computational social science, and CSRankings’ only potential weakness is a lack of representation in interdisciplinary areas like computational social science.

WSDM is well regarded, but I think it overlaps almost entirely with KDD, and one would argue that KDD is strictly more selective and highly regarded of the pair.

Ben
—
Ben Y. Zhao http://people.cs.uchicago.edu/~ravenben
Neubauer Professor of Computer Science, University of Chicago
PGP Key ID 0907015B

**Comment by bowlinearl** [comment]
Happy 2019! Any movement on this issue? 100% agree with Ben that interdisciplinary work remains a bit of weak spot for CSRankings, and ICWSM is the top venue for computational social science. This year ICWSM is shifting to a rolling deadline model, which I think speaks to the quality of the community, i.e. that they have the dedication to manage a rolling process (it takes a lot of work!) and that there is sufficient high-quality work being submitted to justify the change.

**Comment by emidec** [comment]
Fully agree with Christo. Another option could be creating a computational social science entry in the "Interdisciplinary Areas"? Although considering that "The Web & information retrieval" has only two conferences, probably ICWSM belongs in there anyway.

**Comment by worst** [comment]
Still only 2 venues in Web and IR with seemingly no justification...

**Comment by emeryberger** [comment]
Sure, you know, no justification apart from the justification of having an actual full-time job... :)

Anyway, the methodological challenge here remains. I need to know whom to survey.

**Comment by emidec** [comment]
I'd be happy to help suggesting whom to survey -- I guess it'd need to be people publishing in Web?

**Comment by emeryberger** [comment]
I need a list of indisputably top venues (which can be a challenge) and their program committee members' e-mails (send them to me directly), preferably from the last two years.

**Comment by emidec** [comment]
Thanks Emery. You mean top venues overall, or top venues in Web & IR? If the latter, I guess it would be the current conferences (WWW and SIGIR) plus perhaps the ones people have been discussing (ICWSM, WSDM)? WWW is huge but I could try to ask the chairs if they'd be willing to extract the emails from Easychair and send them to you.
