### ISSUE TITLE
consider adding another AI venue

### ISSUE THREAD

**Issue by emeryberger** [emeryberger/CSrankings#37]
There are currently two, so there is room for one more. Proposed candidates include AAMAS, ICAPS, KR, UAI, SOCS, CP.

**Comment by brendano** [comment]
UAI is more like machine learning (at least these days? or is it all changing again?)

**Comment by emeryberger** [comment]
I gathered the numbers for UAI and it is not in the same equivalence class as the other two by selectivity or number of submissions (consistently >30% acceptance rate).

**Comment by vjmenon** [comment]
AAMAS is quite a big conference and I see that the acceptance rates (as listed here - http://www.adaptivebox.net/CILib/CICON_stat.html) are consistently below 25%.

**Comment by emeryberger** [comment]
I also consider size (# of submissions) and impact factors. AAMAS and UAI are not in the same equivalence class as IJACI and AAAI -- those conferences are 5x to 6x larger (by # of submissions).

IJCAI '16: 2294 papers submitted, 551 accepted (24%)
(see http://www.ijcai.org/Proceedings/16/Papers/001.pdf)

AAAI '17:  2590 submissions, 638 accepted (25%)

AAMAS '16: 411 submissions, 109 accepted (25%)
http://www.ifaamas.org/Proceedings/aamas2016/pdfs/welcome.pdf

UAI '16: 275 submissions, 85 accepted (30%)
http://auai.org/uai2016/proceedings/uai-2016-proceedings.pdf
