### ISSUE TITLE
One paper for two professors in the same school will count twice, which makes the scores unreasonable, the school will get higher scores

### ISSUE THREAD

**Issue by 12z34x** [emeryberger/CSrankings#3706]
If two professors publish the same paper, both of them will get the score. And if they are from the same school, the school will have double score for only one paper. For example, professor Xiaodan Liang and Liang Lin from Sun Yat-sen University in China share many papers. So the Sun Yat-sen University has a very high but unreasonable scores. And it is not fair for other schools! So could you make the sum of scores of multiple professors from the same paper is 1.0? And multiple professors from this paper will divide the score.(If one professor is the first author or corresponding author, he will get higher score).

**Comment by marcniethammer** [comment]
This is already the case. As far as I recall the score you get is 1 divided by the number of authors. This addresses your concern, though it raises some other concerns with regards to student co-authors and authors from different fields (that are not in csrankings).

**Comment by 12z34x** [comment]
Firstly, thanks for your reply.
OK, I know this is a complex problem. But many professors just "put their name" on the author list of papers without other help. And then, it causes two unfair cases.
1. It is unfair for the professor who is the **first** author or **corresponding** author.  This two kinds of authors have higher contribution to the paper, but get the same score as other authors. They should have gotten higher score. 
2. It is unfair to the University. For example, one paper has four author, and the **first** author and the **corresponding** author are both from university **A**. The **second** and **third** author are both from university **B**. As your rule, the university **A** can only get 0.5 score as **same** as **B**. But the authors from university A may have almost **0.8** contribution to the paper. 
  And the situation is even worse when the whole paper is from **company**. Some professors are the staff of some companies before they join in their universities. And they can enjoy the high weighted score from the papers published by their colleagues. And then, their university can get high weighted score( like a gift) from these companies.
I know it is hard to make an absolutely fair rule. Maybe it is not possible to rectify in a few days or weeks. But the idea is well worth considering.
