### ISSUE TITLE
Add DATE (Design Automation and Test in Europe) to Design Automation

### ISSUE THREAD

**Issue by xsharonhu** [emeryberger/CSrankings#3718]
DATE is one of the two largest conferences (the other is DAC) in the design automation area. Its quality is comparable to DAC and ICCAD which are the two conferences included in the CSRankings for the design automation area. 

It has been petitioned that DATE should be included together with DAC and ICCAD. See "Design Automation: Add DATE to the list #1312". But it seems that the issue was closed without a result. On Nov. 28m 2919, Prof. Berger wrote that a survey would be conducted. It would be great to get an update on the survey result.

As the past chair of ACM SIGDA and a past DAC chair, I would be happy to help with the survey effort if needed.

@emeryberger Thank you for all your effort!

**Comment by janadoppa** [comment]
Thanks @xsharonhu for following up on this important topic.

@emeryberger: Prof. Berger, can you please update us about the status of this planned survey to include DATE as the third conference for the Design Automation area? Sharon is the past ACM SIGDA chair and she will be able to help including coordinating any discussion with the new SIGDA chair.

**Comment by jamy54** [comment]
What's is the update on adding DATE?

**Comment by kiwih** [comment]
Hi, I am also interested to know why DATE is not included, particularly as other domains have "top 3" venues on csrankings.
