### ISSUE TITLE
How often will you merge these requests and update the ranking?

### ISSUE THREAD

**Issue by 12z34x** [emeryberger/CSrankings#3719]
How often will you merge these requests and update the ranking? If the requests are not valid, how long and how I will know that?

**Comment by staeiou** [comment]
It is a very tedious task and I empathize with @emeryberger on the flood of requests! But maybe some of us can help out with the verification? I'd be willing to help clear the backlog, with many hands makes light work.

**Comment by 12z34x** [comment]
Thanks for your kindness~ Because I have updated almost 80 professors in open request #3711. And I am worried about one possible case —— "if there is only one invalid professor, the whole request will be rejected, without telling me which professor is invalid." So, I don't know if this case will happen, because I do not know the update rule clearly. 
I am not worried about the long waiting time for the update. I just worried about my request will be reject but I do not know the fault.
Will @emeryberger merge the whole request and only reject several invalid professors?

**Comment by szuapple** [comment]
@12z34x Me too. I want to know how long and how I will know if the requests are not valid. Could I friend you on Wechat?

**Comment by 12z34x** [comment]
I am also not sure about this. I am just waiting for the update. And sorry, I only use Wechat for work, we can communicate here.

**Comment by 12z34x** [comment]
@staeiou Thank you, if you have spare time, can you help me check the request https://github.com/emeryberger/CSrankings/pull/3711#issue-698361542?  Because HIT have not updated the faculty list for about 5 years.
