### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by davheld** [emeryberger/CSrankings#373]
The CS rankings website seems to not be working for me.  I am using a Mac and have tested it on Chrome, Firefox, and Safari.  The website loads but the list of schools is blank - see the attached screenshot.  I apologize if this is not the correct location to post this issue.
<img width="1178" alt="screen shot 2017-07-11 at 3 39 38 pm" src="https://user-images.githubusercontent.com/4319260/28087159-7736c6b0-664f-11e7-8809-65139b4a05cf.png">

**Comment by emeryberger** [comment]
It should eventually load. I am trying to figure out why it has slowed down. Try again and wait a minute.
