### ISSUE TITLE
As of approximately one month ago, csranking does not load on Firefox

### ISSUE THREAD

**Issue by IddoTzameret** [emeryberger/CSrankings#3731]
As of one month ago, when using Firefox browser's latest version (I've tried several versions), Csrankings.com does not load.

When switching to "World", it takes about 3 minutes to load properly. Before that it took about 15 seconds. 
Sometimes it doesn't load at all if I'm not mistaken. 

OS: Win 10, 64bit
Browser: Firefox 9x.x 64-bit.

**Comment by emeryberger** [comment]
Thanks for the report - FWIW CSrankings is primarily tested on Chrome (and on Mac). Does not reproduce on Mac M1 or Windows 10 64-bit (running in Parallels) with Firefox 90.0.2 (64-bit).

**Comment by IddoTzameret** [comment]
Okay, thanks for checking this yourself. I've done another check on a different computer running Win 10/64-bit, Firefox, and it does render (though slightly lagging: takes ~30 seconds to fully show the World table). So possibly this was indeed only a local problem on my system.
