### ISSUE TITLE
Why pull requests are processed selectively?

### ISSUE THREAD

**Issue by songfu1983** [emeryberger/CSrankings#3794]
There are many pull requests issued several months ago but are not processed yet.
When look at closed pull requests, they are issused later than still opened requests.

**Comment by jstulips** [comment]
@songfu1983 I made a pull request (#3563) back in May, and it wasn't processed as well. Check back a few times but no update. Like you said, noticed that the recent requests were all done...

**Comment by rnrand** [comment]
Yeah, this is frustrating (pull request made in April).
