### ISSUE TITLE
Bug: Rank institutions in USA lists non-US institutions

### ISSUE THREAD

**Issue by nguyenthanhvuh** [emeryberger/CSrankings#3800]
Rank institutions in USA (default option) lists several places that are not in the US, e.g., 125. Chinese University of Hongkong and 169. Barcelona Supercomputing Center as shown in the attached images.  

<img width="968" alt="csrankings-bug2" src="https://user-images.githubusercontent.com/20884260/130091903-df9e7925-8dd4-4051-ad76-8dad56c4e67c.png">
<img width="968" alt="csrankings-bug1" src="https://user-images.githubusercontent.com/20884260/130091910-8945b209-d5fe-4551-a3fe-55dcbf035acf.png">

**Comment by emeryberger** [comment]
Thanks for the note. This was due to a typo in an entry (no "The" for CUHK) and an inappropriate inclusion; both now fixed.
