### ISSUE TITLE
Merged change is not reflected on 'gh-pages' branch

### ISSUE THREAD

**Issue by tanvirmahdad** [emeryberger/CSrankings#3838]
**DO NOT USE ISSUES TO UPDATE ENTRIES: EDIT THE APPROPRIATE FILES (`csrankings-[0-9].csv`) AND OPEN A PULL REQUEST INSTEAD**

I have a pull request: https://github.com/emeryberger/CSrankings/pull/3786

I have changed csrankings-n.csv for updating affiliation, website. But after the merge the change is not reflected on 'gh-pages' branch.

Can you please let me know if I need to do anything more?

**Comment by emeryberger** [comment]
<img width="398" alt="Screen Shot 2021-11-06 at 7 53 02 PM" src="https://user-images.githubusercontent.com/1612723/140627196-c430de1b-63f4-4cc3-b4c9-3ea7b2e517b3.png">
