### ISSUE TITLE
revisit third conference for SE

### ISSUE THREAD

**Issue by emeryberger** [emeryberger/CSrankings#40]
inclusion of ASE is controversial; arguments made by some that is not up to the level of ICSE/FSE

**Comment by tsantalis** [comment]
According the [SE Conferences](http://taoxie.cs.illinois.edu/seconferences.htm) webpage maintained by Tao Xie,
FSE and ASE have a very similar number of submissions and acceptance rate every year.

In the last two years (which are not included in the stats) we can observe the same pattern.

|  | FSE | ASE |
| --- | :-: | :-: |
| 2015 | 74/291 (25.4%) | 60/289 (20.7%) |
| 2016 | 74/273 (27.1%) | 57/298 (19.1%) |

**Comment by emeryberger** [comment]
Agreed.
