### ISSUE TITLE
Profile not showing in CSRanking (possibly) due to update in DBLP index

### ISSUE THREAD

**Issue by arijitkhan** [emeryberger/CSrankings#4019]
**DO NOT USE ISSUES TO UPDATE ENTRIES: EDIT THE APPROPRIATE FILES (`csrankings-[0-9].csv`) AND OPEN A PULL REQUEST INSTEAD**

Hello:
I'm Arijit Khan (https://personal.ntu.edu.sg/arijit.khan/), faculty from NTU Singapore. https://scholar.google.com/citations?user=6Y-m8k4AAAAJ&hl=en

Recently my DBLP entry has been updated to: Arijit Khan 0002 (https://dblp.org/pid/67/2933.html)
I believe due to this update, my name is not showing under NTU Singapore DB faculty list.

Can this be please corrected? Thanks!

Arijit Khan

**Comment by arijitkhan** [comment]
A correction:  my DBLP entry has been updated to: Arijit Khan 0001 (https://dblp.org/pid/67/2933.html)

**Comment by emeryberger** [comment]
I manually updated this for you, but this is not meant to be done via issues (see the comment in the issue text).
