### ISSUE TITLE
Error on title of Prof. David Held at CMU

### ISSUE THREAD

**Issue by ShaoxiongYao** [emeryberger/CSrankings#4141]
I think Prof. David Held received his Ph.D. in 2017, and there is no record on his webpage of ACM Fellow in 1994. I wonder if I should submit a pull request directly? Or someone can confirm this is an error. Thank you!
![image](https://user-images.githubusercontent.com/49648374/138537740-2ba641c4-ae50-424a-859d-5d060fcfefd9.png)

**Comment by emeryberger** [comment]
Confirmed, thanks!
