### ISSUE TITLE
Computational Biology/Bioinformatics area

### ISSUE THREAD

**Issue by patrickb314** [emeryberger/CSrankings#42]
The top venues are places like Science, Nature, and PNAS. Those are all very broad and not indexed by dblp, but are from what I understand where the best work is published. I'm not sure how accurate using lower-impact but more focused publications would be, but it is an area many CS people work in.

**Comment by salzberg** [comment]
Computational Biology is a major area in Computer Science and has been growing for 20 years. I think every department in the top 20 has at least one faculty member in this area, many have 2 or more. CMU has an entire Dept of Comp Bio within their School of Computer Science. We do _not_ use conference publications - rarely, at least - as the main venue for our results in comp. bio. Instead, like almost all other scientific fields, we publish in journals. There are at least 20 different journals that often feature comp bio results. I'd be happy to provide a list.  The best CompBio work does not appear in Science or Nature - those journals aren't interested - but recently Nature Methods and Nature Biotechnology have started to feature quite a few Comp Bio papers.

**Comment by patrickb314** [comment]
What are the top publications? Bioinformatics, PLOS Comp Bio?  

I understand the point on Science and Nature for this field. They do need to count somewhere, however, so that interdisciplinary CS work isn't further marginalized. As a colleague of mine said "When I do interdisciplinary computer science work, I try to publish it in the best venue for that field.  For EVERY OTHER FIELD except computer science, that is Science, Nature, and PNAS.  Any ranking system that counts only publications strictly inside of computer science is dooming our field to continued provincialism."

**Comment by emeryberger** [comment]
Many of these publications are not indexed by DBLP, which CSRankings relies on. Journals also present methodological difficulties. In the interim and to make forward progress on this front (and after consultation with many, _and_ in the interest of not letting the perfect be the enemy of the good), I have added preliminary support for comp bio, as it meets the inclusion criteria (see commit b736e2916a3eaec5dc155938fef35a03dc0f529f). DBLP does not distinguish the recent journal proceedings of ISMB/ECCB from the rest of Bioinformatics, so I will need to add custom logic to support that.

**Comment by emeryberger** [comment]
ISMB special-case handling now rolled in with https://github.com/emeryberger/CSrankings/commit/ffaafadbc91efc31248f2deebc7f5521aa4d448b.
