### ISSUE TITLE
Count publications using an averaging function

### ISSUE THREAD

**Issue by respel** [emeryberger/CSrankings#422]
Hi.
Right now, the methodology is to count all publications upto "x" years beyond. I think we can do better by weighing the publications according to their age, say through some sort of sigmoid function.  
Eg,
A year old publication can be given a weight of 1 while a decade old publication can be given a weight of 0.5 and so on.

**Comment by emeryberger** [comment]
The current system is deliberately simple to understand and easily auditable (that is, the numbers can easily be hand tabulated). Your proposal would make the counts difficult to understand and it also rests on the assumption that publications "decay" over time, which is debatable. If you want to see more recent publications, just change the range of years.
