### ISSUE TITLE
What is the policy on journals that are tied to conferences and appear in DBLP?

### ISSUE THREAD

**Issue by jkkummerfeld** [emeryberger/CSrankings#4251]
I noticed that TACL (Transactions of the Association for Computational Linguistics) is not included in the ranking calculations. It is not a conference, but all papers accepted to TACL are presented at once of the ACL conferences and the bar for a TACL paper is widely acknowledged to be above that of an ACL paper. Papers in TACL do appear in DBLP (see <https://dblp.uni-trier.de/db/journals/tacl/index.html>).

If I put in the effort to make a PR adding TACL, would it be accepted?

 Thanks!

**Comment by tuukkaruotsalo** [comment]
I am also wondering if some journals should be there. Many journals, such as ACM TOCHI for CHI, ACM TOIS for SIGIR, and others invite presentations to the conference if papers are accepted by the "sister" journal of the conference. This might be a good addition but surely will need quality control to only include the really good ones.
