### ISSUE TITLE
Missing some papers due to page limit

### ISSUE THREAD

**Issue by Z-Y00** [emeryberger/CSrankings#4272]
This line would cause missing of valid papers like this:
https://github.com/emeryberger/CSrankings/blob/cc128b55c8f5dc878fc50d82f2a82e0e7d341d36/util/csrankings.py#L15
```
<inproceedings mdate="2018-11-06" key="conf/micro/PattA85">
<author>Yale N. Patt</author>
<author>John K. Ahlstrom</author>
<title>Microcode and the protection of intellectual effort.</title>
<pages>167-170</pages>
<year>1985</year>
<booktitle>MICRO</booktitle>
<ee>https://doi.org/10.1145/18927.18923</ee>
<crossref>conf/micro/1985</crossref>
<url>db/conf/micro/micro1985.html#PattA85</url>
</inproceedings><inproceedings mdate="2021-08-04" key="conf/micro/DeWitt75">
```

**Comment by Z-Y00** [comment]
Also this one

Maurício Breternitz Jr., John Paul Shen:
Organization of array data for concurrent memory access. MICRO 1988: 97-99

**Comment by emeryberger** [comment]
I'm not clear if there's a latent proposal here: a global change to page count, or one specific to MICRO? Reducing the page count globally is a non-starter: it would add unacceptable complexity as there are many conferences with short papers, keynotes, etc. that get a few pages in the proceedings, and yet are not in fact comparable to full papers (e.g., not subjected to peer review, or reviewed in a more permissive process). As for MICRO-specific: it's not clear what the review process was for these papers, as MICRO was originally a workshop and for whatever reason, the digitized front matter is partial or missing. If you can shed any light, I'd be interested in hearing about it. Thanks!
