### ISSUE TITLE
CSrankings is broken on Firefox 78.15 ESR / Debian

### ISSUE THREAD

**Issue by gannimo** [emeryberger/CSrankings#4279]
CSrankings is broken on Firefox 78.15 ESR on stock Debian. Chromium on the same platform continues to work. This seems to be a recent change in the client-side code.

The minimized JavaScript fails and exits with an error during initialization and data is not loaded (and the page fails then). A couple of references fail as well but those are likely due to uBlock filters.

![image](https://user-images.githubusercontent.com/2371964/143876572-0b79b48b-cd69-4797-8d01-4e9b2a71c55d.png)

**Comment by emeryberger** [comment]
Hi Matthias - thanks for reporting. That version of Firefox is "old" (June 2020) and no long supported. On my Mac, a similarly old Firefox 72.0.2 **crashed** the tab when opening CSrankings.  However, the latest version (94.0.2) works fine. Everything is also fine with Chrome and Safari, so this is feeling like a Firefox bug (interesting that this randomly happened with a rebuild of the page!). Please try a more recent version of Firefox and let me know. Per Wikipedia, the vast majority of Firefox users are running Firefox 92+.

**Comment by gannimo** [comment]
Hm, Firefox 78 ESR is unfortunately still the default version in Debian stable (as it's an Extended Support Release). From following the Debian forums it looks like Debian tries to migrate to ESR 92 but the build requires software that is not yet in Debian stable. Modern build systems are an amazing pain---software requires HEAD versions of most dependencies and compilers to even build. There seems to be an ongoing distribution war on how to (or not to) update browsers on Debian because of colliding principles.

IMO it's a bit odd that websites no longer run with a browser that's been initially released a year ago (and since then only received security but not feature updates).

In the mean time, Chromium seems a good alternative for the few websites that require a browser that has been released very recently. Thanks for the quick reply.

**Comment by emeryberger** [comment]
It's honestly pretty crazy that a page written in JavaScript produced by TypeScript (generating ES6 compliant code) and minimized by Google Closure would be such a problem for an ~18 month old web browser... Anyway, I see the likely culprit. I honestly wonder whether minimization is worth it (saves 43K). Would you mind downloading and testing with loading the non-minimized code? (Just switch around the comments just before the `</head>` tag in `index.html`)

**Comment by gannimo** [comment]
The non-minimized version works like a charm. (I entered developer tools, changed the URL of the script element, copied it into body, and reevaluated it to make the website work.)

**Comment by emeryberger** [comment]
Sweet - thanks! Fixed with https://github.com/emeryberger/CSrankings/commit/e6f1dc4e4aa695a4a85ddce19ec812f58571eecb.
