### ISSUE TITLE
Evolutionary Computation area?

### ISSUE THREAD

**Issue by patrickb314** [emeryberger/CSrankings#43]
Consider including Evolutionary computing as an AI sub-field. One colleague suggested the journal "Evolutionary Computation" as the leading venue; the suggested candidates for the next ones were either the journals "IEEE Transactions on Evolutionary Computation" and "Genetic Programming and Evolvable Machines, or the CEC and GECCO conferences. Need to consult with others in the field to dial this in.

**Comment by emeryberger** [comment]
Only journals that are the publication venues for conferences are currently included. In any event, with CEC and GECCO, this area does not currently meet the inclusion criteria (50 R1 schools published in the area since 2000).
