### ISSUE TITLE
Suggestion to add 'Music Information Retrieval' in 'Interdisciplinary Areas'.

### ISSUE THREAD

**Issue by chenlianMT** [emeryberger/CSrankings#438]
As the Wiki said, "Music information retrieval (MIR) is the interdisciplinary science of retrieving information from music." It combines music, information retrieval, psychology, digital signal processing, physics and other research areas.

And International Society for Music Information Retrieval (ISMIR) is the world’s leading forum in this topic, which holds annual conferences.

**Comment by emeryberger** [comment]
Hi - closing this issue. Seems like a fine area but doesn't fit with the ACM SIG / AAAI overall organization of areas.
