### ISSUE TITLE
Systematic way to find areas/sub-areas?

### ISSUE THREAD

**Issue by patrickb314** [emeryberger/CSrankings#44]
Is there some way to at least semi-systematically identify key sub-areas/publications that aren't currently included but should be? There are, for example, lots of systems sub-areas and publication venues listed, but few in other areas. 

One way would be to come at it from known top researchers. How hard would it be to check the publication score of all of the ACM fellows elected in the last decade, for example?

**Comment by patrickb314** [comment]
(Found a list of ACM fellows - working through this to see what it looks like)

**Comment by patrickb314** [comment]
Looking at the fellows elected in the last 10 years with faculty appointments, the main areas that seem to be missing are Computational Biology, Automated Reasoning/Formal Methods, Design Automation, Computational Geometry, and Computing Education.

**Comment by emeryberger** [comment]
Major areas are primarily derived from ACM SIGs. These are being added gradually.

**Comment by emeryberger** [comment]
In any event, please add individual areas as issues. Computing education is already an issue, as is computational biology.
