### ISSUE TITLE
ADD ICLR?

### ISSUE THREAD

**Issue by xiaochaowei** [emeryberger/CSrankings#4442]
Is it possible to add ICLR? ICLR is definitely one of the top conference in ML community. It equals to ICML and NeurIPS.

**Comment by smiles724** [comment]
I  really agree with this proposal. ICLR becomes rather important in the AI field and should not be ignored.

**Comment by animesh-garg** [comment]
I also recommend this. 
It is easily the top conference in AI based on citation metrics.
https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_artificialintelligence

Leaving it out in Learning feels like a big omission.

**Comment by srush** [comment]
I sent a PR, but haven't received any response :( https://github.com/emeryberger/CSrankings/pull/4529
