### ISSUE TITLE
ACM Fellows change

### ISSUE THREAD

**Issue by ljcamp** [emeryberger/CSrankings#4453]
ACM Fellows list uses my full legal name which does not match dblp, Google Scholar, or anyone who knows me.  Changing this required editing ACM Fellows data, not simply the list of faculty. Thank you for your consideration.

**Comment by ljcamp** [comment]
I noticed that although there are papers listed with my coauthors names, I am not listed as a faculty. This seems odd. It is a result of collaborating and putting my name last? 
Also, please consider adding the Workshop of Economics of Security under the Economics if you are only including conferences. Thank you.

**Comment by emeryberger** [comment]
Verified that this is correct per DBLP aliases and showing up in the database.

<img width="1092" alt="Screen Shot 2022-03-27 at 5 15 34 PM" src="https://user-images.githubusercontent.com/1612723/160301345-3b1a9a4d-1715-4612-9bc4-b96474c82f3c.png">
