### ISSUE TITLE
Profile addition does not reflect | Dr. Juneja, TIFR India.

### ISSUE THREAD

**Issue by coder-amey** [emeryberger/CSrankings#4491]
The [pull request](https://github.com/emeryberger/CSrankings/pull/4309) for making Dr. Juneja's profile visible on the listings page has been merged. However, his details do not yet reflect on the rankings page. Instead, a blank row is visible at the end of the TIFR  listing (please see attached image).

I request you to kindly look into this and advise.

![image](https://user-images.githubusercontent.com/22518828/154987428-fb516e62-76b0-416e-aef8-b3ec4fb907f9.png)

**Comment by emeryberger** [comment]
This author does not have any recorded CSrankings conference publications.

**Comment by coder-amey** [comment]
Thank you for the clarification.
