### ISSUE TITLE
Bar plot to represent university's ranking in the sub area as a percentile

### ISSUE THREAD

**Issue by animesh-garg** [emeryberger/CSrankings#4584]
The current model of presenting the bar chat helps present the counts in a more interpretable manner. 

However, instead of presenting counts, which do not have a meaning in an absolute sense, an improved visualization might be a presentation of the department ranking normalized to percentile in each area separately. In this manner, if theory produces fewer papers than ML, the bars would still be of reasonably equal size because of normalization across all universities! 

The plot would remain the same but instead, it will be showing the relative strength of the university without drowning areas where the norm is fewer publications. 

While not exactly the same but @alecjacobson created a dashboard to show this data as absolute rankings. 
http://www.cs.toronto.edu/~jacobson/csrankings-profile.html?school=Massachusetts%20Institute%20of%20Technology
In the new version, the percentile option may make the y-axis normalized 

In this model, clear winners who are outliers might not stand out, but evaluating the univ strength would be easier from a UI perspective.

**Comment by emeryberger** [comment]
Can you point to institutions where this is in fact currently highly misleading? I would welcome a PR (closing the issue).
