### ISSUE TITLE
South Asian University info entry has not been deployed yet

### ISSUE THREAD

**Issue by sayanta28** [emeryberger/CSrankings#4610]
Almost 26 days ago this #4478 PR merged with the default base branch but is still not deployed in the main Project. 

- [ ] Can anyone clarify for me is it already deployed? Or need much more time to deploy? 
- [ ] Waiting for Deploy the Info's

Thanks.

**Comment by sayanta28** [comment]
Dear @[emeryberger](https://github.com/emeryberger), Any clue about this issue??

**Comment by sayanta28** [comment]
Dear @[emeryberger](https://github.com/emeryberger), any update about this pull request deployment? It's now 1 month since the PR merged.

**Comment by sayanta28** [comment]
This year's admission application deadline is very near the end of our university. [(Admission Application Link)](http://sau.int/admissions/admission-notice.html)
Can you please explain why our university has not deployed yet? We have been waiting for a very long time. 
To: @emeryberger
CC: @zlangley, @christianholz, @hosking, @vjmenon

**Comment by emeryberger** [comment]
Done (as of some time ago). Updates are now done on a quarterly cadence.
