### ISSUE TITLE
Area Filter Problem

### ISSUE THREAD

**Issue by nhittt** [emeryberger/CSrankings#464]
Check 1 field in Area Filter but the ranking is sorted by all filters.
Please check your source code! Thanks!

![screenshot from 2017-09-23 15-13-34](https://user-images.githubusercontent.com/12457979/30771421-d72aa616-a071-11e7-9e90-48e2533c7920.png)

**Comment by emeryberger** [comment]
Do you mean that the pie chart now lists all areas? That is an intentional change.

**Comment by emeryberger** [comment]
The ranking is correct. Closing.
