### ISSUE TITLE
BUG: selecting non-default conferences has no updates or effects

### ISSUE THREAD

**Issue by nguyenthanhvuh** [emeryberger/CSrankings#4729]
this is probably a recent glitch but now when selecting or de-selecting non-default conferences (e.g., click on OOPSLA/ICFP under programming languages)  the display of institution list on the right does not get updated.  Tried on Firefox and Safari.

**Comment by emeryberger** [comment]
Tested on Chrome, Safari, and Firefox, works fine for me.
