### ISSUE TITLE
DO NOT use issues to update entries

### ISSUE THREAD

**Issue by soso123so** [emeryberger/CSrankings#4744]
**DO NOT USE ISSUES TO UPDATE ENTRIES: EDIT THE APPROPRIATE FILES (`csrankings-[a-z].csv`) AND OPEN A PULL REQUEST INSTEAD**

I have a question~
There is no NUDT in the ranking when you pick China. Anyway to update it? Since there is still some great researchers there

**Comment by emeryberger** [comment]
You need to submit a pull request that adds their CS faculty.
