### ISSUE TITLE
Request to add a domain of CS Eduation

### ISSUE THREAD

**Issue by YangAzure** [emeryberger/CSrankings#4763]
Per ACM SIG Groups, [SIGCSE](https://www.acm.org/special-interest-groups/sigs/sigcse) is listed as the group of CS Educational research. [SIGCSE TS](https://dl.acm.org/conference/sigcse) has been one of the major (flagship) conference in the domain. A simple statistics in [SIGCSE TS affiliations](https://docs.google.com/spreadsheets/d/1m6YUifR4n9rI1vA8rVWZzQCPbEM-b5wUg0ZrF-9ZDkA/edit?usp=sharing) in the past 10 years show that there are at least 69 R1 Universities published in the conference with >= 10 papers ([data source](https://dl.acm.org/conference/sigcse/affiliations?AfterYear=2012&BeforeYear=2022&queryID=4%2F4647935749&startPage=0&pageSize=50)), which makes the research area fit to join the ranking.

There are also some other conferences CS Educational researchers go for some starting references of conference candidates in the area, such as:

- [ITiCSE](https://dl.acm.org/conference/iticse)
- [ICER](https://dl.acm.org/conference/icer)
- [AIED](https://aied2022.webspace.durham.ac.uk/)
- [LAK](https://dl.acm.org/conference/lak)
- [EDM](https://educationaldatamining.org/edm2022/)

etc.

It would greatly encourage the research in computer science education area if CSRanking can give it a thought. This research area have been very interdisciplinary, while some key research results are published in HCI conferences such as CHI, or AI conferences such as AAAI, the educational emphasis makes it a distinct area by itself.

**Comment by acbart** [comment]
Unfortunately, @emeryberger has been radio silent since he rejected our initial request for this.

#11 

I don't understand why he continues to make this a sticking point. It's extremely disappointing that he's not interested in helping the field advance.

**Comment by YangAzure** [comment]
I believe @emeryberger has recently got some interesting observations about CS Education. Check the post: https://www.sigarch.org/coping-with-copilot/

Addressing this issue needs a lot of educational research effort and CSEd (and possibly AIED) conferences are the major places seeing this happen from CSEd researchers. ([ICER 2022 best paper on using Codex/Copilot for CSEd](https://dl.acm.org/doi/10.1145/3501385.3543957))

Hopefully we can receive some feedback (either positive or negative) from the stakeholders, thanks for the consideration.
