### ISSUE TITLE
BUG: Pennsylvania misspelled as Pennsylvannia

### ISSUE THREAD

**Issue by nguyenthanhvuh** [emeryberger/CSrankings#4854]
Pennsylvania misspelled as Pennsylvannia and hence an extra UPenn ranked 81st
![csranking-pennsylvannia](https://user-images.githubusercontent.com/20884260/183779715-d96cb2f7-4961-48da-8817-9a28d7fbdd7f.jpg)

**Comment by emeryberger** [comment]
Thanks! Fixed with f68f85e5c1371e975a734d3b879ed4e753845cc3.
