### ISSUE TITLE
Adding additional institutions

### ISSUE THREAD

**Issue by yoavg** [emeryberger/CSrankings#49]
The coverage of Israel seem to be quite lacking, with only Tel Aviv University and the Technion being represented. What is the procedure of adding other institutions (Bar Ilan University, Hebrew University, Ben Gurion University)?

**Comment by emeryberger** [comment]
Many non-US institutions have been added by contributions. The ideal way to do this is via a pull request: https://github.com/emeryberger/CSrankings/pulls
Extend `faculty-affiliations.csv` and `country-info.csv`. Please make sure the faculty are full-time appointments and that the names are as they appear in DBLP (you may need to enter multiple variants). Thanks in advance.
