### ISSUE TITLE
Why there is no faculty in the department of engineering science in Oxford university included in the ranking?

### ISSUE THREAD

**Issue by Junjie-Chu** [emeryberger/CSrankings#4935]
The link of the research group here: https://eng.ox.ac.uk/about/computer-vision-and-machine-learning/
Many wellknown computer scientists are not listed. such as [Andrew Zisserman]

**Comment by emeryberger** [comment]
If they don't meet the stated inclusion criteria, they can't be included (this is also in the FAQ).

> Make sure that any faculty you add meet the inclusion criteria. Eligible faculty include only full-time, tenure-track research faculty members on a given campus who can solely advise PhD students in Computer Science. Faculty not in a CS department or similar who can solely advise PhD students in CS can be included regardless of their home department. Faculty should also have a 75%+ time appointment (check `old/industry.csv` for faculty who are now more than 25% in industry).
