### ISSUE TITLE
CSrankings is missing half my papers (on DBLP)

### ISSUE THREAD

**Issue by brendano** [emeryberger/CSrankings#5]
_(6/20: updated the numbers)_

I don't care personally and feel like it's not even worth addressing such a drop in the bucket and it may not affect rankings much, but anyway...

The page on DBLP that corresponds to me is:
http://dblp.uni-trier.de/pers/hd/o/O=Connor:Brendan_T=

For papers fitting into the NLP categories (ACL, NAACL, EMNLP), I think it is completely correct.
It has 8 papers total.  But the CSRankings interface says I have 6.  I'm not sure how to see which exactly are missing?

Here's the list of papers from DBLP.  I figure the issue is alternate naming of pub venues?  There's some annoying history and conflicting naming schemes for some of the conferences (e.g. "HLT-NAACL" is now often just called "NAACL") so you end up seeing citations on internet or gscholar or i'm sure dblp where the same conference is given pretty different names by different people. bleah

```
Khanh Nguyen, Brendan O'Connor:
Posterior calibration and exploratory analysis for natural language processing models. EMNLP 2015: 1587-1598

David Bamman, Brendan O'Connor, Noah A. Smith:
Learning Latent Personas of Film Characters. ACL (1) 2013: 352-361

Brendan O'Connor, Brandon M. Stewart, Noah A. Smith:
Learning to Extract International Relations from Political Context. ACL (1) 2013: 1094-1104

Olutobi Owoputi, Brendan O'Connor, Chris Dyer, Kevin Gimpel, Nathan Schneider, Noah A. Smith:
Improved Part-of-Speech Tagging for Online Conversational Text with Word Clusters. HLT-NAACL 2013: 380-390

Kevin Gimpel, Nathan Schneider, Brendan O'Connor, Dipanjan Das, Daniel Mills, Jacob Eisenstein, Michael Heilman, Dani Yogatama, Jeffrey Flanigan, Noah A. Smith:
Part-of-Speech Tagging for Twitter: Annotation, Features, and Experiments. ACL (Short Papers) 2011: 42-47

Dani Yogatama, Michael Heilman, Brendan O'Connor, Chris Dyer, Bryan R. Routledge, Noah A. Smith:
Predicting a Scientific Community's Response to an Article. EMNLP 2011: 594-604

Jacob Eisenstein, Brendan O'Connor, Noah A. Smith, Eric P. Xing:
A Latent Variable Model for Geographic Lexical Variation. EMNLP 2010: 1277-1287

Rion Snow, Brendan O'Connor, Daniel Jurafsky, Andrew Y. Ng:
Cheap and Fast - But is it Good? Evaluating Non-Expert Annotations for Natural Language Tasks. EMNLP 2008: 254-263
```

**Comment by emeryberger** [comment]
Fixed entry for HLT-NAACL.

**Comment by emeryberger** [comment]
Also, "ACL (Short Papers)" is not currently included.
