### ISSUE TITLE
On qualification of Xiao Yan in CSranking

### ISSUE THREAD

**Issue by songfu1983** [emeryberger/CSrankings#5092]
Xiao Yan is Research Assistant Professor at SUSTech who **cannot** solely advise PhD students in Computer Science.
Please refer to  https://cse.sustech.edu.cn/faculty/~yanx.

I did not check all the PIs of SUSTECH in CSRanking, but doubt if PIs claimed that are affiliated with SUSTECH are really qualified to be added in CSRanking.

**Comment by emeryberger** [comment]
Removed. If you identify more such issues, please let me know.
