### ISSUE TITLE
Add Design Automation to the list of CS areas

### ISSUE THREAD

**Issue by simha** [emeryberger/CSrankings#51]
Rationale

SIGDA is part of ACM. Many of the "top 20" schools in the US have faculty in CS that have faculty publishing in design automation conferences.

Thanks,
Simha

**Comment by emeryberger** [comment]
Hi Simha - thanks for the note. What are the top conferences in this area? The SIGDA page just lists DAC. Any other included conference needs to be in the same equivalence class in terms of prestige, # of submissions, and acceptance rate.

**Comment by wongdani** [comment]
I would say ICCAD and DAC are the clear top two in this area. SIGDA organizes many events (SRC, PhD Forum, etc) across these two conferences. 

-- Daniel

**Comment by emeryberger** [comment]
OK, more than meets the criteria. Added.
