### ISSUE TITLE
Collaborating with pull requests

### ISSUE THREAD

**Issue by huwan** [emeryberger/CSrankings#5185]
Many contributors have helped to submit pull requests to add and maintain faculty CSrankings data. However, it is a tough job for @emeryberger to verify all these pull requests. There are many pull requests to be merged.

How about establishing a volunteer-based review board committee, with the responsibility of reviewing pull requests, just like a conference program committee for reviewing papers. The board decides whether the pull requests should be accepted, changed, or rejected. Pull requests must have a specific number of approving reviews from the review board before they can be merged.

GitHub supports this collaboration, for example, [Approving a pull request with required reviews](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

I hope this will ease the review burden of the project manager and speed up the pull request review process.

**Comment by mnwrhsn** [comment]
I am happy to volunteer.

**Comment by emeryberger** [comment]
I appreciate the information and will take it under advisement. Thanks.
