### ISSUE TITLE
What would be the procedure to add a faculty?

### ISSUE THREAD

**Issue by ghost** [emeryberger/CSrankings#52]
Hi,
pretty much everything is in the title: my faculty is currently missing and I wonder what would be the necessary steps to add it to the website. List of researchers ? Email adresses ?

Thank you.

**Comment by emeryberger** [comment]
There are some instructions on the bottom of the page; I prefer a pull request to `faculty-affiliations.csv`. It's extremely important that the names are exactly as they appear in DBLP (preferably including all aliases, though I can generate these automatically).
