### ISSUE TITLE
please merge the pull request 5183 -  https://github.com/emeryberger/CSrankings/pull/5183/checks

### ISSUE THREAD

**Issue by arijitkh** [emeryberger/CSrankings#5208]
**DO NOT USE ISSUES TO UPDATE ENTRIES: EDIT THE APPROPRIATE FILES (`csrankings-[a-z].csv`) AND OPEN A PULL REQUEST INSTEAD**

The following pull request was made earlier 
https://github.com/emeryberger/CSrankings/pull/5183/checks 
and appreciate if this can be merged.

The pull request is about the affiliation update of Arijit Khan (update to Aalborg University, with homepage: https://homes.cs.aau.dk/~Arijit/)

Thank you,
Arijit Khan

**Comment by emeryberger** [comment]
Updates are quarterly. It hasn't been three months since your pull request (far from it).
