### ISSUE TITLE
Publication filter too restricted for computational biology

### ISSUE THREAD

**Issue by pinardemetci** [emeryberger/CSrankings#5266]
**Original post:** recently checked out the computational biology rating for my institution (Brown U) on this page, and the number of publications is incorrect by a very large margin. I suspect the same is probably true for all schools. For example, Ritambhara Singh's publication record is listed as 1 for all of 2012-2022, while their dblp profile lists 6 CS-based comp bio publications for just the past year alone (2021-2022). 
The number seems incorrectly low for other professors I recognize from different institutions, too, like Ziv Bar Joseph. Their CSrankings profile shows 6 publications for 2012-2022 while they have 6-7 publications from 2021-2022 alone. 

What are the criteria for determining which papers count towards comp bio publications here? Is there some filtering on the dblp papers list? 

**Edit:** Found the criteria in _filter.xq_ file. Two major conferences (RECOMB and ISMB, ISMB/ECCB) seem to be considered, as well as the Bioinformatics journal publications accompanying ISMB, which is great. However, the filter seems too restrictive, e.g. Journal of Computational Biology publications accompanying RECOMB aren't considered despite the Bioinformatics example. ECCB conference seems to count only when it is co-organized with ISMB, but it is a stand-alone conference every two years. ACM's Bioinformatics and Computational Biology conference (ACM-BCB), Pacific Symposium on Biocomputing, and Workshop on Algorithms in Biology (WABI) aren't on the list, either, although these also publish CS-heavy comp bio papers. Are we allowed to submit pull requests for the _filter.xq_ file?

**Comment by emeryberger** [comment]
Included conferences are clearly indicated on the web page - just click on one of the blue triangles. Only the top conferences in any area - forming a single top equivalence class - are included in CSrankings. I'd recommend watching the video linked on the front page and/or reading the FAQ for more background.
