### ISSUE TITLE
Missing SC 2017 papers

### ISSUE THREAD

**Issue by dingwentao** [emeryberger/CSrankings#5270]
I observed a drop in #Pubs in CSRankings and feel it may miss some publications. I personally don't care, but just feel it might affect other people's CSRankings too.

The page on DBLP that corresponds to me is:
https://dblp.uni-trier.de/pid/162/0802.html

In 2017, I do have one publication that should be counted for CSRankings' HPC category:
```
Xin Liang, Jieyang Chen, Dingwen Tao, Sihuan Li, Panruo Wu, Hongbo Li, Kaiming Ouyang, Yuanlai Liu, Fengguang Song, Zizhong Chen:
Correcting soft errors online in fast fourier transform. SC 2017: 30
```

However, if you check ["2017-2017"+"HPC"+"USA"](https://csrankings.org/#/fromyear/2017/toyear/2017/index?hpc&us), Indiana University (where I'm now affiliated) is not listed.

This can be also verified from another perspective:
If you check ["2017-2017"+"HPC"+"the world"](https://csrankings.org/#/fromyear/2017/toyear/2017/index?hpc&world), [Torsten Hoefler](https://dblp.uni-trier.de/pid/16/3869.html) from ETH Zurich only has #Pubs of 2 in 2017. However, he should have 4 publications counted for CSRankings in 2017:
```
Maciej Besta, Michal Podstawski, Linus Groner, Edgar Solomonik, Torsten Hoefler: 
To Push or To Pull: On Reducing Communication and Synchronization in Graph Computations. HPDC 2017: 93-104

Marius Poke, Torsten Hoefler, Colin W. Glass: AllConcur: 
Leaderless Concurrent Atomic Broadcast. HPDC 2017: 205-218

Edgar Solomonik, Maciej Besta, Flavio Vella, Torsten Hoefler: 
Scaling betweenness centrality using communication-efficient sparse matrix multiplication. SC 2017: 47

Torsten Hoefler, Salvatore Di Girolamo, Konstantin Taranov, Ryan E. Grant, Ron Brightwell: 
sPIN: high-performance streaming processing in the network. SC 2017: 59
``` 

It makes me feel like all papers in SC 2017 are not counted (I didn't check them all). I remember the number of publications in CSRankings being correct for me, but not sure if something was changed recently, so just want to bring this to your attention.

Thanks,
Dingwen

**Comment by emeryberger** [comment]
Thanks for the note. For some reason, DBLP no longer lists (or never listed?) SC 2017 papers with page numbers. I have added that year as an exception for the page length checker for that conference.
