### ISSUE TITLE
CSrankings is missing my papers/books (on DBLP)

### ISSUE THREAD

**Issue by hagohel** [emeryberger/CSrankings#535]
My many papers are not listed on dblp but My following papers and books are really worth and not listing in dblp.  I know it is not much serious matter and feel like it's not even worth addressing such a drop in the bucket and it may not affect rankings much but following list is not only interesting read but also latest research trends of computer science. Please do the needful

1) Gohel H., Sharma P. (2016) **Intelligent Web Security Testing with Threat Assessment and Client Server Penetration.** In: Proceedings of International Conference on ICT for Sustainable Development. Advances in Intelligent Systems and Computing, vol 409. Springer, Singapore available at https://link.springer.com/content/pdf/10.1007%2F978-981-10-0135-2_54.pdf

2)  Dr. Hardik Gohel, Dr. Bhavesh Kumar Garsondiya, Dr. Aarti Kothia, Hitesh Jani, **“Operational
Study of Brain Reading–Neuroimaging in Human Brain Computer Interface(H-BCI)”**. American Research Journal of Computer Science and Information Technology, Volume 2, 2017; pp:1-6.

3) H. Gohel, **DEVELOPMENT OF SPECIALIZED OPERATORS FOR ANALYSIS OF SOCIAL MEDIA THROUGH WEB INTELLIGENCE** Proceedings of International Conference on E-Learning Engineering and Computer Software July 15-16, 2015, ISBN: 978819313731

4) Gohel, Hardik, and Priyanka Sharma. "Study of Quantum Computing with Significance of Machine Learning." CSI Communications - Knowledge Digest for IT Community 38.11 (2015): 21-23.

5) G. Hardik, U. Himanshu, "Developing Solutions with Big Data Technology",  CSI Communications - Knowledge Digest for IT Community 41.2 (2017): 18-21.

Books availalbe on [amazon](https://www.amazon.com/s/ref=dp_byline_sr_book_1?ie=UTF8&text=Hardik+Gohel&search-alias=books&field-author=Hardik+Gohel&sort=relevancerank) but not on dblp
1) Introduction to Network & Cyber Security
2) Human Brain Computer Interface (H-BCI)
3) Applied ICT - Beyond Oceans & Spaces

**Comment by emeryberger** [comment]
Hi - for better or worse, CSrankings depends on DBLP, so papers not present there are out of scope.
