### ISSUE TITLE
Ting Zhu 0001—publications not pulling from DBLP?

### ISSUE THREAD

**Issue by aperrault** [emeryberger/CSrankings#5394]
Hello,

A couple of days ago, my PR #5350 was merged in, which adds faculty to Ohio State University (OSU) CSE. One of the changes was to add Ting Zhu 0001, who was previously at University of Maryland–Baltimore County (UMBC). He did not previously have a DBLP page and was listed on CSRankings for UMBC with a pointer to the disambiguation page for Ting Zhu. In the update, DBLP created an author page for him, which is currently listed in csrankings-t.csv:
Ting Zhu 0001,Ohio State University,https://engineering.osu.edu/people/zhu.3445,BXp6PIIAAAAJ

He is not appearing under OSU CSE on CSRankings.org. It looks like his publications are not getting added to generated-author-info.csv. An example publication that should show up (from Ting Zhu 0001's DBLP page https://dblp.org/pid/42/5105-1.html) is:
[Yan Li](https://dblp.org/pid/87/660-48.html), [Zicheng Chi](https://dblp.org/pid/136/1074.html), [Xin Liu](https://dblp.org/pid/76/1820-45.html), Ting Zhu:
Passive-ZigBee: Enabling ZigBee Communication in IoT Networks with 1000X+ Less Power Consumption. [SenSys 2018](https://dblp.org/db/conf/sensys/sensys2018.html#LiCLZ18): 159-171

Thanks.

Andrew

**Comment by emeryberger** [comment]
The addition of this entry apparently post-dates my previous update of DBLP (November 27, 2022). Just pushed an update.
