### ISSUE TITLE
Make affiliations relevant per year

### ISSUE THREAD

**Issue by mwhicks1** [emeryberger/CSrankings#54]
It seems this system does not account for arrivals/departures of faculty? If so, then rankings computed up to any year in the past (e.g., from 2000-2010) would be flawed because they would be computed using the present roster, not the past roster (i.e., the one in 2010). Generally speaking, one might think that the ranking from years XXX-YYY should computed from the average pub count of the actual faculty present during each of those years.

**Comment by emeryberger** [comment]
I know of no way to easily obtain historical affiliation data. If you find one, I would consider integrating it (though it would have to be quite complete).

**Comment by mwhicks1** [comment]
Fair point. Then I might suggest updating the website to point out that you are using a 2016 roster and that historical rankings are not to be trusted (i.e., computing the ranking from 2000-2008, which one can do, is not going to make sense in and of itself).

**Comment by emeryberger** [comment]
It specifically says at the bottom: "Output is attributed to the institution where authors are currently affiliated full-time, tenure-track faculty members."

**Comment by mwhicks1** [comment]
Read the fine print, eh? :)
