### ISSUE TITLE
Full time and tenured tracked faculty from many universities in France are missing

### ISSUE THREAD

**Issue by schopra6** [emeryberger/CSrankings#5409]
Many researchers who advise Ph.D. students and also are faculty members with affiliated Universities for France are missing. Like Max Planck Institute in Germany, France has government-sponsored research institutes  Centre national de la recherche scientifique (https://www.cnrs.fr/en) and National Institute for Research in Digital Science and Technology(INRIA) in various cities and regional labs LORIA, LIG, IRIT etc. These institutes are in general affiliated with the universities. Adding each member in the csv file is a tedious task. I just want to bring to your notice that if there is an automatic process to collect this information, please consider including them. Ranking for France might change completely and impact worldwide ranking.

**Comment by emeryberger** [comment]
There is no automatic way to generate this information. Practically every institution in the database - including, for example, MPI - comprises manually entered faculty members, almost all of them contributed by someone else. I will happily accept PRs.
