### ISSUE TITLE
Awaiting disambiguation entries for PKU

### ISSUE THREAD

**Issue by emeryberger** [emeryberger/CSrankings#544]
Wei Chen
Wen Gao
Chao Zhang
Lu Zhang
Feng Chen
Chao Xu
Ning Zhang
Jian Wang
Wei Zhang
Gang Huang
Jing Chen
Liwei Wang

**Comment by inspiron221** [comment]
Xiaojun Wan is also ambiguous

**Comment by emeryberger** [comment]
Thanks for the note - fixed Xiaojun Wan.

**Comment by xiongyingfei** [comment]
This one should have been resolved by my pull request.

**Comment by emeryberger** [comment]
belated cleaning up this issue.
