### ISSUE TITLE
IEEE VR 2022, ACM SIGGRAPH 2022 Volume 41, ACM SIGGRAPH ASIA 2022 are not indexed 

### ISSUE THREAD

**Issue by quangtnv** [emeryberger/CSrankings#5452]
Counting the papers published in:
- IEEE VR 2022 - TVCG journal track
- ACM SIGGRAPH 2022
- ACM SIGGRAPH Asia 2022

Added missing index inside [util/csrankings.py](https://github.com/emeryberger/CSrankings/blob/gh-pages/util/csrankings.py) and issued pull request: #5451

**Comment by emeryberger** [comment]
Thanks! Fixed with PR and extended with https://github.com/emeryberger/CSrankings/commit/35f159fc0fcc1bcf8b4e6cb519e83fc02884d000.
