### ISSUE TITLE
display bug? EUROGRAPHICS (listed under the horizontal line) selected by default under Graphics

### ISSUE THREAD

**Issue by nguyenthanhvuh** [emeryberger/CSrankings#5454]
Usually conferences under the horizontal lines are not listed by default, so not sure if it is a bug or not.

**Comment by emeryberger** [comment]
Fixed, thanks for the report!

**Comment by ikewyz** [comment]
Hi，I‘m a newcomer，I would like to ask what is the meaning of unselected by default under the horizontal line ？
