### ISSUE TITLE
Include Duke University's ECE department

### ISSUE THREAD

**Issue by shingjan** [emeryberger/CSrankings#548]
UIUC got its whole ECE department included. But other universities, like Duke, don't get to do the same. I assume ECE departments are eligible for such a ranking. Hence, can we do that? I could create a pull request to include all ECE faculties from Duke.

**Comment by emeryberger** [comment]
Only faculty who can (solely) advise PhD students in CS are eligible for inclusion. See https://github.com/emeryberger/CSrankings/blob/gh-pages/CONTRIBUTING.md.
