### ISSUE TITLE
Awaiting disambiguation entries for Tsinghua: Jun Zhu

### ISSUE THREAD

**Issue by emeryberger** [emeryberger/CSrankings#551]
Jun Zhu , Tsinghua University

**Comment by chenming-wu** [comment]
Already done in #683

**Comment by xchuwenbo** [comment]
Hi, there. I am from Tsinghua University and work closely with Jun Zhu. **_Currently still Awaiting disambiguation_**. Could you please take a look? Let me know if you need any information or help. Thanks!
![image](https://user-images.githubusercontent.com/3981246/47262365-86f67e80-d519-11e8-9f37-5cd152ff875c.png)

**Comment by xchuwenbo** [comment]
It looks that **Jun Zhu 0001** refers to Jun Zhu himself. But **Jun Zhu** refers to a disambiguation dblp page, and is not intended to be the bibliography of an actual person (https://dblp.uni-trier.de/pers/hd/z/Zhu:Jun). But most paper in this disambiguation pages belongs to Jun Zhu himself. How should we deal with this? Thanks!

**Comment by xchuwenbo** [comment]
Hi, 
The dblp information has been updated. Now we need to 

1. update **Jun Zhu 0001** csranking information from dblp
2. delete **Jun Zhu** asince it's just a disambiguation dblp page

Thanks!
Wenbo

**Comment by xchuwenbo** [comment]
Hi, 

The dblp page have been updated. Now we need to:

1. update **Jun Zhu 0001**'s csranking information from dblp
2. delete **Jun Zhu** since it's a disambiguation dblp page(https://dblp.uni-trier.de/pers/hd/z/Zhu:Jun)

Thanks!
Wenbo

**Comment by emeryberger** [comment]
DBLP's entry is still wrong; many of Zhu's papers (including those in NeurIPS 2018) are still listed under Jun Zhu, not Jun Zhu 0001.

**Comment by emeryberger** [comment]
(Removed Jun Zhu)
