### ISSUE TITLE
Create additional sortable metrics 

### ISSUE THREAD

**Issue by fycus-tree** [emeryberger/CSrankings#562]
Currently, there is only one "master" algorithm for computing an aggregate rating. [As recently posted on a  blog](https://blog.cryptographyengineering.com/2017/11/08/a-few-thoughts-on-csrankings-org), and even highlighted in the FAQ, some of these trade-offs are less than ideal. Adding additional metrics by which users could sort would increase the usability of the site, make the decisions less arbitrary, and reflect that "what counts as best depends on what you value."

Here are some proposals:

1. Include a ranking that only distributes credit to authors in the database (to alleviate the blog's concern, even though this issue is highlighted in the FAQ)
2. Include a ranking that gives "full" credit for each publication (not fractional) (likewise alleviating the above)
3. Include a ranking that removes the per-field normalization (it is strange that when you add new fields, the rankings for schools which don't publish there drops significantly) 
4. Include a ranking that includes arXiv publications as a conference category (yes this is trivial to game, but it'd be interesting to see who does well if they're all counted). 

Just thought I'd propose this formally

**Comment by marcniethammer** [comment]
It would also be nice to have the ability to normalize by faculty size.

**Comment by leonidk** [comment]
@marcniethammer Sure. Though I think this one has serious strategy/gaming issues.

I think (naive) size normalization is fairly flawed. It discourages inclusion and flips user's incentives from contributing updates (as total ranking does) to only contributing updates for high-profile faculty (as average ranking does). 

Plus, when universities do their hiring, their rankings drop. If universities keep old professors around for teaching/advising/administration, their rankings drop. If universities have a bunch of faculty in a single (perhaps unlisted or unpopular) field, their rankings drop. Plus there's an incentive to cull anyone who isn't actively publishing. I think "Median count" may be better for something like this. 

Taking CMU for example (which has 150 faculty at the top of the list). They have 9 faculty with only 1 listed publication, all of them seem to be fairly senior faculty who have moved on to teaching/admin work. They have "1.8" adj. publications between them. The "average" score for CMU would improve if they culled them, as it's 6% of the faculty, but ~ 0.01 % of the research output. Stanford on the other hand, has no such individuals, so their average is fairly high. A naive average would have Stanford score above CMU because of this composition. Though if we take the average of their top 50 faculty (another size normalizing method)? CMU has 50% more research output on a per-professor basis.

**Comment by fycus-tree** [comment]
@marcniethammer Sure, but I think that would makes things worse. It makes the ranking much less strategyproof. It would also flip the incentive for CSRankings contributions, from adding people (a university always benefits) to only adding high-profile people or even removing people (a university wants a higher average). This might introduce more complexity into the system (people who want non-core CS faculty removed from the list because it lowers the rankings). 

Rankings would drop when junior faculty is hired. Rankings would drop if older faculty are kept on for teaching/admin work. Rankings would drop if people submit anyone below the mean to website. Rankings would drop if faculty publish in conferences/venues that aren't listed on CSRankings. 

Using median instead of mean would alleviate this a little bit. But to give an example, CMU has 150 faculty listed. 9 of them have only 1 publication listed. That's 6% of the faculty, contributing ~0.01% of the research output (they seem to be more senior faculty who have moved on to teaching/admin work). Stanford on the other hand, has no such faculty listed. So maybe Stanford's high ranking, with only ~50 faculty, means that each faculty is more efficient? Not really, if you average the top 50 for CMU and Stanford, the top 50 faculty from CMU produce 50% more publications than Stanford's entire faculty. Universities shouldn't benefit from "subselecting" their faculty members.

**Comment by emeryberger** [comment]
The general theme of these suggestions is to add more knobs to let people choose their rankings. I don't think this is helpful (it becomes a "choose your adventure" story). Counting arxiv is, well, an _interesting_ suggestion :). I think the current counting mechanism is not going to change soon (your excellent summary on https://github.com/emeryberger/CSrankings/issues/589 sums up the issues with other proposals). I don't see how removing per-field normalization helps — that would just skew toward areas with higher publication rates.

**Comment by fycus-tree** [comment]
@emeryberger 
Isn't ranking a bit of a choose your own adventure story? Wouldn't it be interesting how everything shifted if we counted arXiv papers? I guess my biggest issue with per-field normalization is that... it feels imperfect as-is. 

I could open a separate issue for this, but my main issue is that it's an unweighted mean across fields. I... don't really like that. As pointed out in #611, "Computer Vision" has nearly 10-times the number of publications as "Economics & Computation" (which is only being done by a dozen universities and a few dozen faculty). Should it not get 10-times the weight? Or log(10) times the weight? As you've said about the selection of a field's conferences, ideally they'd be an equivalence class. It's not clear that the way fields are currently organized/weighed satisfies this.

For example, if you removed Econ/Comp, Stanford moves from 3 -> 5 because it turns out UIUC & Berkeley don't really work in that area, and Tim from Stanford does. In fact, a lot of the top-10 shuffles around because of a single faculty member in their department. **That is not good**. I'm not sure if the weighting should be per-paper-per-field or per-authors-per-field or something else, but it probably should be weighted. Or the conferences should be grouped into better/different logical units that form more of an equivalence class when the geometric mean is computed.

**Comment by emeryberger** [comment]
The organization of CSrankings largely reflects ACM SIGs. This displaces the question of what constitutes an area of CS into a recognized division. No division of areas is going to be equivalent or even stable over time (especially when large-scale changes occur, such as removing certain conferences, adding conferences, etc.).

SIGEcom is an ACM SIG (and a recent entry to CSrankings). Yes, it is a comparatively small SIG, at least based on representation in CSrankings. CSrankings effectively treats all CS areas the same. Weighting will probably end up as a de facto value judgement that will prefer large areas / areas with high publication rates over others. That is also not good.

However: the current precision is perhaps too fine. Dropping the decimal place from adjusted counts when computing counts would make it robust to minor changes (e.g., it would treat 11.2 and 11.3 as equivalent).

**Comment by fycus-tree** [comment]
The problem is this normalization makes it's own value judgement-- that all ACM SIGs are equal. Which assumes that ACM has done a good job of managing, balancing and selecting SIGs. 

The problem I have is that a single faculty member, being a large part of a small ACM SIG, can shift up and down relative rankings by 5-10%. For the Econ field, It's not Stanford that moves so much (11.3 or 11.2) (because they have Tim), but UIUC (10.6 -> 11.3) and Berkeley (11.1 -> 12.1). If we go back to incentive systems, this would incentivize hiring in smaller fields. If UCB hires someone in that field (e.g. [Markakis from AUEB](http://pages.cs.aueb.gr/~markakis/)) their ranking would go up by ~10%. Compare that to hires in Theory or Vision or Security, where a single faculty would be much more marginal (because of normalization). This is a much more real "gaming" process that I'd be worried about. Well-funded universities could hire a few token faculty in less-popular fields, since additional work in popular (sometimes "exciting" or "well-funded") fields isn't worth as much. 

I understand that it seems unfair to reward high-publication fields for having different standards. But in some ways, a paper is a paper. One could draw an analogy to a bicameral political system (e.g. House & Senate). **This is why I'm advocating for allowing users to compute either metric (normalized by field and not), as both clearly have flaws, but different ones.** If there's still a desire for "one metric to rule them all", weighing by log(number of publications per field) brings in a nice power-law assumption about fields, balancing out some of the inequality in SIG organization, while still normalizing for varying publication rates in fields.

**Comment by fycus-tree** [comment]
As highlighted by @marcniethammer on #762, there is an issue with geometric means and increasing the number of subject areas. In fact, with 26 areas right now, many departments' scores get dragged down aggressively, as every area they don't publish in pulls down the score. Per the counts in #611, the bottom 5 fields combined have less papers (8% of total) than any of the top 3 areas (~9% of total each) [vision,theory,ai], so these fairly rare fields can penalize contributions in more established fields. 

This brings an additional metric idea: what about taking geometric means over the 4 "mega" categories (AI, Systems, Theory, Extra) instead of each subcategory? My quick math shows it'd be about 18%,28%,15%,19% splits respectively, which is fairly balanced (more so than the 26 categories). Although I used marc's numbers and they seemed to be missing ML.

**Comment by marcniethammer** [comment]
Oops @fycus-tree , it looks like I indeed forgot to grep 'mlmining' when I created these numbers. I reran the numbers based on the old data and script I posted in the very first post of #611 (so these are not totally current, but from a few months ago, but probably still a good estimate; you can rerun it if you like, just download data.zip). Here are the results sorted by size including ML, sorry about the oversight:

vision: 6334
act: 6184
ai: 5954
mlmining: 5942
comm: 4433
robotics: 4094
mod: 3479
chi: 2825
nlp: 2470
sec: 2410
arch: 2360
hpc: 2220
graph: 2210
plan: 2021
soft: 2015
ir: 1903
da: 1867
ops: 1752
log: 1678
crypt: 1509
mobile: 1223
metrics: 1198
bed: 1172
vis: 1176
bio: 1046
ecom: 736

**Comment by fycus-tree** [comment]
Thanks!

  | Total | AI | Systems | Theory | Misc
-- | -- | -- | -- | -- | --
Papers | 70211 | 22603 | 26150 | 9371 | 12087
Percentage | 100% | 32% | 37% | 13% | 17%
Groups | 26 | 5 | 12 | 3 | 6
% per group | 3.8% | 6.4% | 3.1% | 4.4% | 2.9%


There's all sorts of simple reads on this. AI (versus Systems) has too "few" groups, leading to those papers being "undervalued" under geometric means (or by Systems work being overvalued). Computing geometric means over these categories would be fair-ish, although computing them over 3 groups (AI, Systems, Theory+Misc) would have fairly balanced percentages at (32%,37%,31%) and make sense mathematically, if not completely align with the concepts.

**Comment by marcniethammer** [comment]
I am not sure how difficult this would be to do, but I would be very interested in seeing how rankings change with different weighting options:

1) The current approach.
2) The approach suggested by @fycus-tree above.
3) The simplest possible approach which just adds papers - still using the # of co-author weighting. (When in doubt I tend to prefer the simplest option.)
4) ...

I suspect many of these rankings would be highly unstable, but it could be instructive to see in what ranking ranges a particular university falls given a set of such measures (of course, this then depends on the chosen set, but in any case it may tell something about stability). 

Ultimately, a much more coarse-grade ranking may be more reasonable and "healthy" (can one really distinguish between rank 23 and 24 lets say?). Or one could alternatively use more of a "choose your own adventure" approach where one dials in desired criteria.

**Comment by fycus-tree** [comment]
I agree that including the "simply add fields" stuff is the simplest, preferable alternative metric. There's still some other types of ideas (including the per-author normalization stuff) that are kind of interesting. 

But my thinking behind considering fewer, larger categories is that it preserves some of the benefits of current system (where Theory and AI and Systems all have different publishing rates), while more closely approximating the "simply add everything" metric (which you could get by simply having 1 category).
