### ISSUE TITLE
Questions about a PR.

### ISSUE THREAD

**Issue by trhun-ptit** [emeryberger/CSrankings#5738]
Dear admins,

I am the owner of the PR "Add a new institute in Vietnam (Asia) and new faculty members".
It seems my PR was rejected. Could you provide me with a reason? Then I will fix my PR and create a new one again.
Thank you.

Best regards,
Hung Tran.

**Comment by nguyenthanhvuh** [comment]
I am not an admin here but your PR was **not** rejected.  It is still in the list of open PRs waiting to be merged.
