### ISSUE TITLE
CSrankings has missed one of my papers, even though it exists on DBLP.

### ISSUE THREAD

**Issue by yjwtheonly** [emeryberger/CSrankings#5788]
For the ACM SIGCSE listed under Computer Science Education category, my related paper count shows 0. However, the following paper can be found on my DBLP page:

```
Ming Zhang, Virginia Mary Lo:
Undergraduate computer science education in China. SIGCSE 2010: 396-400
```
This is my DBLP page: https://dblp.uni-trier.de/pid/73/1844-4.html. Maybe you can check it out.

**Comment by emeryberger** [comment]
From the FAQ:

> Note that publications must be at least 6 pages long to be counted.
