### ISSUE TITLE
Existing Faculty Members in csv not showing on website

### ISSUE THREAD

**Issue by pratikmiitj** [emeryberger/CSrankings#5813]
Hi,

Some faculty members are present in the corresponding csv files but they are not showing on the website under their affiliation. Please suggest if there is any issue that needs to be corrected.

**Comment by emeryberger** [comment]
Faculty are only listed if they have published full papers in one of the selective venues that CSrankings indexes. I went to the first author's and third author's DBLP pages and they have no such pubs.

**Comment by pratikmiitj** [comment]
Is the list of considered publication venues maintained anywhere on the site?

**Comment by emeryberger** [comment]
Of course. They are all listed on the left-hand side of the UI (click on a triangle on the left side), and the code in the repo processes these publications.

<img width="399" alt="Screenshot 2023-05-01 at 11 48 58 AM" src="https://user-images.githubusercontent.com/1612723/235481367-312c349c-0486-4300-b1ec-c6dfcdf4f37e.png">

**Comment by pratikmiitj** [comment]
Ok Thanks.
