### ISSUE TITLE
Can CSRankings program files be updated ?

### ISSUE THREAD

**Issue by soulteary** [emeryberger/CSrankings#5869]
I've read the program files in detail outside of the data files for this project.

I found some obsolete and unused program scripts, and some ways to improve the handling, which can lower the threshold for independent operation of this project or other people's participation in the contribution while ensuring the running results are consistent.

However, according to the [contribution guidelines](https://github.com/emeryberger/CSrankings/blob/gh-pages/docs/CONTRIBUTING.md), I can't find the applicable rules or recommendations, can any maintainers provide some guidance?

How do I submit a PR, or is this allowed?

According to the project commits record and maintenance timeline, I think it may be more suitable to ask you,  @emeryberger , thanks!

Sorry for the interruption.

**Comment by emeryberger** [comment]
Hi - I'm the sole maintainer, so you have the right person. I'd welcome a set of narrowly scoped PRs that each do one thing that is easily auditable (e.g., remove no longer used files, add documentation about files, etc.).

**Comment by soulteary** [comment]
thanks, I will follow your advice, and have a try, and I'll try to start with the easiest

----

after reading the project carefully, I found that the project does have some areas that can be improved, which can make this project better, e.g. 

- Some files that are no longer used such as you mentioned
- Perhaps some logic moved to python or other languages ​​to make the front-end program faster and the overall code easier to maintain
- GitHub currently supports CI (for free, I can also provide servers to do similar things), which allows data updates to be updated daily or weekly with the upstream, Depends on reviewer's (maybe you) energy
- There may also be some detailed adjustments on the front end to make the experience better and faster.
- hardcode But perhaps better configuration rules can be extracted, which can make it easier for other projects to use the same criteria to screen better people
