### ISSUE TITLE
CSRankings Update Schedule and Moderation Policies

### ISSUE THREAD

**Issue by csrankings-anon** [emeryberger/CSrankings#5892]
~~~deleted anonymous post~~~

It's fine to post issues, but not anonymously.

**Comment by emeryberger** [comment]
Deleting anonymous post.

**Comment by csrankings-anon** [comment]
Thanks, but I think your unwillingness to address any of the issues I've raised and failure to understand why a junior member of the field might wish to post anonymously on this topic confirms what I've said. I also don't see anywhere in your contributing guidelines that anonymous posts are disallowed.
