### ISSUE TITLE
Incorrect count of my publications

### ISSUE THREAD

**Issue by joselabellan** [emeryberger/CSrankings#5897]
Hi,
Yesterday, my profile was included in the repo (José L. Abellán from the University of Murcia). Thanks for this!

However, I've seen that only 2 of my publications are counted when the ranking is generated. 
According to the venues.csv, the count should be 5 as I have published in HPCA 2020, ISCA 2019, ASPLOS 2023, ICS 2015, and Bioinformatics 2021 (this is named "Bioinform." in DBLP).

What is wrong?
Thank you so much.

**Comment by emeryberger** [comment]
Thanks for the note. The ASPLOS one is because they changed the name of the conference to add a number (smfh). I will fix that momentarily. HPCA is not on by default. Only the issue of Bioinformatics corresponding to ISMB is indexed.

**Comment by joselabellan** [comment]
Thanks Emery. 
But I see that HPCA is on by default in this link: https://github.com/kimns516/CSrankings/blob/c55fbc85dad0b6103af0a736aeebc7cfcd99294c/venues.csv
If not, please, what are the venues that really count to generate the ranking? Which file of the repo does define them?
Thanks!

**Comment by emeryberger** [comment]
That venues thing is not used. Click on the blue triangles next to each area in the user interface.
