### ISSUE TITLE
Question about number of professors in the database

### ISSUE THREAD

**Issue by mcmachado** [emeryberger/CSrankings#595]
Hello,

I looked at the FAQ and I didn't find the answer to this question. I thought I should ask here instead of reading the source code, it seemed an overkill.

- Imagine a department has 50 professors, but only 25 are able to publish in the top conferences. The others do not. Does it matter in the ranking if one registers only the 25 productive faculty instead of all 50?

As far as I understand it doesn't matter, but I wanted to double check that there are no incentives to handpick the professors that go into the database.

Thanks!

**Comment by emeryberger** [comment]
Please include _all_ the professors that meet the inclusion criteria (no handpicking needed).
