### ISSUE TITLE
Game Research could be a category

### ISSUE THREAD

**Issue by siddu1998** [emeryberger/CSrankings#5951]
There should be a category for Games Research. I understand if people think that HCI would cover the Games Research. But the Game Researchers actively publish in conferences like ACM CHI PLAY, ACM FDG, IEEE CoG, CHI, and AIIDE. I feel students looking to understand universities in Game Design; Game research tends to choose HCI as their filter, which can be misleading. A great resource to understand Game Research Publications - https://www.kmjn.org/game-rankings/

**Comment by emeryberger** [comment]
The conferences listed here (except of course for CHI) are all ranked C on CORE Rankings (https://portal.core.edu.au/conf-ranks/); this is a deal-breaker for inclusion.
