### ISSUE TITLE
support to add MICCAI, IPMI, and ISBI conferences to CS Rankings process

### ISSUE THREAD

**Issue by rubyshamir** [emeryberger/CSrankings#602]
I support the petition to have the MICCAI, IPMI, and ISBI conferences considered in the CS Rankings process. These conferences are significant resources for my computer science research, collaborators, students, and staff; and we present major components of our computer science research and applications at these conferences. They are instrumental in the advancement of the scholarly works of my computer science department.

Thank you, 
Ruby Shamir, PhD
Computer Scientist

**Comment by francoismeyer** [comment]
I support the petition to have the MICCAI, IPMI, and ISBI conferences considered in the CS Rankings process. These conferences are significant resources for my research, collaborators, students, and staff; and we present major components of our  research and applications at these conferences. They are instrumental in the advancement of the scholarly works of my electrical and computer engineering department.

Francois G Meyer
Professor
Electrical, Computer, and Energy Engineering
University of Colorado at Boulder

**Comment by emeryberger** [comment]
See https://github.com/emeryberger/CSrankings/issues/558#issuecomment-342654550.
