### ISSUE TITLE
DBLP disambiguation

### ISSUE THREAD

**Issue by yulunalexliu** [emeryberger/CSrankings#6037]
The DBLP disambiguation is resolved regarding this PR https://github.com/emeryberger/CSrankings/pull/6028.
The updated DBLP is here https://dblp.org/pid/142/0282-1.html.
Thank you!

**Comment by yulunalexliu** [comment]
Not sure if I should open a new PR or if we could reopen the closed one.

**Comment by emeryberger** [comment]
Merged.
