### ISSUE TITLE
Consider publications in the MICCAI, IPMI, and ISBI in CS Ranking

### ISSUE THREAD

**Issue by lingucv** [emeryberger/CSrankings#605]
I am writing to give my strong support for the petition to have the MICCAI, IPMI, and ISBI conferences considered in the CS Rankings process. These conferences are significant resources for my computer science research, collaborators, students, and staff; and we present major components of our computer science research and applications at these conferences. They are instrumental in the advancement of the scholarly works of my computer science department.

**Comment by emeryberger** [comment]
See https://github.com/emeryberger/CSrankings/issues/558#issuecomment-345141772
