### ISSUE TITLE
Explain "# Pubs" better

### ISSUE THREAD

**Issue by koppor** [emeryberger/CSrankings#6084]
I checked "University of Stuttgart" and found Stefan Wagner.

The graph shows 1 publication.

![grafik](https://github.com/emeryberger/CSrankings/assets/1366654/cd721206-f2d7-4b00-b0c9-f4b797be752a)

I am not sure, how this number is calculated.

His dblp record shows a huge number of SE publications. Example:

![grafik](https://github.com/emeryberger/CSrankings/assets/1366654/f6548d3b-195a-4559-bbfa-bb9582c426bf)

I think, also for others, the number seems to be very low. Maybe, the metric is defined differently in CSrankings?

(Maybe, this refs https://github.com/emeryberger/CSrankings/issues/331).

**Comment by emeryberger** [comment]
Those are journals and not the conferences that CSrankings indexes (it indexes no journals that do not correspond to conference proceedings).

<img width="349" alt="Screenshot 2023-07-18 at 4 35 49 PM" src="https://github.com/emeryberger/CSrankings/assets/1612723/f18d050b-6ec8-497c-abb8-4a077cb87086">
