### ISSUE TITLE
Layout Broken in Firefox 57.0 (64-bit) on Ubuntu 16.04 

### ISSUE THREAD

**Issue by fycus-tree** [emeryberger/CSrankings#614]
![screenshot](https://user-images.githubusercontent.com/16022311/33001316-1da29384-cd7b-11e7-940e-dec2f1f63864.png)
1366 x768 resolution. 

This can be replicated by using [this web-based render preview](http://quirktools.com/screenfly), which just happened to be my first search result for "render preview website"

Checking the console log I got
TypeError: a.navigoRouter is undefined on csrankings.min.js:31:285
But this error also exists in Chrome, which renders correctly (caught TypeError: Cannot read property 'navigate' of undefined)

**Comment by emeryberger** [comment]
Forgot to push a fix last night. Pushed, should be fixed.

**Comment by emeryberger** [comment]
Nope, still broken. Working on it.

**Comment by emeryberger** [comment]
(Fixed)

**Comment by fycus-tree** [comment]
@emeryberger 

Still seems broken for me and via that [web-based tool](http://quirktools.com/screenfly/#u=http%3A//csrankings.org&w=1024&h=600)

It's all from this edit

```
 -   <link rel="stylesheet" href="css/csrankings.css">
 +   <link rel="preload" href="css/csrankings.css" as="style" onload="this.rel='stylesheet'">
 +    <noscript><link rel="stylesheet" href="css/csrankings.css"></noscript>
```

[Preload doesn't work in Firefox 57](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content)

> [1] This feature was available in Firefox 56, but only for cacheable resources. It has been disabled in Firefox 57 because of various web compatibility issues (e.g. bug 1405761). An improved version that works for non-cacheable resources is expected to land in Firefox 59.

**Comment by emeryberger** [comment]
Aha. I only use Chrome. I guess I need to test others. Will patch immediately.

**Comment by emeryberger** [comment]
When I run it in Firefox directly, seems to work fine. In the web-based tool, not so much. Not sure why.

**Comment by emeryberger** [comment]
For now, removed a bunch of asyncs. Probable race condition.
