### ISSUE TITLE
ICLR (Poster) not being considered

### ISSUE THREAD

**Issue by mcmachado** [emeryberger/CSrankings#6141]
DBLP entries for ICLR prior to 2020 are listed at DBLP such that papers that got an Oral presentation appear as "ICLR" and papers that were presented as posters appear as "ICLR (poster)". I believe the entries that are "ICLR (poster)" are not being considered, but they are just regular papers published in the conference. This can be seen by the breakdown, year by year, of oral/poster papers in this link: https://github.com/lixin4ever/Conference-Acceptance-Rate.

I suggest ICLR papers that are listed as ICLR (poster) to also be considered as ICLR papers, because they are. Otherwise we're using a standard for ICLR that is different than the standard we use for the other conferences.

Thanks in advance.

**Comment by songfu1983** [comment]
To my knowledge, posters of ICSE, ASE and ESEC/FSE are not considered as regular papers. Rare conferences regard posters as regular or research papers.

**Comment by mcmachado** [comment]
But this is different in ML conferences. Proof of this is that ICLR did not stop having papers accepted as poster, spotlight, oral, but DBLP stopped labelling them as such. This is an anomaly for ICLR prior to 2020.

**Comment by florianReitz-tr** [comment]
I work for dblp. From our perspective all publications of ICSE are of the same category ( i.e. inproceedings). This is true to all conferences. We do not distinguish between full papers, posters, etc. The line between these categories is often difficult to draw and as was pointed out above, different communities have very different understanding what these terms mean. For some conferences, i.e., https://dblp2.uni-trier.de/db/conf/iclr/iclr2019.html, we obtain groupings of papers. Here it is 'Oral Presentations' and 'Poster Presentations'. These can appear in the <booktitle> field in the data export. In other cases, papers are grouped by topic, date of presentation ...  

It is difficult to tell how to handle these categories in scientometrics. But please consider the following: for the majority of conferences dblp has just 'inproceedings'. I.e., we do not have data on the type of publication. Differentiating for conferences where we have the data punishes them just on the basis of better data availability.

**Comment by emeryberger** [comment]
Thanks @florianReitz-tr. Is this something that the ICLR folks could / should handle with you all? Or is it best that I special-case it?

**Comment by florianReitz-tr** [comment]
I think it is best you handle this as a special case. We could remove the '(Poster)' part from the booktitle, but this would loose us a little bit of information.

**Comment by emeryberger** [comment]
Thanks @florianReitz-tr, will do. Merging this PR, will re-build: https://github.com/emeryberger/CSrankings/pull/6382
