### ISSUE TITLE
Separating faculty members in the different universities into diffferent files

### ISSUE THREAD

**Issue by xiongyingfei** [emeryberger/CSrankings#627]
Most of the pull requests are dealing with faculty in a single university. Separating each university into an independent file could greatly avoid conflicts.

**Comment by emeryberger** [comment]
Separate files would greatly increase download times for users. Since the number of users far exceeds the number of GitHub PRs (by almost three orders of magnitude), I am optimizing for them :).

**Comment by xiongyingfei** [comment]
I think that is a separate issue. You may have files to contain the original data, and files to be generated from the original data for web viewing.

**Comment by emeryberger** [comment]
This is of course true. It's a ton of files, though, and I don't yet see conflicts as that much of an issue for many people. But I will think about it.
