### ISSUE TITLE
Please add Leiden University

### ISSUE THREAD

**Issue by sunnweiwei** [emeryberger/CSrankings#6286]
I found that CSRanking doesn't have **Leiden University**.  I tried to add Leiden University and four of its professors but no permissions. https://github.com/emeryberger/CSrankings/pull/6285 Could you please add Leiden University to CSRanking? Thanks for your help!

> Leiden University (https://www.universiteitleiden.nl/en) is a public research university in Leiden, Netherlands. It was founded in 1575 and is one of the leading international research universities in Europe.

**Comment by emeryberger** [comment]
The instructions are pretty clear: when adding an institution, _all_ faculty in CS must be added with the same pull request. Moreover, _only_ faculty who meet the inclusion criteria should be added. Please read the instructions carefully and try again. Thanks.
