### ISSUE TITLE
Duplicate author entries

### ISSUE THREAD

**Issue by benjholla** [emeryberger/CSrankings#629]
I noticed one case, but there may be more. In the csrankings.csv, Aiken is listed twice under different first names. Should these be consolidated or is this intentional?

`Alex Aiken,Stanford University,https://theory.stanford.edu/~aiken/,NOSCHOLARPAGE`
...
`Alexander Aiken,Stanford University,https://theory.stanford.edu/~aiken/,3vKjkoQAAAAJ`

**Comment by emeryberger** [comment]
It's intentional and required (right now). The logic currently depends on all aliases being present in the DB. I will fix Alex's missing scholar entry, though. Thanks!
