### ISSUE TITLE
How does CS Ranking process the faculties who unfortunately passed away?

### ISSUE THREAD

**Issue by Junjie-Chu** [emeryberger/CSrankings#6290]
Some professors have unfortunately passed away, but CS Ranking still includes them, for example Anders Robertsson from Lund University, Sweden (according to this post: https://www.linkedin.com/posts/department-of-automatic-control-lund-university_dear-colleagues-it-is-our-sad-duty-to-inform-activity-7053705502848880640-pObW/?originalSubdomain=dk). I am not sure if this is correct from the view of CS Ranking?

**Comment by emeryberger** [comment]
They should be moved to `old/rip.csv`.

**Comment by Junjie-Chu** [comment]
Thanks for your answer!

**Comment by emeryberger** [comment]
I would welcome a PR to do this for this faculty member.
