### ISSUE TITLE
Hamad Bin Khalifa University appearing in the USA category

### ISSUE THREAD

**Issue by quettabit** [emeryberger/CSrankings#632]
@emeryberger I checked the country-info.csv file. The entry seems right. But in the UI view, the university is not appearing in the Asia category and instead is appearing in the USA category. I have attached a screenshot of the issue. 
![hamad_bug](https://user-images.githubusercontent.com/27509167/33282762-a997c844-d377-11e7-8de9-49a4d6ff2407.png)

**Comment by emeryberger** [comment]
Fixed. The country-info entry had a typo ("Univerity") which was easily missed...

**Comment by emeryberger** [comment]
(Thanks for the report!)
