### ISSUE TITLE
Consider to add ICDE to Database

### ISSUE THREAD

**Issue by xu-cheng** [emeryberger/CSrankings#644]
The same request is brought up in issues #122, but was rejected due to three venues limit per area.

However, it is worthy noting that there are currently only two conferences included in the database area. The VLDB and PVLDB are the same venue.

https://github.com/emeryberger/CSrankings/blob/93ad3ab95a182422770ed979aeb7d8fffbbc726d/util/csrankings.py#L85

**Comment by emeryberger** [comment]
(a) Yes, I am aware that PVLDB and VLDB are (now) the same venue. That logic is there for a reason; VLDB wasn't always PVLDB.
(b) A number of areas have only two top conferences. See PL and OS, for example.
