### ISSUE TITLE
CSrankings but for professors?

### ISSUE THREAD

**Issue by osalbahr** [emeryberger/CSrankings#6478]
Is there a way to display the same data, but sort by professor rather than by university? I'd like to know, for example, which professors published the most in which areas/conferences (and, from that, conclude which areas a certain professor is most active in).

**Comment by osalbahr** [comment]
I noticed that there is a bar chart next to each professor which helps with knowing an individual professor's areas on interest

**Comment by ninghaohello** [comment]
I do not think CSranking is qualified to do so.

**Comment by ninghaohello** [comment]
CSrankings but for every particle in the universe?

**Comment by ninghaohello** [comment]
Criticizing something nonsensical is easy, but I think a more crucial task is to let young students know why every ranking is limited and even not close to being good, and what are the negative impacts if a ranking is abused.
