### ISSUE TITLE
RWTH Aachen University is not listed

### ISSUE THREAD

**Issue by LKlinke** [emeryberger/CSrankings#6535]
On the website, RWTH Aachen University is not listed.
However, RWTH Aachen is listed as a US University which is not correct.

Looking into the repository, it seems that the institutions file contains both RWTH Aachen and RWTH Aachen University which might be misleading. In the country-info.csv there is just an entry for RWTH Aachen University (which is correct).

Is there an easy fix for this?

**Comment by emeryberger** [comment]
I'm just going to search and replace all RWTH Aachen with RWTH Aachen University.

**Comment by emeryberger** [comment]
Just pushed.
