### ISSUE TITLE
Permanet URLs for region and publication years

### ISSUE THREAD

**Issue by mtov** [emeryberger/CSrankings#665]
Hi,

Currently, we have permanent URLs for regions and research areas, like:

http://csrankings.org/#/index?soft&southamerica

Is it possible to also support publication years in URLs?

For example, to select only publications in the last 4 years (instead of 10 years, as the default).

Thanks

**Comment by emeryberger** [comment]
I had wanted to put this in before; just added it with https://github.com/emeryberger/CSrankings/commit/e217d299b3648f22d1e7ef38d0bb76765cbe1317.
