### ISSUE TITLE
Adding Top Computer Vision Conference Workshop Proceedings can add value

### ISSUE THREAD

**Issue by furkankirac** [emeryberger/CSrankings#6655]
The field of Computer Vision is evolving rapidly. Key forums for specialized and interactive research in this domain are often found in high-quality workshops. Prominent conferences like ECCV, CVPR, and ICLR are known for their valuable workshop proceedings. However, when examining the code filtering DBLP documents (filter.xq), it's noticeable that these important workshop proceedings from top conferences are overlooked. Including the following proceedings volumes could significantly enhance the evaluation of universities in the Computer Vision field. Below are the DBLP volume names of the top conference workshops as of today:

**ECCV Workshops**
1. ECCV Workshop BioAW
2. ECCV Workshop SMVP
3. ECCV Workshop on HCI
4. ECCV Workshops (1)
5. ECCV Workshops (2)
6. ECCV Workshops (3)
7. ECCV Workshops (4)
8. ECCV Workshops (5)
9. ECCV Workshops (6)
10. ECCV Workshops (7)
11. ECCV Workshops (8)
12. ECCV Workshops CVAMIA and MMBIA

**CVPR Workshops**
1. CVPR Workshops

**ICLR Workshops**
1. ICLR (Poster)
2. ICLR (Workshop Poster)
3. ICLR (Workshop)

Best regards

**Comment by emeryberger** [comment]
As since the inception of CSrankings, workshops are not eligible for inclusion (conferences only).
