### ISSUE TITLE
Chinese Academy of Sciences doesn't appear at all

### ISSUE THREAD

**Issue by jindongwang** [emeryberger/CSrankings#675]
Hi there, recently I've added some faculties from **Chinese Academy of Sciences**, and the pull requests got merged. But I really didn't see them on the webpage, which I think is not reasonable.
Those faculties have published a lot of papers at the top conferences, but they just did not appear at all. However, existing researchers with only 1 pubs do appear. This is not right.
Can you help me to check what is going on? The names of the faculties are:
- (Human Computer Interaction area) Yiqiang Chen,Chinese Academy of Sciences,http://rcpc.ict.ac.cn/YiqiangChen,LC3SwhEAAAAJ
- (Computer Vision area) Shiguang Shan,Chinese Academy of Sciences,http://vipl.ict.ac.cn/view_people.php?id=12,Vkzd7MIAAAAJ
- (Computer Vision area) Xilin Chen,Chinese Academy of Sciences,http://vipl.ict.ac.cn/view_people.php?url=xlchen&id=13,vVx2v20AAAAJ

I have confirmed that their DBLP names are correct.

**Comment by emeryberger** [comment]
No faculty members from Chinese Academy of Sciences are currently in the database (in `csrankings.csv`). Please try again.

**Comment by jindongwang** [comment]
@emeryberger I checked in the csv file, there are in. So what's going on... Still can't see them

**Comment by emeryberger** [comment]
I _just_ merged them. I will push the update momentarily.
