### ISSUE TITLE
Publication count for Walid G. Aref, Purdue

### ISSUE THREAD

**Issue by TiarkRompf** [emeryberger/CSrankings#677]
CSrankings lists 4 DB papers (VLDB+SIGMOD) for Walid G. Aref in 2007-2017, but DBLP shows 7 PVLDB and 3 SIGMOD.

**Comment by emeryberger** [comment]
CSrankings doesn't include non-research papers or those below 6 pages in length. See https://github.com/emeryberger/CSrankings/blob/gh-pages/util/regenerate-data.py#L256 (and others).

**Comment by TiarkRompf** [comment]
Ah ok, I didn't realize demos and tutorials aren't distinguished by their title or otherwise. Thanks.

**Comment by emeryberger** [comment]
No problem, thanks for checking!
