### ISSUE TITLE
Deadlock scenario when adding an institution

### ISSUE THREAD

**Issue by bishnudev01** [emeryberger/CSrankings#6814]
I tried [adding NYU Abu Dhabi](https://github.com/emeryberger/CSrankings/pull/6813) but it fails saying _This institution (NYU Abu Dhabi) was not found in `institutions.csv`_

When I [modify institutions.csv adding NYU Abu Dhabi](https://github.com/emeryberger/CSrankings/actions/runs/7595655311/job/20688470762), it says _ERROR: Invalid file modification (institutions.csv). Please only modify allowed CSV files._

**Comment by emeryberger** [comment]
This is a feature, not a bug. The common case is that people should not be modifying any files except those prescribed (e.g., csrankings-*.csv).
