### ISSUE TITLE
Add Nanjing University to the list of asia universities

### ISSUE THREAD

**Issue by zsf222** [emeryberger/CSrankings#682]
English home page of the department https://www.nju.edu.cn/EN/7f/6b/c7136a163691/page.htm

**Comment by emeryberger** [comment]
Not sure what the issue is here: Nanjing is already listed.

**Comment by zsf222** [comment]
Nanjing University is not listed in Asia university list

**Comment by emeryberger** [comment]
See https://github.com/emeryberger/CSrankings/blob/gh-pages/country-info.csv#L69.

**Comment by zsf222** [comment]
Many thanks!
