### ISSUE TITLE
FAST publications not processed correctly

### ISSUE THREAD

**Issue by vijay03** [emeryberger/CSrankings#684]
Example: for my profile, http://dblp.uni-trier.de/pers/hd/c/Chidambaram:Vijay

there are 2 SOSP papers, 1 OSDI paper, and 2 FAST papers in the last 10 years.

However, CSRankings displays the total count as 4, and not 5. I believe one of the two FAST papers is not getting added.

**Comment by emeryberger** [comment]
The DBLP entry for one of those papers has a single number for a page, so CSrankings assumes its page count is < 6 (and thus excludes it). Please reach out to DBLP to address this (dblp@dagstuhl.de) and copy me. Thanks.

http://dblp.uni-trier.de/rec/xml/conf/fast/ChidambaramSAA12.xml
