### ISSUE TITLE
PPoPP

### ISSUE THREAD

**Issue by ielhajj** [emeryberger/CSrankings#690]
With the addition of secondary conferences, it is surprising to see ICFP added as a secondary PL conference but PPoPP (and CGO) left out. Both are SIGPLAN conferences (http://www.sigplan.org/Conferences). PPoPP has a higher citation index than ICFP (CGO has the same):

PLDI (h5-index = 50)
POPL (h5-index = 46)
PPoPP & OOPSLA (h5-index = 37)
CGO & ICFP (h5-index = 27)

Why has ICFP been preferred over PPoPP (and CGO)?

**Comment by emeryberger** [comment]
This addition was based on the results of a survey of the PL community.

**Comment by ielhajj** [comment]
I think the strongest feature of CSRankings which makes it a great step forward is that it is metrics-based. The FAQs say:

> Unfortunately, the most influential rankings right now are those from US News and World Report, which is entirely reputation-based and relies on surveys sent to department heads and directors of graduate studies. By contrast, CSRankings is entirely metrics-based...

It seems contrary to the spirit of CSRankings to choose conferences based on surveys of opinions as opposed to metrics such as acceptance rates and h-index.

I have expressed similar concern for the choice of HPC conferences in #361.

**Comment by emeryberger** [comment]
This is not in any way comparable to the US News approach. These metrics are based on the conferences _that the community_ feels are most prestigious. Bibliometric approaches and the like often fall far short in this regard (consider, for example, the question of selectivity: is it because there is a lot of noise, or are most of the papers signal?).

**Comment by ielhajj** [comment]
Yes, agreed. I did not intend to compare to US News institutional ranking, just to extend the survey-vs-metric issue to conference ranking.

Thank you for the clarification. It seems survey vs. metric is already being discussed in #564. Sorry for duplicating the discussion.
