### ISSUE TITLE
Add PVLDB to Database area

### ISSUE THREAD

**Issue by eagichtein** [emeryberger/CSrankings#692]
Hello, 
Please include PVLDB (Proceedings of VLDB) to the Databases area. PVLDB papers are presented in VLDB, excluding papers sourced from PVDLB is inconsistent.
http://dblp.uni-trier.de/db/journals/pvldb/

Reference:
http://www.vldb.org/pvldb/pvldb-m2c.html

....
PVLDB allows continuous submissions throughout the year.
In addition to being accepted or rejected, submissions may also have revisions requested and invited for further review. Regardless of the submission type, all accepted papers are uniformly published in the next available issue of PVLDB and will be offered a presentation slot at the next available VLDB conference. Accepted papers will be published in PVLDB only; there will be no separate published conference proceedings. For presentation at the conference in any year, a paper must be accepted for PVLDB by a specified date in May of that year at the latest. Papers that are accepted much earlier (e.g. in January) will be published in an earlier PVLDB issue (e.g. in April) and will still be presented at the VLDB conference (e.g. in August).

**Comment by emeryberger** [comment]
PVLDB is already included (has been for some time).

See https://github.com/emeryberger/CSrankings/blob/gh-pages/util/regenerate-data.py#L62
