### ISSUE TITLE
Electrical engineering under computer science is inconsistent

### ISSUE THREAD

**Issue by dmgerman** [emeryberger/CSrankings#698]
I am wondering, why are electrical engineering departments listed along computer science in some universities and not in others? Is there any policy regarding this? Or is it just a matter of adding also the electrical engineering faculty to the dataset?

thank you.

**Comment by emeryberger** [comment]
Yes, there is a policy, and no, it is not just a question of adding EE faculty. See the inclusion criteria here: https://github.com/emeryberger/CSrankings/blob/gh-pages/CONTRIBUTING.md
