### ISSUE TITLE
a DBLP entry error

### ISSUE THREAD

**Issue by inspiron221** [emeryberger/CSrankings#699]
Prof. Kai Yu of Shanghai Jiao Tong University should be Kai Yu 0004 in dblp, not Kai Yu 0001. Kai Yu 0001 is a machine learning expert, now CEO of Horizon Robotics Inc (Former Leader of Institute of Deep Learning, Baidu Inc).

**Comment by emeryberger** [comment]
Thanks. Fixed with https://github.com/emeryberger/CSrankings/commit/11a13f1ea2cd1d0dfeec3e52a7fcdeb183b74357.
