### ISSUE TITLE
Error when adding UMass Dartmouth CIS Department faculties

### ISSUE THREAD

**Issue by yluo39github** [emeryberger/CSrankings#7042]
I attempted to add UMass Dartmouth CIS faculties with https://github.com/emeryberger/CSrankings/pull/7041, but encountered the ERROR: "This institution (University of Massachusetts Dartmouth) was not found in institutions.csv." However, I am unable to alter the file institutions.csv.

**Comment by emeryberger** [comment]
That's to be expected but in any event, UMass Dartmouth does not appear to have a PhD program in Computer Science and as such is ineligible for inclusion.

**Comment by emeryberger** [comment]
Never mind, found this: https://www.umassd.edu/engineering/graduate/doctoral-degree-programs/egr-and-applied-science-phd/csis-option/

**Comment by yluo39github** [comment]
Dear Dr. Emery, Thank you very much for providing a detailed explanation regarding this case. 
We're focused on boosting our community impact, and as noted, our Engineering and Applied Sciences (EAS) program includes a CSIS concentration, allowing most faculty to mentor PhD students.
