### ISSUE TITLE
Are NAACL Finding papers indexed by CSRanking?

### ISSUE THREAD

**Issue by ghost** [emeryberger/CSrankings#7118]
Hello Mr/Mrs,

I am writing to inquire whether NAACL Finding papers are indexed by CSRanking. Currently, I have observed that the NAACL conference is recognized by CSRanking, and I have also found a [NAACL Finding paper](https://dblp.org/db/conf/naacl/index.html) listed on DBLP. To clarify, I would like to know if all NAACL Finding papers are included in the CSRanking index, or if the one I came across is an exception.

The attached images are where I found the indexed NAACL paper on DBLP.

Best regards,
![Screenshot_2024-04-17_at_10_56_51 AM](https://github.com/emeryberger/CSrankings/assets/17596799/0599f018-40c9-4e7a-8bc2-f42c3a54048b)
![Screenshot_2024-04-17_at_10_57_03 AM](https://github.com/emeryberger/CSrankings/assets/17596799/9c64d138-bad9-4cee-8038-9b11b934adfa)

Tin

**Comment by jvladika** [comment]
Hi Tin,

you can see in the source code (in the [csrankings.py](https://github.com/emeryberger/CSrankings/blob/gh-pages/util/csrankings.py) file) all the strings used to index different conferences in DBLP. 

It appears that for NAACL only the different aliases are included (NAACL, NAACL-HLT, HLT-NAACL), but the "NAACL (Findings)" format is not included. It is it the same story for ACL and EMNLP. This means that Findings papers are currently not included in the rankings.

Best,
Juraj
