### ISSUE TITLE
Publication count is incorrect

### ISSUE THREAD

**Issue by janeadams** [emeryberger/CSrankings#7153]
The number of publications shown next to each professor's name doesn't match the number of publications listed in the DBLP link next to their name

**Comment by emeryberger** [comment]
Not a bug but a feature. Only full-length publications published in the CSrankings conferences (click the triangles on the left side) count.

**Comment by janeadams** [comment]
I don't think this is correct -- for example, for IEEE VIS, these authors definitely have more than this number of full papers published
![Screenshot 2024-05-08 154442](https://github.com/emeryberger/CSrankings/assets/18581006/b383ac5a-c6d4-4e98-9f51-bd7ecb1d12ea)

If you filter to only show IEEE VIS and then click the dblp entries for any prof, you'll see that the number of full conference papers far exceeds the listed number in csrankings

**Comment by janeadams** [comment]
Oh I figured out the issue -- IEEE VIS publishes all its full papers in TVCG. So full papers for IEEE VIS don't count at all toward the metric -- despite IEEE VIS being the premiere visualization conference in our field. So all you're seeing is vis short papers in the tally I think. This makes the CS rankings for the whole field of vis not very useful/accurate.

Edit to add: it goes the other direction too -- anything published in TVCG is presented as a full paper at VIS the following year. So TVCG is functionally the conference proceedings for VIS.

**Comment by emeryberger** [comment]
It counts TVCG papers from a specific volume for VIS, though it looks like it's missing 2024; if you can confirm that it is still volume 1, I will update. From `util/csrankings.py`:

```# TVCG special handling to count only IEEE VIS
TVCG_Vis_Volume = {
    2023: (29, 1),
    2022: (28, 1),
    2021: (27, 2),
    2020: (26, 1),
    2019: (25, 1),
    2018: (24, 1),
    2017: (23, 1),
    2016: (22, 1),
    2014: (20, 12),
    2013: (19, 12),
    2012: (18, 12),
    2011: (17, 12),
    2010: (16, 6),
    2009: (15, 6),
    2008: (14, 6),
    2007: (13, 6),
    2006: (12, 5),
}
```

**Comment by janeadams** [comment]
Are we sure that there should be volumes specified at all? I think that all TVCG should be included; if a full paper is submitted directly to TVCG on the rolling deadline instead of the conference deadline, it still goes through the same reviewing process and is presented at the conference the following year. For example, just from a quick scan:

- 2020 should also have (26, 3) (you can see that [this paper](https://doi.org/10.1109/TVCG.2018.2876539) was presented at vis [here](https://ieeevis.org/year/2019/assets/vis19-printout.pdf))
- 2022 should have (28, 10) e.g. [this paper](https://doi.org/10.1109/TVCG.2021.3064037) was [presented at IEEE VIS in 2021](https://virtual.ieeevis.org/year/2021/session_v-full-full9.html)

EDIT to add: You can also see numerous papers listed directly on the[ IEEE VIS site](https://ieeevis.org/year/2024/info/call-participation/area-model) as key example papers of the caliber/type accepted to the conference which don't have volume numbers reflected in the list, like [this one](https://ieeexplore.ieee.org/document/8730513) (26(11)), [this one](https://ieeexplore.ieee.org/document/8307265) (25(3)), and [this one](https://ieeexplore.ieee.org/document/7583708) (23(9)).

From what I can tell, the TVCG edition increments by 1 each year (so 2024 should be vol. 30), and the second number shouldn't matter at all. I think a large swath of VIS research is being excluded because of this.

Thanks for your rapid attention, this is a wonderful resource

**Comment by emeryberger** [comment]
My understanding (possibly out of date!) is that different volumes of TVCG correspond to either VIS or VR. For example: (also note that I should have said _issue #_ and not _volume_)

```
# TVCG special handling to count only IEEE VR
TVCG_VR_Volume = {
    2023: (29, 5),
    2022: (28, 5),
    2021: (27, 5),
    2020: (26, 5),
    2019: (25, 5),
    2018: (24, 4),
    2017: (23, 4),
    2016: (22, 4),
    2015: (21, 4),
    2014: (20, 4),
    2013: (19, 4),
    2012: (18, 4),
}
```

**Comment by mcorrell** [comment]
I can at least confirm that [Volume 30, Issue 1](https://ieeexplore.ieee.org/xpl/tocresult.jsp?isnumber=10373160&punumber=2945) is the issue of TVCG the contains the papers submitted to IEEE VIS 2023 along with other usual conference proceedings material. As your post-2016 data suggests, the plan is to continue making the first issue of TVCG the IEEE VIS proceedings issue for the foreseeable future, with the caveats about other sources of IEEE VIS content mentioned above.

**Comment by janeadams** [comment]
Ah yes it does seem to be more complex than I knew. I'm told that this is the best resource for all papers: https://sites.google.com/site/vispubdata/data-details

But I'm not sure how best to map that back to CSrankings given how many edge cases appear here
