### ISSUE TITLE
Failure to load with uBlock Origin

### ISSUE THREAD

**Issue by fycus-tree** [emeryberger/CSrankings#718]
Gets stuck on "Computing ranking."

Repeatable through
http://quirktools.com/screenfly/#u=http%3A//csrankings.org&w=1024&h=600

**Comment by emeryberger** [comment]
Just tried it; works for me through the URL given and on Firefox (Mac), 58.0.1 (64-bit).

**Comment by fycus-tree** [comment]
I have diagnosed that the problem was due to my use of an ad blocker. Apparently "freegeoip" is on the EasyList blocking list and it's inclusion (in it's new form, tied to a recent commit) lead to the issue. Just an FYI

https://easylist.to/easylist/easyprivacy.txt
https://github.com/emeryberger/CSrankings/commit/1b16a13faee474083a66591839c18322f7188132

**Comment by emeryberger** [comment]
Nice. Thanks for the diagnosis. I just put the geoCheck logic in a try-catch; can you test if it now works even with the ad blocker on?

**Comment by fycus-tree** [comment]
Doesn't seem to fix it. Ad blocker is uBlock Origin. May be an issue on their end?  Same extension on Chrome seems to have the same issue.

**Comment by emeryberger** [comment]
Ok, got it. Tested and verified on my end (with uBlock Origin) that this now works, even in the face of ad blocking. Thanks!
