### ISSUE TITLE
Institution not found in institutions.csv

### ISSUE THREAD

**Issue by cesarlincoln** [emeryberger/CSrankings#7255]
I am trying to add UFC (Federal University of Ceará) [CS faculties](http://www.mdcc.ufc.br/component/content/article/34-fixo/140-presentation) with https://github.com/emeryberger/CSrankings/pull/7254, but encountered "ERROR: This institution (UFC) was not found in institutions.csv". How to proceed, since institutions.csv is unwritable?

**Comment by jay-tau** [comment]
In addition to `country-info.csv`, you will also need to update [`institutions.csv`](https://github.com/cesarlincoln/CSrankings/blob/gh-pages/institutions.csv)

**Comment by emeryberger** [comment]
I handle these cases manually (the validation script is deliberately designed to reject such alterations, but that does not prevent me from merging them).
