### ISSUE TITLE
Request to Merge Pull Request #7349 for Adding Sichuan University

### ISSUE THREAD

**Issue by He-Changhao** [emeryberger/CSrankings#7350]
Hello, I noticed that [Sichuan University](https://en.scu.edu.cn/) was not included in the previous country-info.csv and institutions.csv files. I referred to your previous responses to an issue and made a [pull request #7349](https://github.com/emeryberger/CSrankings/pull/7349), including adding relevant entries to the [country-info.csv](https://github.com/emeryberger/CSrankings/blob/gh-pages/country-info.csv) and csrankings-[a-z].csv files. 

However, as you mentioned in [#7255](https://github.com/emeryberger/CSrankings/issues/7255), we cannot directly commit to [institutions.csv](https://github.com/emeryberger/CSrankings/blob/gh-pages/institutions.csv). We suspect that this might require your permissions to handle.

Could you please check if our [pull request #7349](https://github.com/emeryberger/CSrankings/pull/7349) is correct and merge it? 

Thank you very much for your help.

**Comment by emeryberger** [comment]
I manually audit all PRs. Yours will be handled in due time. As the guidelines state, "please don't contact us for at least three months for updates".

**Comment by He-Changhao** [comment]
> I manually audit all PRs. Yours will be handled in due time. As the guidelines state, "please don't contact us for at least three months for updates".

Hello,

Thank you for your previous response. I understand that all PRs are manually audited and that the process can take time. However, it has now been over three months since I submitted the pull request (#7349) to add Sichuan University, and there hasn’t been any update regarding its status.

Could you kindly provide an update on the current status of the review process for the pull request? We would really appreciate it if you could let us know if there are any issues or additional steps we should take to facilitate this process.

Thank you for your time and attention to this matter.
