### ISSUE TITLE
Extended abstracts not counted towards the ranking

### ISSUE THREAD

**Issue by MariusGarbea** [emeryberger/CSrankings#7364]
Some conferences (such as EC - Economics and Computation) allow for extended abstract submissions. Here is the description of what an extended abstract is:

One-page extended abstract option. To accommodate the publishing traditions of different fields, authors of accepted papers can ask that only a one-page abstract of the paper appear in the proceedings, along with a URL pointing to the full paper. Authors should guarantee the link to be reliable for at least two years. This option is available to accommodate subsequent publication in journals that would not consider results that have been published in preliminary form in conference proceedings. Such papers must be submitted electronically and formatted just like papers submitted for full-text publication.

Please note that although a paper may be submitted as an extended abstract, it still goes through the same admission process and if accepted, is thus part of the proceedings just like any full paper. This means that if some authors choose this option and get accepted, the CSRankings website will not count this publication, as it is below the 6-page threshold that seems to filter publications.

For now, I don't see exactly what the best choice for including this change is, but I believe lowering the page threshold is probably not a good idea, so some local changes for specific conferences may be the way to go.

Here is the submission instruction page for EC, for reference: https://ec24.sigecom.org/call-for-contributions-acm/papers/.

**Comment by emeryberger** [comment]
Thanks for the note. I was actually aware of this policy. As with every other field of computer science, only full conference papers will be indexed by CSrankings.

**Comment by brianhzhang** [comment]
Respectfully, I would like to protest this decision.

Within the economics & computation area, EC is the premier conference. As mentioned by the above comment: extended abstracts and full papers go through the same review process. Indeed, all papers presented as EC are _submitted and reviewed as full papers_, and only _after acceptance_ do authors decide whether they wish for their papers to be published as extended abstracts or full papers. 

There is very little incentive for authors to publish full papers at EC: extended abstracts are always accompanied by a link to the full paper on e.g. arXiv, and the option allows authors to send their papers to journals afterwards. As such, at EC 2023, a whopping [110 out of 160 papers](https://dl.acm.org/doi/proceedings/10.1145/3580507) were published as extended abstracts. (Although I haven't checked, I imagine other years are similar.)

By excluding these extended abstracts, CSRankings is therefore missing out on over 2/3 of the papers at the premier conference in the economics and computation area. Different authors might also have different practices regarding the extended abstract option---I know of several authors who will basically _always_ use the extended abstract option at EC; such authors have _almost none_ of their EC publications counted by CSRankings, and are thus are currently heavily punished (if not outright excluded!) by the rankings. This renders the area rankings for economics and computation extremely skewed.

Is there any way at all that extended abstracts can be treated on a conference-by-conference basis, or at least that an exception can be made for obvious cases, such as this, where extended abstracts clearly ought to be counted equally to full papers?

**Comment by jasonhartline** [comment]
As former program chair for EC, I strongly agree that EC extended abstracts need to be counted.  It is an error that misrepresents the best papers in the field not to count them.

In many fields, short papers such as two page abstracts are not considered to be the same quality and publication status as the longer format paper.  In EC they are considered the exact same as long format papers.  They are submitted and reviewed as long papers and they are considered published with respect to CS conferences.  I.e. they cannot be submitted again to another archival conference.   

The two page format is only to accommodate publishing the journal version of the paper in economics venues which is very important for the interdisciplinary success of the field.  

It is wrong to punish authors for doing the work to disseminate their papers in econ journals by not counting these papers in EC.

From my experience, the way to tell paper from a non-paper is not the length, it whether a long version can be submitted to another conference.
