### ISSUE TITLE
Checking homepage URL received error code 412.

### ISSUE THREAD

**Issue by qinzhang11** [emeryberger/CSrankings#7452]
[commit_validation](https://github.com/emeryberger/CSrankings/actions/runs/10164788882/job/28111049620?pr=7451#logs)
Checking homepage URL (https://csse.szu.edu.cn/pages/user/index?id=1151)
WARNING: Received error code 412.
WARNING: Invalid homepage URL (https://csse.szu.edu.cn/pages/user/index?id=1151). Please provide a correct URL.

Actually the homepage is correct. Please check workflow.

**Comment by emeryberger** [comment]
Should be fixed with https://github.com/emeryberger/CSrankings/commit/984487ccf74265b0e7bdd402a5b94dcad1773fe9.
