### ISSUE TITLE
Many Professors are missing for Chinese Academy of Sciences

### ISSUE THREAD

**Issue by wentaozhu** [emeryberger/CSrankings#748]
Dear Prof. Berger,

There are only 5 professors for Chinese Academy of Sciences in the current CSrankings.

I add several professors I know into the csrankings.csv in the following.

Hope it can be added into CSrankings sooner.

Thanks,
Wentao

Liang Wang,Chinese Academy of Sciences,http://www.cbsr.ia.ac.cn/users/liangwang/,8kzzUboAAAAJ
Junliang Xing,Chinese Academy of Sciences,https://sites.google.com/site/junliangxing/,jSwNd3MAAAAJ
Kaiqi Huang,Chinese Academy of Sciences,http://people.ucas.ac.cn/~huangkaiqi?language=en,caQ-OmYAAAAJ
Tieniu Tan,Chinese Academy of Sciences,http://english.cas.cn/about_us/administration/administrators/201409/t20140926_128522.html,W-FGd_UAAAAJ
Zhennan Sun,Chinese Academy of Sciences,http://www.cbsr.ia.ac.cn/users/znsun/,PuZGODYAAAAJ
Ruiping Wang,Chinese Academy of Sciences,http://vipl.ict.ac.cn/homepage/rpwang/index.htm,duIUwpwAAAAJ
Xueqi Cheng,Chinese Academy of Sciences,http://www.bigdatalab.ac.cn/~cxq/,hY8aLqAAAAAJ
Yu Qiao,Chinese Academy of Sciences,http://mmlab.siat.ac.cn/yuqiao/index.html,gFtI-8QAAAAJ
Qingming Huang,Chinese Academy of Sciences,http://people.ucas.edu.cn/~0003060?language=en,J1vMnRgAAAAJ
Xiujuan Chai,Chinese Academy of Sciences,http://people.ucas.edu.cn/~0032526?language=en,ZcL91HsAAAAJ
Shuqiang Jiang,Chinese Academy of Sciences,http://vipl.ict.ac.cn/homepage/jsq/,4Rvn-ykAAAAJ
Hong Chang,Chinese Academy of Sciences,http://vipl.ict.ac.cn/view_people.php?url=&id=54,LX6MnNsAAAAJ
Hu Han,Chinese Academy of Sciences,https://sites.google.com/site/huhanhomepage/publication,4v709-MAAAAJ
Meina Kan,Chinese Academy of Sciences,http://vipl.ict.ac.cn/homepage/mnkan/index.html,4AKCKKEAAAAJ
Shuhui Wang,Chinese Academy of Sciences,http://vipl.ict.ac.cn/view_people.php?url=&id=62,h-JxBSYAAAAJ
Qianqian Xu,Chinese Academy of Sciences,http://vipl.ict.ac.cn/view_people.php?url=qianqianxu&id=155,MjifS2MAAAAJ
Bingpeng Ma,Chinese Academy of Sciences,http://people.ucas.edu.cn/~bpma,fClDLgMAAAAJ
Xiang Ao,Chinese Academy of Sciences,http://mldm.ict.ac.cn/MLDM/~aox/,W8wrWfMAAAAJ
Qing He,Chinese Academy of Sciences,http://people.ucas.edu.cn/~0000964?language=en,zT-zZucAAAAJ
Fuzhen Zhuang,Chinese Academy of Sciences,http://www.intsci.ac.cn/users/zhuangfuzhen/index.htm,klJBYrAAAAAJ
Ping Luo,Chinese Academy of Sciences,http://mldm.ict.ac.cn/MLDM/luoping/,d5L-OV4AAAAJ
Xiaojiang Peng,Chinese Academy of Sciences,https://pengxj.github.io/,7oRD67kAAAAJ

**Comment by emeryberger** [comment]
Hi - can you please make this a pull request? Thanks!
