### ISSUE TITLE
Question about professors in the Department of engineering and Department of Statistics

### ISSUE THREAD

**Issue by JinJinSang** [emeryberger/CSrankings#7606]
Dear Emery,

I come from Oxford. I have just found that most of the professors in Oxford whose research focus on robotics, computer vision, and machine learning are not included in the csranking. I found the reason that computer science department in Oxford only includes these faculty focusing on theoretical computer science. And the robotics computer vision, and NLP are seen as applied science and therefore the related faculties are in the Engineering science. Similarly, the machine learning faculties are in the statistics and math department. These faculties also publish on **top** conferences and journals that are included in csranking. For example, professor Philip Torr, Andrew Zisserman, Andrea Vedaldi, João Henriques, Paul Newman, and etc. There are many famous and powerful professors not included.

I am wondering how to add these faculties into the csranking list. Based on the 'pull request rule:  **_Faculty not in a CS department or similar who can advise PhD students in CS can be included regardless of their home department_**.' I found problem is that the PhD students of these faculties are also not in the computer science department although they are doing research either on robotics, computer vision, or machine learning.

**Comment by emeryberger** [comment]
CSrankings is for PhD students looking to get a PhD _in Computer Science_ (or the local equivalent). Faculty in other departments who cannot advise PhD students for a PhD _in Computer Science_ are ineligible for inclusion, no matter how "famous and powerful."
