### ISSUE TITLE
Request to Update Professor Xuemin Lin's Affiliation on CSRankings

### ISSUE THREAD

**Issue by qmy0701** [emeryberger/CSrankings#7608]
Dear CSRankings Team,

I hope this message finds you well. I am writing to request an update to Professor Xuemin Lin's affiliation on CSRankings. Currently, his profile lists him as affiliated with an Australian institution, but Professor Lin has now officially joined Shanghai Jiao Tong University, China. You can find his official faculty page here: [https://www.acem.sjtu.edu.cn/en/faculty/linxuemin.html](https://www.acem.sjtu.edu.cn/en/faculty/linxuemin.html).

We would greatly appreciate it if you could update his affiliation accordingly to reflect this change.

Thank you for your attention to this matter.

**Comment by emeryberger** [comment]
You need to do this via a pull request.
