### ISSUE TITLE
Don't work with students. Don't connect to industry. Don't collaborate.

### ISSUE THREAD

**Issue by sweirich** [emeryberger/CSrankings#770]
This part of issue #564 seems to have been dropped from the discussion. @emeryberger wants to create good incentives, but the current status seems particularly perverse. 

> First off, what CSRankings is telling us is that we should ditch our co-authors. If I could write a paper with one graduate student, but a second student also wants to participate, tough cookies. That’s the difference between getting 1/2 a point and 1/3 of a point. Sure, that additional student might improve the paper dramatically. They might also learn a thing or two. But on the other hand, they’ll hurt your rankings.
> 
> (Note: currently on CSRankings, graduate students at the same institution don’t get included in the institutional rankings. So including them on your papers will actually reduce your school’s rank.)
> 
> I hope it goes without saying that this could create bad incentives.

If I'm a student looking for an institution where I will find a vibrant group of faculty, postdocs, students and visitors to learn from and collaborate with, csrankings will lead me astray. In particular, csrankings has no indication of how successful institutions are at training students.

**Comment by sweirich** [comment]
Adding a link to a (closed) similar issue. 

#589 

I know this has been discussed before, but I still see a problem.

**Comment by emeryberger** [comment]
More authors means more papers. Normalizing means there is no bias towards one or the other.

**Comment by sweirich** [comment]
I fundamentally disagree. More authors mean better papers and better science. Not necessarily more papers.
