### ISSUE TITLE
CSrankings FAQ says that it considers papers with at least 6 pages. But the reports only includes 7 or more

### ISSUE THREAD

**Issue by dmgerman** [emeryberger/CSrankings#7761]
The FAQ says that "Note that publications must be at least 6 pages long to be counted."

The reports of CSrankings appear to be ignoring  some papers of 6 pages. Here are two examples:

In 2022:

pubkey conf/kbse/JungK0ZL021

authors: Kyu Hyung Lee, Weihang Wang 0001

conference: ASE.

This paper is not counted.

This other paper is not counted either: conf/kbse/AlrajehBU21, same conference and year: ASE 2022.

**Comment by emeryberger** [comment]
Publications need to be _at least_ 6 pages long. However, short papers are excluded.

From `util/csrankings.py`:

```
# ASE accepts short papers and long papers. Long papers appear to be at least 10 pages long,                          
# while short papers are shorter.                                                                                     
ASE_LongPaperThreshold = 10
```
