### ISSUE TITLE
Update Conference Name: FSE Renamed to Proceedings of the ACM on Software Engineering

### ISSUE THREAD

**Issue by petertsehsun** [emeryberger/CSrankings#7799]
Dear CSRankings,

The conference FSE (ACM SIGSOFT Symposium on the Foundations of Software Engineering) has been officially renamed to Proceedings of the ACM on Software Engineering - Number FSE. FSE becomes similar to VLDB, where the publications will appear as journal papers on the ACM website. The updated DBLP page is here: https://dblp.org/db/journals/pacmse/pacmse1.html

In the CSRankings dataset, FSE should be updated to reflect its new title, Proceedings of the ACM on Software Engineering - FSE. This will help maintain consistency with the official ACM naming and ensure accuracy for researchers and institutions referencing the rankings. Thank you very much for your help.

Best Regards,
Peter

**Comment by emeryberger** [comment]
Updated with https://github.com/emeryberger/CSrankings/commit/6b7fc3c0982ad12ed5fd6d1a1facfd8c81e62abb (it will still be listed on the website as FSE).
