### ISSUE TITLE
Request to add Associate Professor Ruonan Liu to CSRankings

### ISSUE THREAD

**Issue by Ruonansgroup** [emeryberger/CSrankings#7852]
Dear CSRankings Team,

I hope this message finds you well. I am writing to request an addition of Associate Professor Ruonan Liu's information to CSRankings. She is currently a tenure-track associate professor in Department of Automation, Shanghai Jiao Tong University. You can find her official faculty page here: [https://automation.sjtu.edu.cn/Ruonan](https://automation.sjtu.edu.cn/Ruonan), and you can also find her personal page here: [ruonanliu.com](http://ruonanliu.com/). 

We would greatly appreciate it if you could add her information accordingly.

Thank you for your attention to this matter.

**Comment by emeryberger** [comment]
You need to add this faculty member via a pull request.
