### ISSUE TITLE
Missing volumes for cryptography conferences

### ISSUE THREAD

**Issue by stessaro** [emeryberger/CSrankings#7903]
Unfortunately, the use of LNCS for the proceedings of the two flagship cryptography conferences, CRYPTO/EUROCRYPT is forcing them to increase the number of published volumes each year. At a quick glance, it seems that not all volumes from the last editions of these conferences are included in csrankings. I supposed this problem will keep happening (I had also noticed a similar issue last year), and I am not sure whether there is an easy fix for it. 

Thank you!

**Comment by emeryberger** [comment]
This should be up to date for now. (See the file `filter.xq`.)
