### ISSUE TITLE
Update of the dblp.xml.gz file

### ISSUE THREAD

**Issue by musialski-lab** [emeryberger/CSrankings#7907]
Dear @emeryberger,

Thank you for your efforts in maintaining these rankings. I agree that quarterly updates are sufficient. However, I noticed that the database file [dblp.xml.gz](https://github.com/emeryberger/CSrankings/blob/gh-pages/dblp.xml.gz) has not been updated for some time, so recent publications are currently not included.

Could we please update this file? I am also happy to assist by submitting a pull request with an update if needed.

Thank you and best regards,  
Przemyslaw

**Comment by emeryberger** [comment]
As the web page states, I update DBLP every 3 months. It requires work on my part to update faculty names that now have disambiguation suffixes, etc., so a PR is not helpful. Thanks for the offer, though.
