### ISSUE TITLE
Issues with URL validation in PR #7337

### ISSUE THREAD

**Issue by hoonose** [emeryberger/CSrankings#7939]
PR #7337 previously failed URL validation for the following two URLs:
https://pages.stern.nyu.edu/~atuzhili/
https://pages.stern.nyu.edu/~xchen3/index.html

It seems the issue is due to the following error:
`ERROR: An exception occurred with requests: HTTPSConnectionPool(host='pages.stern.nyu.edu', port=443): Max retries exceeded with url: /~atuzhili/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))). Failing over to Selenium...`

Note that these URLs indeed work. I have changed their URLs to alternatives that identify them, but that actually work. Nonetheless, flagging this in case it affects other PRs.

**Comment by emeryberger** [comment]
Not sure what the issue is; I suspect something on the CI side.
