### ISSUE TITLE
adding Theory of Cryptography Conference

### ISSUE THREAD

**Issue by zaumka** [emeryberger/CSrankings#7960]
Theory of Cryptography (TCC) is a flagship conference in cryptography. 
https://dblp.uni-trier.de/db/conf/tcc/index.html

Currently, only CRYPT and Eurocrypt are counted, but TCC is on par with these conferences. In algorithms and complexity, one counts STOC, FOCS and SODA. Not clear why in cryptography TCC is not counted, as it is roughly the same prestige as SODA in algorithms. 
Here are some rankings:
https://research.com/conference-rankings/computer-science/computer-security-cryptography

But we can also do it scientifically. Let's make a survey asking top cryptographers at CRYPTO/Eurocrypt:
https://www.iacr.org/cryptodb/data/stats.php?crypto=on&eurocrypt=on

Note, if you toggle TCC, you will see all top cryptographers frequently publish there. So, IMHO, there is no excuse not to include it in the rankings, while including SODA, for example.

**Comment by emeryberger** [comment]
While TCC may be a fine conference, the numbers and other sources indicate that TCC is not in the same equivalence class as CRYPTO and Eurocrypt.

* It receives no more than 1/3 of the number of submissions of CRYPTO and Eurocrypt (details below).
* Its most recent iteration had an acceptance rate of 40%. Compare to CRYPTO (27%) and Eurocrypt (21%).
* Per CORE rankings, TCC is ranked A while CRYPTO and Eurocrypt are both ranked A*.

From the front matter of the most recent proceedings:

## TCC 2023
> The total of 68 full papers presented in the proceedings was carefully reviewed and selected from 168 submissions. 

## CRYPTO 2024
> The 143 full papers presented in the proceedings were carefully reviewed and selected from a total of 526 submissions.

## EuroCrypt 2024
> The 105 papers included in these proceedings were carefully reviewed and selected from 500 submissions.
