### ISSUE TITLE
Computer graphics publications in 2007 are completely absent from database

### ISSUE THREAD

**Issue by fowlkes** [emeryberger/CSrankings#803]
There appears to be no info on computer graphics publications in 2007.
This can be seen through the web interface with this query:

  http://csrankings.org/#/fromyear/2007/toyear/2007/index?graph

or by looking at the generated-author-info.csv

**Comment by emeryberger** [comment]
Thanks for the report! Fixed with https://github.com/emeryberger/CSrankings/commit/b1b262d535ba30c4838712cfd7ee2b8d58fa6c25.
