### ISSUE TITLE
Half of ECCV 2024 papers are not indexed by dblp.xml.gz

### ISSUE THREAD

**Issue by shihaoji** [emeryberger/CSrankings#8053]
Half of ECCV 2024 papers are not index by dblp.xml.gz. Please see all ECCV 2024 papers at https://dblp.org/db/conf/eccv/index.html

**Comment by emeryberger** [comment]
Thanks for the report; this should be fixed.

**Comment by shihaoji** [comment]
Thanks, Emery. I appreciate your effort and quick response.
