### ISSUE TITLE
the ranking could have a count/faculty parameter

### ISSUE THREAD

**Issue by LucidMach** [emeryberger/CSrankings#8060]
as someone who used csrankings to shortlist universities for a masters (by coursework)
i think count/faculty would be more helpful

i would prolly use csrankings to find advisors for my phd down the line [ETA 1.5ish years]

**Comment by emeryberger** [comment]
This does not produce a meaningful result (the ranking makes no sense when normalized in this way). I would also that, in general, more faculty means an increased menu of choices for coursework.
