### ISSUE TITLE
Questions Regarding the Removal of Several Professors with Affiliations in the Industry

### ISSUE THREAD

**Issue by leobxpan** [emeryberger/CSrankings#812]
Hi there,

I just noticed several recent modifications which removed some professors with affiliations in the industry from the ranking list (e.g., Prof. Abhinav Gupta from CMU, Prof. Feifei Li from Stanford, Prof. Noah Smith from UW, etc). So I am wondering the specific rule of a professor being added into the ranking list ---- e.g., the professors can only take positions in the academia?. If so, I presume that only removing records after their joining into the industry may be more reasonable than entirely deleting all their related records.

Thanks,

Boxiao

**Comment by emeryberger** [comment]
Only full-time tenure-track faculty are eligible for inclusion (and there are other criteria); this includes faculty on sabbatical leaves but not faculty on leaves of absence to work in industry and not people with partial appointments.

**Comment by leobxpan** [comment]
OK I understand. Thank you.
