### ISSUE TITLE
Publication count is incorrect

### ISSUE THREAD

**Issue by amrit-singh-bedi** [emeryberger/CSrankings#8174]
not counting ICRA IROS NeurIPS AAAI ICLR papers

**Comment by emeryberger** [comment]
Please point to specific papers that are not being indexed.

**Comment by amrit-singh-bedi** [comment]
Sure, before that I wanted to mention that they were being correctly
counted till last month.

Regards,
Amrit

Amrit Singh Bedi,
Assistant Professor,
Department of Computer Science,
University of Central Florida, Orlando, FL, USA
https://sites.google.com/view/amritsinghbedi/home

**Comment by amrit-singh-bedi** [comment]
Hi, thank you for your response. I checked in detail; it is only counting papers in ICML(even if this count is not absolutely correct) and ICLR, but I am not considering any of my Neurips, ICRA, AAAI, or IROS papers. I can also provide specific links to the papers if needed.

**Comment by emeryberger** [comment]
Yes, specific papers (ideally DBLP entries).

**Comment by amrit-singh-bedi** [comment]
Thank you. I have identified the issue: my publications listed under “Amrit S. Bedi” are being indexed, but those under “Amrit Singh Bedi” are not. How can I resolve this? 

For example, this one (with name Amrit S. Bedi) is indexed https://dblp.org/rec/conf/iclr/ChakrabortyBKWM24.html

but this one (with name Amrit Singh Bedi) is not: https://dblp.org/rec/journals/corr/abs-2405-20495

**Comment by emeryberger** [comment]
Open a PR adding your (currently unlisted) alias. This is expected behavior.
>  If DBLP has multiple entries for this person, all of them need to be listed. Do not update dblp-aliases.csv.

**Comment by amrit-singh-bedi** [comment]
Hi, 

I hope you are doing well. I added my current Alias 

https://github.com/emeryberger/CSrankings/pull/8187 

But the change is still not reflected, and it is still not counting. Let me know if there are any issues with my PR. 

Regards,
Amrit
