### ISSUE TITLE
publication length

### ISSUE THREAD

**Issue by tukw** [emeryberger/CSrankings#852]
From FAQ: "Note that publications must be at least 6 pages long to be counted."

In the natural language processing field, all the top conferences (ACL, EMNLP, NAACL) have short papers that are limited to 4 pages of content (5 pages after acceptance) plus unlimited reference pages. Consequently, some of the short papers are counted in CSRankings while many others are not. Note that these papers use a two-column format and would contain 6 pages or more if converted to a single-column format. So I suggest all the short papers in these three conferences be counted (or perhaps simply reduce the paper length threshold to 5).

**Comment by fycus-tree** [comment]
For [ACL](https://dblp.org/db/conf/acl/index) and [NAACL](http://dblp.uni-trier.de/db/conf/naacl/index.html) the short paper filtering could be done by conference filtering. Only not possible in EMNLP.

**Comment by emeryberger** [comment]
Circling back to this, quite belatedly: how exactly would this filtering be done, @fycus-tree ?
