### ISSUE TITLE
Clarify R1 Inclusion criteria

### ISSUE THREAD

**Issue by fycus-tree** [emeryberger/CSrankings#857]
The current inclusion criteria state that there should be > 50 R1 institutions publishing in an area in the last 10 years. 

Using the current affiliations and dblp data since 2007, that is not true for **Logic**,  **Cryptography** and **Economics & Computation**, each of which have under 50 (with a gap of 10 until the next least popular field, graphics). 

It'd be nice to see the criteria updated to reflect this, or to have these three fields moved "below the line" as nextTier and not counted. 

| Area       | R1 uni with pubs (out of 100) |
|------------|--------------|
| act        | 69           |
| ai         | 90           |
| arch       | 65           |
| bed        | 62           |
| bio        | 62           |
| chi        | 75           |
| comm       | 57           |
| crypt      | 46           |
| da         | 60           |
| ecom       | 43           |
| graph      | 56           |
| hpc        | 77           |
| ir         | 79           |
| log        | 45           |
| metrics    | 69           |
| mlmining   | 94           |
| mobile     | 77           |
| mod        | 77           |
| nlp        | 68           |
| ops        | 57           |
| plan       | 61           |
| robotics   | 81           |
| sec        | 77           |
| soft       | 67           |
| vis        | 62           |
| vision     | 85           |

As a caveat, CSRankings is missing 15 of the 115 R1 universities
* Florida International University
* Louisiana State University
* Syracuse University
* Texas Tech University
* University at Albany, SUNY
* University of Alabama at Birmingham
* University of Cincinnati
* University of Louisville
* University of Mississippi
* University of Missouri
* University of North Texas
* University of Oklahoma
* University of Wisconsin–Milwaukee
* Wayne State University
* West Virginia University

Here's a graph
![picture1](https://user-images.githubusercontent.com/16022311/41003577-1780fba2-68e5-11e8-89a4-f42abbbec229.png)

![picture2](https://user-images.githubusercontent.com/16022311/41004177-f33cffa0-68e6-11e8-9a2b-c5c196697d22.png)

**Comment by marcniethammer** [comment]
I agree. It would be good to clarify this in the frequently asked questions. 

As this came up a couple of times now in previous discussions, it would also be good to clearly state in the FAQs that "there is a moratorium in place for adding new areas of CS through at least 2018" (#856).  Though the rationale for such a moratorium is entirely unclear to me.
