### ISSUE TITLE
There are some missing papers of Prof. Jie Tang in Tsinghua University

### ISSUE THREAD

**Issue by zfjsail** [emeryberger/CSrankings#862]
The current CSranking page shows there are 14 KDD papers for Prof. Jie Tang in Tsinghua University. There are 4 missing KDD papers since the dblp faculty entry was ambiguous previously. We have fixed this by merging these papers to corresponding dblp entry(Jie Tang 0001) in dblp database. Could you please use the latest released dblp data to add these papers? Thank you very much!

---

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

**Comment by emeryberger** [comment]
I regenerated the database (this does not happen immediately after pull requests are merged) and there are indeed 14 KDD entries for this author.

**Comment by zfjsail** [comment]
Thanks for your reply. I used the latest dblp.xml.gz just now and found there were 20 KDD entries for Prof Jie Tang. Some are short papers, but counted papers should be more than 14 papers. Would you mind checking this issue and regenerating the database again? Thank you very much! @emeryberger

**Comment by emeryberger** [comment]
Please check over `articles.json` and indicate which papers you think are missing.

**Comment by zfjsail** [comment]
The missing papers include:

[c51] Yu Han, Jie Tang:
Probabilistic Community and Role Model for Social Networks. KDD 2015: 407-416

[c28] Chenhao Tan, Lillian Lee, Jie Tang, Long Jiang, Ming Zhou, Ping Li:
User-level sentiment analysis incorporating social networks. KDD 2011: 1397-1405

[c2] Jie Tang, Hang Li, Yunbo Cao, ZhaoHui Tang:
Email data cleaning. KDD 2005: 489-498

Thanks! @emeryberger

**Comment by emeryberger** [comment]
Looks like the version of DBLP I downloaded had not merged these entries with "Jie Tang 0001". I will update. Thanks.

**Comment by zfjsail** [comment]
There were some updated papers merged to dblp entry Jie Tang 0001 these days. I have checked that the latest dblp.xml.gz incorporated these changes. The missing papers include:

[1] Yikang Shen, Wenge Rong, Nan Jiang, Baolin Peng, Jie Tang, Zhang Xiong:
Word Embedding Based Correlation Model for Question/Answer Matching. AAAI 2017: 3511-3517

[2] Yu Han, Jie Tang: 
Who to Invite Next? Predicting Invitees of Social Groups. IJCAI 2017: 3714-3720

[3] Mi Zhang, Jie Tang, Xuchen Zhang, Xiangyang Xue:
Addressing cold start in recommender systems: a semi-supervised co-training algorithm. SIGIR 2014: 73-82

[4] Conghui Zhu, Jie Tang, Hang Li, Hwee Tou Ng, Tiejun Zhao:
A Unified Tagging Approach to Text Normalization. ACL 2007

Could you please regenerate the database again? Thanks a lot! @emeryberger
