### ISSUE TITLE
University of Michigan Professors 

### ISSUE THREAD

**Issue by fycus-tree** [emeryberger/CSrankings#864]
- [Edwin Olson](https://april.eecs.umich.edu/people/ebolson/) lists himself as CEO of May Mobility, an autonomous vehicle company. It is at the top of his CV.
- [Honglak Lee](https://www.linkedin.com/in/honglak-lee-8b07709) says "I am a Research Scientist at Google Brain and also [a professor]"

I have heard that neither are taking students nor teaching classes, and are primarily at their companies. Getting confirmation one way or another would be good.

**Comment by fycus-tree** [comment]
@emeryberger if Raquel Urtasun got removed for a significant corporate role, shouldn't these two also be considered?

**Comment by havron** [comment]
Also, Martha Pollack is still listed as UMich faculty, but is currently Cornell's President (as of fall 2017: http://president.cornell.edu/.) She has an appointment as a full CS professor, but I don't think she advises PhD students anymore.

**Comment by emeryberger** [comment]
The Michigan folks mentioned in the first entry have been removed (for some time). Just moved Pollack to Cornell. Thanks.
