### ISSUE TITLE
Two professors active in AI research at the IRIDIA lab of Université Libre de Bruxelles should be included

### ISSUE THREAD

**Issue by niuneo** [emeryberger/CSrankings#910]
One is Prof. Dorigo Marco (personal page: http://code.ulb.ac.be/iridia.people.php?id=2; google scholar: https://scholar.google.com/citations?user=PwYT6EMAAAAJ&hl=en&oi=ao);
Another is Prof. Bersini Hugues (personal page: http://code.ulb.ac.be/iridia.people.php?id=1; google scholar: https://scholar.google.com/citations?user=8EdHVuYAAAAJ&hl=en&oi=ao).
Can you please add them? Thanks.

**Comment by emeryberger** [comment]
Hi -

Please submit these as pull requests.

Thanks,
-- emery
