### ISSUE TITLE
Graphs not updating based on Selected Areas/Below bar conferences

### ISSUE THREAD

**Issue by rahmati** [emeryberger/CSrankings#920]
Example below. With only the security field (+NDSS) selected, Lorrie's paper count shows as 10. Graph shows 9 security papers (discluding the NDSS paper) and 30 HCI papers. 

![screen shot 2018-07-27 at 4 03 01 pm](https://user-images.githubusercontent.com/1612598/43349737-bd392304-91b6-11e8-8d8a-c69d422b62d4.png)

**Comment by emeryberger** [comment]
Intended behavior ("feature, not a bug").
