### ISSUE TITLE
Latest DBLP update did not fetch ISBM 2018

### ISSUE THREAD

**Issue by emidec** [emeryberger/CSrankings#922]
Proceedings at https://dblp.uni-trier.de/db/journals/bioinformatics/bioinformatics34.html

**Comment by emeryberger** [comment]
Thanks. I have to enter new code to handle ISMB every year, because they don't publish it in a particular issue. If you could convey to the Bioinformatics/ISMB people that it would be great for them to (a) pick an issue number for ISMB or (b) notify me in advance, that would be most welcome.

**Comment by emeryberger** [comment]
Fixed with https://github.com/emeryberger/CSrankings/commit/e8f53af13dc3165d50056a3dbb85c36c01896fa6.

**Comment by emidec** [comment]
Thanks Emery. I will let the ISMB people know. 

It seems however that the script might be pulling from the wrong section of the issue... I noticed since I have a paper in the Proceedings of ISMB 2018 but it wasn't be fetched, while the authors added in [e8f53af](https://github.com/emeryberger/CSrankings/commit/e8f53af13dc3165d50056a3dbb85c36c01896fa6) have papers in the Bioinformatics journal, but not in the ISMB Proceedings.  

I guess the problem is that that issue (Vol 13, Issue 13) has both ISBM proceedings and regular journal papers. This seems to be a problem for 2017 as well. 

The ISMB proceedings papers are in pages iXXX-iXXX and, in the DBLP page, appear from the ISMB Proceeedings until Author Index.

Does this make sense?

Thank you,
Emiliano
