### ISSUE TITLE
New Area: Spatial Computing -- ACM SIGSPATIAL 

### ISSUE THREAD

**Issue by cshahabi** [emeryberger/CSrankings#927]
Dear Emery,

 

I attended the CS Department rankings session today at CRA and I would like to applaud your and efforts for creating the csranking site (http://csrankings.org ).

 

I was a little disappointed though that the SIGSPATIAL conference was not included in the list of conferences even though all the other ACM SIG conferences were included.  The reason may be that SIGSPATIAL is a relatively new SIG, started in 2008. 

 

In fact, I would suggest adding “spatial computing” as one of the areas under CS.  This is a new and emerging field in CS, studying the research challenges in geospatial and location-based systems, with applications in transportation, urban planning, ride-sharing, etc.  Several new industries, e.g., Uber, Lyft, Foursquare, and well-established CS companies such as Google, Oracle, Microsoft and Facebook are actively working in this area.  The researchers in this area publish mainly in the following conferences:

·      ACM SIGSPATIAL, see: http://sigspatial2018.sigspatial.org/

·      IEEE MDM, see: http://mdmconferences.org/mdm2018/

·      https://sstd2017.org/

 

and journals:

·      ACM Transactions on Spatial Algorithms and Systems, see: https://tsas.acm.org/

·      Geoinformatica, see: https://link.springer.com/journal/10707

 

In fact, this new area was highlighted on the cover of ACM CACM in 2016: https://cacm.acm.org/magazines/2016/1/195727-spatial-computing/abstract

 

If needed, I can provide more information on the participation at SIGSPATIAL and impact factor of the journals.

 

Regards,

-Cyrus

Cyrus Shahabi
Professor of Computer Science, Electrical Engineering and Spatial Sciences
Chair, Department of Computer Science 
Chair, ​ACM SIGSPATIAL

**Comment by fycus-tree** [comment]
@cshahabi I would like to point you toward #859, where I've done some unbiased analysis about research areas in CS. There are many "areas" that need to be added or reformed ( see #839 #856 #762 #367 #238).

Looking at MDM, GeoInformatica, SIGSPATIAL, they're fairly low profile and don't have a distinct publishing cluster (falling into a SIGIR,PVLDB, WWW, Commun. ACM, ICDE, SIGMOD group). I don't have the numbers in front of me, but I suspect they also fail Emery's 50 R1 criteria.

**Comment by cshahabi** [comment]
@fycus-tree According to CSrankings FAQ, to add and ACM SIG area, it should include papers from more than 50 R1 universities in the past 10 years.

We did the research and submitted an excel sheet to Emery 2.5 month ago showing that for the last 10 years of SIGSPATIAL, 2009-2018, we had (197) papers from 54 (out of 132) R1 universities. 

Isn't this sufficient to include the SIGSPATIAL conference in the site either as a separate area or at least under the database area?

Note: It is unfortunate that only US universities included in this practice as we have a lot of papers from top institutes in Europe, Australia, and Canada, but none of them is counted. Not to mention that SIGSPATIAL papers from top industries like MSR, Google, ESRI, and Facebook, are also not counted.

**Comment by marcniethammer** [comment]
@cshahabi , unfortunately there are currently no clear criteria for inclusion. Just as you, I also initially thought that fulfilling the criteria in the FAQ would be what is required (#558). Unfortunately, this does not seem to be sufficient.

Furthermore, Emery has currently put a moratorium on adding new areas. The status of this moratorium is unclear (#1422). 

As it stands there appear to be many areas that have a good case for inclusion, also based on the analysis of @fycus-tree . An incomplete list of current requests can be found here (#1422).

@emeryberger : Emery, is there an update on resolving these issues / requests? I think there are many areas that have a good case for inclusion. By excluding them the ranking becomes, in my opinion, a bit unbalanced and misleading for students.
