### ISSUE TITLE
add survey info to repo / FAQ / other

### ISSUE THREAD

**Issue by emeryberger** [emeryberger/CSrankings#928]
A number of communities have been surveyed to establish their top conferences. It would be nice to put these on-line somewhere; in the FAQ? In another page?

**Comment by fycus-tree** [comment]
I really appreciate how clear/simple/straightforward CSrankings is. Having a single FAQ/README page is pretty convenient. Any interested in "more information" is basically directed to a single page, I don't see anything wrong with that.

However! The FAQ link is kind of hard to find. The "Prominent mentions of CSrankings" gets more space. I wouldn't mind a sightly more visible FAQ link, either at the top and/or the bottom.

**Comment by emeryberger** [comment]
Survey data is now in the repo as a PDF of graphs under `docs/`. FAQ link is already in boldface immediately below the rankings; not sure much more needs to be done on that front.
