### ISSUE TITLE
NAACL-HLT 2018 not recognized

### ISSUE THREAD

**Issue by neubig** [emeryberger/CSrankings#931]
First, thanks again for the nice resource!

Anyway, I'm opening this issue because it seems that NAACL 2018 is still not recognized. I tried to fix this with the following PR, but it seems that this still didn't work: https://github.com/emeryberger/CSrankings/pull/868

I'm not sure why, and I wasn't able to easily run the software myself to see what's going wrong, but thought I'd open an issue here in the hope that someone else could figure out what's happening.

**Comment by emeryberger** [comment]
I found the problem. The file `filter.xq` also needed to be updated; this reduces the DBLP file for faster processing. Rebuilding now.

**Comment by neubig** [comment]
Thanks! I've confirmed that it's fixed now.
