### ISSUE TITLE
Bug in ISBM fetching code

### ISSUE THREAD

**Issue by emidec** [emeryberger/CSrankings#933]
Hi Emery,

Sorry for somewhat reopening #922 -- it seems that the script might be pulling from the wrong section of the Bioinformatics issue with the ISBM Proceedings. Note how authors added with https://github.com/emeryberger/CSrankings/commit/e8f53af13dc3165d50056a3dbb85c36c01896fa6 have papers in the Bioinformatics journal, but not in the ISMB Proceedings.

This is why the Bioinformatics issue (e.g., Vol 13, Issue 13 for 2018) has both ISBM proceedings and regular journal papers. This seems to be a problem for 2017 as well!

The ISMB proceedings papers are in pages iXXX-iXXX and, in the DBLP page, appear from the ISMB Proceeedings until Author Index.

Does this make sense?

Thank you,
Emiliano

**Comment by emeryberger** [comment]
Thanks, that was helpful. This numbering scheme seems to have started with volume 33. I put in logic assuming this will remain the case (updated data - missing page numbers and counts for now - in https://github.com/emeryberger/CSrankings/commit/df0e4684c99549c57b043881d0e7fda305369c26; logic in https://github.com/emeryberger/CSrankings/commit/92ac4a3469568793a3a3946becbbbbfd8eed7ea5).
