### ISSUE TITLE
Consider to add #publications for each area (or conference)

### ISSUE THREAD

**Issue by realstolz** [emeryberger/CSrankings#966]
How about showing the total number of publications during a given period for each area (or conference) selected by the user?

### For example: 

Rank institutions in [ANY] by publications from **2017** to **2017** 
- [x]  Artificial intelligence: **1,298**     
 AAAI: **638**
 IJCAI: **660**
- [x]  Operating systems: **39**
 OSDI: **0**
 SOSP: **39**

**Comment by emeryberger** [comment]
I don't see what purpose this serves for the intended audience (prospective grad students).

**Comment by realstolz** [comment]
Students may consider multiple areas and compare the number of publications directly for faculties in different areas. If so, the total number of publications in the area may help students to realize the difference between areas.

For example, from 2015 to 2018, Prof. A published 8 papers in AI area, and Prof. B published 4 papers in OS area. In their own area, Prof. A maybe not the 100th, the 200th or more, while Prof. B is the Top 5. 
(Note: the total number of publications from 2015 to 2018: AI > 4000 and OS = 116)

**Comment by emeryberger** [comment]
That's pretty oblique. One could directly count % of papers in areas and use that number. I actually wrote code to do this. It works, but I worry that it's not as clear as just listing number of papers (which of course has its disadvantages, one of which you point out here).

**Comment by realstolz** [comment]
I agree that the number of publications is intuitive and sufficient. It should be the default. The % of papers in areas is a little trivial. Thus, I suggest providing the total number of publications for areas (or conferences). It could remind students the difference between areas and may also provide students with some abstract information about the area, like the area scale, the graduation requirement, and the potential output.

Just a personal suggestion. Anyway, thanks for creating CSRankings.
