### ISSUE TITLE
Would you mind to release the codes of getting articles.json

### ISSUE THREAD

**Issue by CSerxy** [emeryberger/CSrankings#979]
@emeryberger Hi, I sincerely appreciate for your work on CSrankings. I am wondering if you could release the codes of getting articles.json from raw data in dblp? The reason I ask this is because in articles.json you just take the full papers into consideration. I want to extend this work and take the short papers into account.

**Comment by emeryberger** [comment]
It is part of the repo. The program `util/regenerate-data.py` (which does the bulk of the processing) generates both `csrankings.csv` and `articles.json` as output.

Also, you may not stand up a competitor website derived from any CSrankings data or code; this is prohibited by the license.
