### ISSUE TITLE
Non-Availability of Some Fields

### ISSUE THREAD

**Issue by nipunpruthi** [emeryberger/CSrankings#982]
Its very Good. But one thing I couldn't help but notice is as CS students also work on ECE(Electronics and Communication) fields but on the contary there is no option to also filter for ECE fields or any separate website for ECE fields. It would be nice and really will help ECE and CS students to have a website like this one.

**Comment by emeryberger** [comment]
Yes, but it's "CSrankings", not "ECErankings". Non-CS areas are not going to be included.

**Comment by nipunpruthi** [comment]
Yeah, I completely understand your point. But we can make a separate website for ECE fields. I don't know how csranking.org is getting data but surely we can use the same code for eceranking.org.

**Comment by fycus-tree** [comment]
@nipunpruthi people submit faculty affiliations and updates manually :)

**Comment by emeryberger** [comment]
@fycus-tree is correct though I initially manually entered information for around 100 institutions. And no, in fact, you can't use the code unless I agree to make it available. Not saying it's not going to happen but someone would have to seriously commit to building and maintaining a site.
