### ISSUE TITLE
Suggestion to add WSDM to "web" area

### ISSUE THREAD

**Issue by eagichtein** [emeryberger/CSrankings#99]
WSDM is one of the 3 most selective web search and IR conferences
http://dblp.uni-trier.de/db/conf/wsdm/

**Comment by shanzhenren** [comment]
Vote for adding WSDM into the "web" area. Here are the supporting evidences according to the criterions from FAQ:

- As shown in Google Scholar (https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_databasesinformationsystems), WSDM has already got higher H5-index than SIGIR (54 vs 50)
- WSDM'17 attracted 505 submissions with acceptance rate 16% (http://dl.acm.org/citation.cfm?id=3018661&CFID=799320547&CFTOKEN=60571979); versus SIGIR'17 has 362 submissions with acceptance rate 22% (http://dl.acm.org/citation.cfm?id=3077136&CFID=799320547&CFTOKEN=60571979).
